In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as plx
import seaborn as sns
import statistics as sts

In [14]:
df= pd.read_csv('/content/drive/MyDrive/Projetos/Pivic/dados/Dados/epidemiologia dengue cg/AnyConv.com__2022_SI_DENGON2642315_00.csv')
pd.set_option('display.max_columns',None)
df.head()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","ID_AGRAVO,C,5","DT_NOTIFIC,D","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","DT_SIN_PRI,D","SEM_PRI,C,6","DT_NASC,D","SOUNDEX,C,70","NU_IDADE_N,N,4,0","CS_SEXO,C,1","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_DISTRIT,C,9","ID_BAIRRO,C,8","NM_BAIRRO,C,60","ID_GEO1,C,8","ID_GEO2,C,8","CS_ZONA,C,1","ID_PAIS,C,4","DT_INVEST,D","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","DT_CHIK_S2,D","DT_PRNT,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_PRNT,C,1","DT_SORO,D","RESUL_SORO,C,1","DT_NS1,D","RESUL_NS1,C,1","DT_VIRAL,D","RESUL_VI_N,C,1","DT_PCR,D","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","DT_INTERNA,D","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CODISINF,C,4","CO_BAINF,C,8","NOBAIINF,C,60","CLASSI_FIN,C,2","CRITERIO,C,1","DOENCA_TRA,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","DT_OBITO,D","DT_ENCERRA,D","ALRM_HIPOT,C,1","ALRM_PLAQ,C,1","ALRM_VOM,C,1","ALRM_SANG,C,1","ALRM_HEMAT,C,1","ALRM_ABDOM,C,1","ALRM_LETAR,C,1","ALRM_HEPAT,C,1","ALRM_LIQ,C,1","DT_ALRM,D","GRAV_PULSO,C,1","GRAV_CONV,C,1","GRAV_ENCH,C,1","GRAV_INSUF,C,1","GRAV_TAQUI,C,1","GRAV_EXTRE,C,1","GRAV_HIPOT,C,1","GRAV_HEMAT,C,1","GRAV_MELEN,C,1","GRAV_METRO,C,1","GRAV_SANG,C,1","GRAV_AST,C,1","GRAV_MIOC,C,1","GRAV_CONSC,C,1","GRAV_ORGAO,C,1","DT_GRAV,D","MANI_HEMOR,C,1","EPISTAXE,C,1","GENGIVO,C,1","METRO,C,1","PETEQUIAS,C,1","HEMATURA,C,1","SANGRAM,C,1","LACO_N,C,1","PLASMATICO,C,1","EVIDENCIA,C,1","PLAQ_MENOR,C,7","CON_FHD,C,1","COMPLICA,C,1","NU_LOTE_I,C,9","DS_OBS,C,255","TP_SISTEMA,C,1","NDUPLIC_N,C,1","DT_DIGITA,D","DT_TRANSUS,D","DT_TRANSDM,D","DT_TRANSSM,D","DT_TRANSRM,D","DT_TRANSRS,D","DT_TRANSSE,D","NU_LOTE_V,C,7","NU_LOTE_H,C,7","CS_FLXRET,C,1","FLXRECEBI,C,7","IDENT_MICR,C,50","MIGRADO_W,C,1"
0,8721128,2,A90,03/30/22,202213,2022,35,355030,1331.0,2079127,03/21/22,202212,09/04/61,NaN,4060,M,6.0,1,8.0,25,250400,1421,NaN,NaN,JARDIM TAVARES,NaN,NaN,1.0,1,03/30/22,214205,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/22/22,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,NaN,NaN,NaN,NaN,05/30/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EXAME NS1 REALIZADO NO HOSPITAL SIRIO LIBANES,2.0,NaN,03/30/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN
1,8800907,2,A90,07/05/22,202227,2022,35,355030,1331.0,248991,06/30/22,202226,12/21/95,NaN,4026,M,6.0,9,9.0,25,250400,1421,NaN,26.0,VELAME,NaN,NaN,9.0,1,07/05/22,998999,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,09/04/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COLETADO NS1 PARA DENGUE COM RESULTADO REAGENT...,2.0,NaN,07/06/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN
2,8766916,2,A90,05/16/22,202220,2022,35,355030,1331.0,248991,05/16/22,202220,03/09/86,NaN,4036,F,5.0,9,9.0,25,250400,1421,154.0,40.0,PRATA,NaN,NaN,1.0,1,05/16/22,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,07/16/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SOLICITADO EXAMES PELA DR HELLEN C.\\\O. FERNA...,2.0,NaN,05/17/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN
3,8769004,2,A90,05/20/22,202220,2022,35,355030,1331.0,248991,05/17/22,202220,08/28/89,NaN,4032,F,5.0,1,9.0,25,250400,1421,157.0,10.0,CRUZEIRO,NaN,NaN,1.0,1,05/20/22,NaN,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,07/20/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENCAMINHADO AO PS PELA DR GIOVANA PALOPOLI - C...,2.0,NaN,05/23/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN
4,365734,2,A90,05/21/22,202220,2022,35,354580,1342.0,2082004,05/17/22,202220,10/10/87,NaN,4034,M,6.0,4,6.0,25,250400,1421,NaN,7.0,CATOLE,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,07/21/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,05/28/22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN

In [15]:
classificacao={
    5: 'DESCARTADO',
    10: 'DENGUE',
    11: 'DENGUE C/ ALARME',
    12: 'DENGUE GRAVE',
    13: 'CHIKUNGUNYA'
}
df['CLASSI_FIN,C,2']=df['CLASSI_FIN,C,2'].replace(classificacao)

In [16]:
df.shape

(1646, 146)

In [17]:
df.shape

(1646, 146)

In [18]:

df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace({
    1: 'BRANCO',
    2: 'PRETO',
    3: 'AMARELO',
    4: 'PARDO',
    5: 'INDIGENA',
    9: 'IGNORADO'
})

generos={
    'M': 'HOMEM',
    'F': 'MULHER'
}
df['CS_SEXO,C,1']=df['CS_SEXO,C,1'].replace(generos)



escolaridade={
    0: 'ANALFABETO',
    1: 'PRIMARIO INCOMPLETO',
    2: 'PRIMARIO COMPLETO',
    3: '1 GRAU INCOMPLETO',
    4: 'FUNDAMENTAL COMPLETO',
    5: 'ENSINO MÉDIO INCOMPLETO',
    6: 'ENSINO MÉDIO COMPLETO',
    7: 'SUPERIOR INCOMPLETO',
    8: 'SUPERIOR COMPLETO',
    9: 'IGNORADO',
    10: 'NÃO SE APLICA'
}
df['CS_ESCOL_N,C,2']=df['CS_ESCOL_N,C,2'].replace(escolaridade)

In [19]:
df['DT_NOTIFIC,D'] = pd.to_datetime(df['DT_NOTIFIC,D'], format='%m/%d/%y')
df['MES DO CASO'] = df['DT_NOTIFIC,D'].dt.month

In [20]:
meses = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
df['MES DO CASO'] = df['MES DO CASO'].replace(meses)

estacoes_por_mes={
    'Dezembro' : 'VERAO',
    'Janeiro': 'VERAO',
    'Fevereiro': 'VERAO',
    'Março': 'VERAO',
    'Abril': 'OUTONO',
    'Maio': 'OUTONO',
    'Junho': 'OUTONO',
    'Julho': 'INVERNO',
    'Agosto': 'INVERNO',
    'Setembro': 'INVERNO',
    'Outubro': 'PRIMAVERA',
    'Novembro': 'PRIMAVERA'
}
df['ESTACAO POR CASO']=df['MES DO CASO'].replace(estacoes_por_mes)

In [21]:
df.rename(columns={
    'DT_NOTIFIC,D': 'DATA REGISTRO',
    'CS_SEXO,C,1': 'SEXO DO PACIENTE',
    'CS_RACA,C,1': 'RAÇA',
    'CS_ESCOL_N,C,2': 'GRAU ESCOLARIDADE',
    'NM_BAIRRO,C,60': 'BAIRRO',
    'CS_ZONA,C,1': 'ZONA',
    'ID_UNIDADE,C,7': 'UNIDADE DE ATENDIMENTO',
    'DT_NASC,D': 'DATA DE NASCIMENTO',
    'CLASSI_FIN,C,2': 'CLASS DOENCA',
    'SEM_PRI,C,6': 'SEMANA EPDM',
    'DT_SIN_PRI,D': 'DATA PRIMEIROS SINTOMAS',
    'SOROTIPO,C,1': 'SOROTIPO'

},inplace=True)

In [22]:
df['DATA DE NASCIMENTO'] = pd.to_datetime(df['DATA DE NASCIMENTO'], format='%m/%d/%y', errors='coerce')

# Correcting years that are in the future (e.g., '25' interpreted as 2025 instead of 1925)
def adjust_year(date_series):
    current_year = pd.Timestamp.now().year
    adjusted_dates = []
    for date in date_series:
        if pd.isna(date):
            adjusted_dates.append(pd.NaT)
            continue
        if date.year > current_year:
            adjusted_dates.append(date - pd.DateOffset(years=100))
        else:
            adjusted_dates.append(date)
    return pd.Series(adjusted_dates, index=date_series.index)

df['DATA DE NASCIMENTO'] = adjust_year(df['DATA DE NASCIMENTO'])

# Calculate age in years
df['IDADE EM ANOS'] = (df['DATA REGISTRO'] - df['DATA DE NASCIMENTO']).dt.days / 365.25

# Round the age to the nearest integer
df['IDADE EM ANOS'] = df['IDADE EM ANOS'].round().astype('Int64')

In [23]:
df_final2022 = df[['IDADE EM ANOS', 'SEXO DO PACIENTE','RAÇA','ESTACAO POR CASO','MES DO CASO','GRAU ESCOLARIDADE','BAIRRO','ZONA','UNIDADE DE ATENDIMENTO','DATA REGISTRO', 'CLASS DOENCA','SEMANA EPDM', 'DATA PRIMEIROS SINTOMAS','SOROTIPO']]

In [24]:
df_final2022 = df_final2022[df_final2022['CLASS DOENCA'] != 'DESCARTADO']
df_final2022 = df_final2022[df_final2022['CLASS DOENCA'] != 'CHIKUNGUNYA']
df_final2022 = df_final2022[df_final2022['CLASS DOENCA'] != 8]

In [25]:
df_final2022['DATA REGISTRO'] = df_final2022['DATA REGISTRO'].dt.year

In [26]:
df_final2022['SEMANA EPDM'] = df_final2022['SEMANA EPDM'].astype(str).str[-2:]

In [27]:
np.unique(df_final2022['SEXO DO PACIENTE'].astype(str), return_counts=True)

(array(['HOMEM', 'MULHER'], dtype=object), array([103, 133]))

In [28]:
normalize_sex={
    'I':'MULHER'
}
df_final2022['SEXO DO PACIENTE']=df_final2022['SEXO DO PACIENTE'].replace(normalize_sex)

In [29]:
np.unique(df_final2022['IDADE EM ANOS'],return_counts=True)

(array([ 0,  2,  3,  4,  5,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55,
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 72, 73, 74, 77, 78,
        83, 84]),
 array([ 1,  1,  1,  1,  4,  2,  1,  1,  1,  1,  3,  1,  3,  4,  4,  2,  3,
         8,  5,  5,  6,  5,  4,  4,  6,  5,  3,  4,  4,  4,  2,  2,  8,  3,
         2,  5,  5,  1,  4,  4,  5,  5,  3,  3,  3,  4, 11,  2,  6,  7,  1,
         3,  3,  5,  7,  8,  3,  1,  1,  1,  7,  2,  1,  3,  1,  2,  1,  1,
         2,  1]))

In [30]:
df_final2022.replace(df_final2022['IDADE EM ANOS']=='nan', 24,inplace=True)

In [31]:
np.unique(df_final2022['RAÇA'].astype(str),return_counts=True)

(array(['AMARELO', 'BRANCO', 'IGNORADO', 'PARDO', 'PRETO'], dtype=object),
 array([ 15,  35,   7, 176,   3]))

In [32]:
df_final2022.replace(df_final2022['RAÇA']=='IGNORADO', 'PARDO',inplace=True)

In [33]:
normalize_bairros={
    'ALUISIO CAMPOS': 'ALUIZIO CAMPOS',
    'JURACI PALHANO': 'JURACY PALHANO',
    'NOVA BRAS═LIA': 'NOVA BRASILIA',
    'SAO JO': 'SAO JOSE',
    'S├O JOS╔': 'SAO JOSE',
    'RUA DR MARCELINO DE OLIVEIRA': 'MALVINAS',
    'TRES IRMAES': 'TRES IRMAS',
    'AV COSTA E SILVA': 'JARDIM QUARENTA'
}
df_final2022['BAIRRO']=df_final2022['BAIRRO'].replace(normalize_bairros)

In [34]:
np.unique(df_final2022['BAIRRO'].astype(str),return_counts=True)

(array(['ACACIO FIGUEIREDO', 'ALTO BRANCO', 'ALUIZIO CAMPOS', 'ARAXA',
        'BAIRRO UNIVERSITARIO', 'BELA VISTA', 'BODOCONGO',
        'CASTELO BRANCO', 'CATOLE', 'CATOLE ZE FERREIRA', 'CENTRO',
        'CINZA', 'CONCEICAO', 'CRUZEIRO', 'CUITES', 'DINAMERICA',
        'DISTRITO INDUSTRIAL', 'ESTACAO VELHA', 'GALANTE', 'GENIPAPO',
        'ITARARE', 'JARDIM AMERICA', 'JARDIM ATALAIA',
        'JARDIM CONTINENTAL', 'JARDIM PAULISTANO', 'JARDIM QUARENTA',
        'JARDIM TAVARES', 'JEREMIAS', 'JOSE PINHEIRO', 'JURACY PALHANO',
        'LIBERDADE', 'LUCAS', 'MALVINAS', 'MALVINAS I', 'MIRANTE',
        'MONTE CASTELO', 'MONTE SANTO', 'NOVA BRASILIA', 'NOVO CRUZEIRO',
        'NOVO HORIZONTE', 'PALMEIRA', 'PEDREGAL', 'PRATA',
        'PRESIDENTE MEDICE', 'RAMADINHA', 'ROCHA CAVALCANTE',
        'SANDRA CAVALCANTE', 'SANTA ROSA', 'SANTO ANTONIO', 'SAO JOSE',
        'SAO JOSE DA MATA', 'SERROTAO', 'TAMBOR', 'TRES IRMAS',
        'UNIVERSITARIO', 'VELAME', 'VILA CABRAL', 'ZONA RURAL', 'nan'],
       dtype=object),
 array([ 3,  4, 13,  2,  2,  2, 10,  1, 21,  1,  5,  2,  2,  3,  1,  4, 11,
         2,  4,  1,  2,  1,  1,  1,  2,  2,  4,  4,  8,  1,  3,  1, 17,  2,
         3,  3,  3,  6,  1,  7,  2,  1,  1,  8,  1,  1,  2,  3,  8,  2,  5,
         4,  4, 10,  2,  4,  1,  1, 10]))

In [35]:
bairros={
    'GENIPAPO':'JENIPAPO',
    'LUCAS':'SITIO LUCAS',
    'MALVINAS I': 'MALVINAS',
    'NOVO CRUZEIRO': 'CRUZEIRO',
    'PRESIDENTE MEDICI': 'PRESIDENTE MEDICE',
    'UNIVERSITARIO': 'BAIRRO UNIVERSITARIO',
    'ZONA RURAL': 'SITIO LUCAS'
}

In [36]:
# Calculate the frequency of each neighborhood
neighborhood_frequency = df_final2022['BAIRRO'].value_counts().reset_index()
neighborhood_frequency.columns = ['Bairro', 'Frequência']

# Sort the DataFrame by frequency in descending order
neighborhood_frequency = neighborhood_frequency.sort_values(by='Frequência', ascending=False)

# Get the top N neighborhoods for better visualization (optional, adjust N as needed)
# For now, let's display all, but if there are too many, we might limit it.
# neighborhood_frequency_top = neighborhood_frequency.head(20)

# Create the bar chart
fig = plx.bar(
    neighborhood_frequency,
    x='Bairro',
    y='Frequência',
    title='Frequência de Casos por Bairro',
    labels={'Bairro': 'Bairro', 'Frequência': 'Número de Casos'},
    color_discrete_sequence=plx.colors.qualitative.Pastel
)

fig.update_layout(
    xaxis_title='Bairro',
    yaxis_title='Número de Casos',
    xaxis_tickangle=-45 # Rotate x-axis labels for better readability
)

fig.show()

In [37]:
df_final2022

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
0,61,HOMEM,BRANCO,VERAO,Março,SUPERIOR COMPLETO,JARDIM TAVARES,1.0,2079127,2022,DENGUE,12,03/21/22,NaN
14,24,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,TRES IRMAS,1.0,2363275,2022,DENGUE,21,05/22/22,NaN
18,26,MULHER,PARDO,VERAO,Janeiro,1 GRAU INCOMPLETO,JARDIM TAVARES,1.0,7052251,2022,DENGUE,04,01/23/22,NaN
43,57,HOMEM,PARDO,VERAO,Março,ENSINO MÉDIO INCOMPLETO,JOSE PINHEIRO,1.0,2363275,2022,DENGUE,07,02/17/22,NaN
49,36,HOMEM,PARDO,VERAO,Fevereiro,ENSINO MÉDIO INCOMPLETO,ALTO BRANCO,1.0,7052251,2022,DENGUE,07,02/19/22,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,27,HOMEM,IGNORADO,INVERNO,Agosto,IGNORADO,BAIRRO UNIVERSITARIO,1.0,2399989,2022,DENGUE,33,08/19/22,NaN
1641,28,HOMEM,PARDO,OUTONO,Abril,NaN,LIBERDADE,1.0,6940315,2022,DENGUE,15,04/14/22,NaN
1642,32,MULHER,PARDO,OUTONO,Maio,IGNORADO,JOSE PINHEIRO,1.0,9132686,2022,DENGUE,19,05/11/22,NaN
1643,30,MULHER,PARDO,PRIMAVERA,Outubro,IGNORADO,CENTRO,1.0,2399989,2022,NaN,43,10/26/22,NaN
1645,50,HOMEM,PARDO,OUTONO,Abril,NaN,NaN,9.0,3019608,2022,DENGUE,15,04/14/22,NaN

In [38]:
import pandas as pd
import numpy as np

unidades = {
    # --- Campina Grande (Rede Própria, Conveniada e SUS) ---
    2079127: "HOSPITAL DA FAP",
    2082004: "CLINICA PROMEDICA",
    220337:  "HOSPITAL DE CLINICAS DE CAMPINA GRANDE",
    2313642: "POLYCLINICA",
    2341220: "CLINICA DR WANDERLEY",
    2342367: "CLINICA DE OLHOS DR REINALDO",
    2357100: "CLINICA DOM BOSCO",
    2362198: "CENTRO DE SAUDE DE SAO JOSE DA MATA",
    2362228: "CENTRO DE SAUDE DA PALMEIRA",
    2362287: "INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA",
    2362295: "SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE", # Sede administrativa/SMS
    2362317: "CENTRO DE SAUDE DA LIBERDADE",
    2362341: "CENTRO DE SAUDE DE CATOLE",
    2362392: "CENTRO DE SAUDE FRANCISCO PINTO",
    2362600: "CAPS II",
    2362627: "CAPS AD",
    2362651: "CEREST REGIONAL CAMPINA GRANDE",
    2362678: "CENTRO DE ESPECIALIDADES ODONTOLOGICAS CEO",
    2362716: "POLICLINICA DAS MALVINAS",
    2362740: "UNIDADE MISTA DE GALANTE",
    2362759: "HOSPITAL JOAO RIBEIRO",
    2362767: "APAE CAMPINA GRANDE",
    2362821: "HEMOCENTRO REGIONAL DE CAMPINA GRANDE",
    2362856: "HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES",
    2362880: "HOSPITAL MUNICIPAL DR EDGLEY",
    2363070: "HOSPITAL MUNICIPAL PEDRO I",
    2363275: "VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE",
    248991:  "LABORATORIO PREANALITICA (PRIVADO)",
    2591871: "UBS CATINGUEIRA",
    2595370: "UBS BENICIO BURITI",
    2595389: "UBS MARIA DE LOURDES LEONE",
    2595397: "UBS ROMUPLO GOUVEIA",
    2595435: "UBS RAIMUNDO CARNEIRO",
    2595443: "UBS HORACINA DE ALMEIDA",
    2595451: "UBS CAMPINA GRANDE (BODOCONGO)",
    2605937: "UBS CONJUNTO SEVERINO CABRAL",
    2605953: "UBS BAIRRO DAS CIDADES",
    2607123: "HOSPITAL DE OLHOS DA PARAIBA",
    2612771: "UBS ALTO BRANCO",
    2612992: "UBS NACOES",
    2613611: "UBS MONTE CASTELO",
    2613735: "UBS NOVA BRASILIA",
    2676060: "HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO",
    2677725: "SVO - SERVICO DE VERIFICACAO DE OBITO",
    2712032: "UBS JD QUARENTA",
    2715317: "SAMU 192 CAMPINA GRANDE",
    2763001: "CLINICA DE FRATURAS E ORTOPEDIA",
    2792753: "UBS ANTONIO VIRGILIO BRASILEIRO SILVA",
    2792796: "UBS MALVINAS IV",
    2792877: "UBS PRESIDENTE MEDICI",
    3006204: "CLINICA SANTA CLARA",
    3019608: "UPA 24H DRA ADELE DE ALMEIDA (MALVINAS)", # Antiga ref, atual Dinamérica costuma ser outro cod, mas mantido registro
    4014138: "UBS SAO JANUARIO",
    5053129: "UBS PARQUE DO SOL",
    5053137: "UBS SITIO SALGADINHO",
    5053242: "UBS RESSURREICAO",
    5053269: "UBS JARDIM VERDEJANTE",
    5116279: "UBS CRISTIANO RIBEIRO",
    5116449: "UBS MUTIRAO",
    5485754: "UBS VILA NOVA DA RAINHA",
    5491215: "UBS TAMBOR",
    5617332: "UBS LIBERDADE I",
    5932416: "UBS PEDREGAL I E II",
    5968992: "UBS SANTA ROSA I E II",
    6045340: "LABORATORIO MAURILIO DE ALMEIDA",
    6267939: "CENTRO DE GENETICA MEDICA",
    6531288: "UBS BAIRRO DOS CIDADES II",
    7052251: "UPA 24 HORAS DR MAIA (ALTO BRANCO)",
    7113692: "HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO",
    9374833: "UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA)",

    # --- Externos (João Pessoa, Outros Municípios e Estados) ---
    2399318: "COMPLEXO PSIQUIATRICO JULIANO MOREIRA (JOAO PESSOA)",
    2399717: "HOSPITAL DE TRAUMA SENADOR HUMBERTO LUCENA (JOAO PESSOA)",
    2399989: "HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA)",
    2400243: "INSTITUTO CANDIDA VARGAS (JOAO PESSOA)",
    2400324: "COMPLEXO HOSPITALAR DE MANGABEIRA (ORTOTRAUMA JP)",
    2595427: "SECRETARIA MUNICIPAL DE SAUDE (OUTRO)",
    2613166: "UBSF ZUMBI (PATOS)", # Codigo genérico as vezes
    3886689: "HOSPITAL SAO VICENTE DE PAULO (JOAO PESSOA)",
    6940315: "UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)",
    6962831: "UPA 24H SOBEUS (GUARABIRA)", # Verificação necessária, pode ser regional
    7408765: "UPA 24H NOVA ESPERANCA (PARNAMIRIM-RN)",
    7520972: "UPA 24H TIBIRIO (SANTA RITA)",
    7633149: "UPA 24H PRINCESA ISABEL (PRINCESA ISABEL)",
    7764480: "UPA 24H MONTEIRO (MONTEIRO)",
    7904894: "UPA 24H GUARABIRA (GUARABIRA)",
    9132686: "UPA 24H VALENTINA (JOAO PESSOA)",
    9352899: "UPA 24H CRUZ DAS ARMAS (JOAO PESSOA)",
    9352937: "UPA 24H SANTA RITA (SANTA RITA)",
    9361936: "UPA 24H CIDADE SATELITE (NATAL-RN)",
    9387927: "UPA 24H SAO BENTO (SAO BENTO)",
    9667687: "UPA 24H POMBAL (POMBAL)",

    # --- Erros / Indefinidos ---
    1120:    "CODIGO INVALIDO (ERRO DE REGISTRO)"
}

# 2. Lista apenas com os IDs de Campina Grande (Cód Mun 250400)
# (Filtrado para garantir que unidades de JP/Outros não entrem como 'Campina Grande')
ids_campina_grande = [
    2079127, 2082004, 220337, 2313642, 2341220, 2342367, 2357100,
    2362198, 2362228, 2362287, 2362295, 2362317, 2362341, 2362392,
    2362600, 2362627, 2362651, 2362678, 2362716, 2362740, 2362759,
    2362767, 2362821, 2362856, 2362880, 2363070, 2363275, 248991,
    2591871, 2595370, 2595389, 2595397, 2595435, 2595443, 2595451,
    2605937, 2605953, 2607123, 2612771, 2612992, 2613611, 2613735,
    2676060, 2677725, 2712032, 2715317, 2763001, 2792753, 2792796,
    2792877, 3006204, 3019608, 4014138, 5053129, 5053137, 5053242,
    5053269, 5116279, 5116449, 5485754, 5491215, 5617332, 5932416,
    5968992, 6045340, 6267939, 6531288, 7052251, 7113692, 9374833
]

# --- APLICAÇÃO NO DATAFRAME ---

# Certifique-se de que a coluna é numérica para bater com as chaves do dicionário
# df_final2023['UNIDADE DE ATENDIMENTO'] = pd.to_numeric(df_final2023['UNIDADE DE ATENDIMENTO'], errors='coerce')

# 1. Cria a coluna de Classificação (Interno/Externo) ANTES da substituição
df_final2022['ORIGEM_UNIDADE'] = np.where(
    df_final2022['UNIDADE DE ATENDIMENTO'].isin(ids_campina_grande),
    'Campina Grande',
    'Externo/Outro'
)

# 2. Substitui os códigos pelos nomes
df_final2022['UNIDADE DE ATENDIMENTO'] = df_final2022['UNIDADE DE ATENDIMENTO'].replace(unidades)

In [39]:
np.unique(df_final2022['UNIDADE DE ATENDIMENTO'].astype(str),return_counts=True)

(array(['APAE CAMPINA GRANDE',
        'CENTRO DE ESPECIALIDADES ODONTOLOGICAS CEO',
        'CENTRO DE GENETICA MEDICA', 'CENTRO DE SAUDE DA PALMEIRA',
        'CLINICA SANTA CLARA', 'CODIGO INVALIDO (ERRO DE REGISTRO)',
        'COMPLEXO HOSPITALAR DE MANGABEIRA (ORTOTRAUMA JP)',
        'COMPLEXO PSIQUIATRICO JULIANO MOREIRA (JOAO PESSOA)',
        'HOSPITAL DA FAP', 'HOSPITAL DE CLINICAS DE CAMPINA GRANDE',
        'HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES',
        'HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA)',
        'HOSPITAL JOAO RIBEIRO', 'HOSPITAL MUNICIPAL DR EDGLEY',
        'HOSPITAL MUNICIPAL PEDRO I',
        'HOSPITAL SAO VICENTE DE PAULO (JOAO PESSOA)',
        'HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO',
        'INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA',
        'LABORATORIO MAURILIO DE ALMEIDA', 'POLYCLINICA',
        'UBS BENICIO BURITI', 'UBS CAMPINA GRANDE (BODOCONGO)',
        'UBS HORACINA DE ALMEIDA', 'UBS JARDIM VERDEJANTE',
        'UBS LIBERDADE I', 'UBS MARIA DE LOURDES LEONE', 'UBS MUTIRAO',
        'UBS PARQUE DO SOL', 'UBS RESSURREICAO', 'UBS SANTA ROSA I E II',
        'UBS SITIO SALGADINHO', 'UBS TAMBOR',
        'UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA)',
        'UPA 24 HORAS DR MAIA (ALTO BRANCO)',
        'UPA 24H CRUZ DAS ARMAS (JOAO PESSOA)',
        'UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)',
        'UPA 24H DRA ADELE DE ALMEIDA (MALVINAS)',
        'UPA 24H SAO BENTO (SAO BENTO)', 'UPA 24H TIBIRIO (SANTA RITA)',
        'UPA 24H VALENTINA (JOAO PESSOA)',
        'VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE'], dtype=object),
 array([ 7,  1,  4,  1,  1,  1,  1,  1,  1,  1, 17,  2,  1,  3,  4,  3, 15,
         1,  1,  1,  1, 12,  2,  2,  1,  1,  1,  2,  1, 17,  3,  1,  5, 55,
         1,  1,  1,  5,  1,  2, 54]))

In [40]:
df_final2022['UNIDADE DE ATENDIMENTO'].value_counts()

UNIDADE DE ATENDIMENTO
UPA 24 HORAS DR MAIA (ALTO BRANCO)                            55
VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE                   54
HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES    17
UBS SANTA ROSA I E II                                         17
HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO                       15
UBS CAMPINA GRANDE (BODOCONGO)                                12
APAE CAMPINA GRANDE                                            7
UPA 24H SAO BENTO (SAO BENTO)                                  5
UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA)                    5
CENTRO DE GENETICA MEDICA                                      4
HOSPITAL MUNICIPAL PEDRO I                                     4
HOSPITAL MUNICIPAL DR EDGLEY                                   3
UBS SITIO SALGADINHO                                           3
HOSPITAL SAO VICENTE DE PAULO (JOAO PESSOA)                    3
UPA 24H VALENTINA (JOAO PESSOA)                                2
HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA)                   2
UBS JARDIM VERDEJANTE                                          2
UBS PARQUE DO SOL                                              2
UBS HORACINA DE ALMEIDA                                        2
POLYCLINICA                                                    1
HOSPITAL DA FAP                                                1
LABORATORIO MAURILIO DE ALMEIDA                                1
UBS MARIA DE LOURDES LEONE                                     1
INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA                     1
CLINICA SANTA CLARA                                            1
UBS RESSURREICAO                                               1
CENTRO DE SAUDE DA PALMEIRA                                    1
UBS BENICIO BURITI                                             1
UBS TAMBOR                                                     1
HOSPITAL DE CLINICAS DE CAMPINA GRANDE                         1
UPA 24H CRUZ DAS ARMAS (JOAO PESSOA)                           1
CENTRO DE ESPECIALIDADES ODONTOLOGICAS CEO                     1
HOSPITAL JOAO RIBEIRO                                          1
UBS LIBERDADE I                                                1
UBS MUTIRAO                                                    1
CODIGO INVALIDO (ERRO DE REGISTRO)                             1
COMPLEXO HOSPITALAR DE MANGABEIRA (ORTOTRAUMA JP)              1
COMPLEXO PSIQUIATRICO JULIANO MOREIRA (JOAO PESSOA)            1
UPA 24H TIBIRIO (SANTA RITA)                                   1
UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)                     1
UPA 24H DRA ADELE DE ALMEIDA (MALVINAS)                        1
Name: count, dtype: int64

In [41]:
zonas={
    1: 'URBANA',
    2: 'RURAL',
    3: 'PERIURBANA',
    9: 'NAO INFORMADO'
}
df_final2022['ZONA']=df_final2022['ZONA'].replace(zonas)

In [42]:
df_final2022['ZONA'].value_counts()

ZONA
URBANA           226
RURAL              5
NAO INFORMADO      1
Name: count, dtype: int64

In [43]:
df_final2022['ZONA']=df_final2022['ZONA'].replace('NAO INFORMADO', 'URBANA')

In [44]:
df_final2022

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,61,HOMEM,BRANCO,VERAO,Março,SUPERIOR COMPLETO,JARDIM TAVARES,URBANA,HOSPITAL DA FAP,2022,DENGUE,12,03/21/22,NaN,Campina Grande
14,24,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,TRES IRMAS,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2022,DENGUE,21,05/22/22,NaN,Campina Grande
18,26,MULHER,PARDO,VERAO,Janeiro,1 GRAU INCOMPLETO,JARDIM TAVARES,URBANA,UPA 24 HORAS DR MAIA (ALTO BRANCO),2022,DENGUE,04,01/23/22,NaN,Campina Grande
43,57,HOMEM,PARDO,VERAO,Março,ENSINO MÉDIO INCOMPLETO,JOSE PINHEIRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2022,DENGUE,07,02/17/22,NaN,Campina Grande
49,36,HOMEM,PARDO,VERAO,Fevereiro,ENSINO MÉDIO INCOMPLETO,ALTO BRANCO,URBANA,UPA 24 HORAS DR MAIA (ALTO BRANCO),2022,DENGUE,07,02/19/22,NaN,Campina Grande
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,27,HOMEM,IGNORADO,INVERNO,Agosto,IGNORADO,BAIRRO UNIVERSITARIO,URBANA,HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA),2022,DENGUE,33,08/19/22,NaN,Externo/Outro
1641,28,HOMEM,PARDO,OUTONO,Abril,NaN,LIBERDADE,URBANA,UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS),2022,DENGUE,15,04/14/22,NaN,Externo/Outro
1642,32,MULHER,PARDO,OUTONO,Maio,IGNORADO,JOSE PINHEIRO,URBANA,UPA 24H VALENTINA (JOAO PESSOA),2022,DENGUE,19,05/11/22,NaN,Externo/Outro
1643,30,MULHER,PARDO,PRIMAVERA,Outubro,IGNORADO,CENTRO,URBANA,HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA),2022,NaN,43,10/26/22,NaN,Externo/Outro
1645,50,HOMEM,PARDO,OUTONO,Abril,NaN,NaN,URBANA,UPA 24H DRA ADELE DE ALMEIDA (MALVINAS),2022,DENGUE,15,04/14/22,NaN,Campina Grande

In [45]:
df_final2022['GRAU ESCOLARIDADE'].value_counts()

GRAU ESCOLARIDADE
IGNORADO                   54
ENSINO MÉDIO COMPLETO      46
ENSINO MÉDIO INCOMPLETO    44
1 GRAU INCOMPLETO          22
FUNDAMENTAL COMPLETO       17
SUPERIOR COMPLETO          14
PRIMARIO INCOMPLETO        10
NÃO SE APLICA               9
SUPERIOR INCOMPLETO         3
PRIMARIO COMPLETO           1
Name: count, dtype: int64

In [46]:
df_final2022.head()

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,61,HOMEM,BRANCO,VERAO,Março,SUPERIOR COMPLETO,JARDIM TAVARES,URBANA,HOSPITAL DA FAP,2022,DENGUE,12,03/21/22,NaN,Campina Grande
14,24,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,TRES IRMAS,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2022,DENGUE,21,05/22/22,NaN,Campina Grande
18,26,MULHER,PARDO,VERAO,Janeiro,1 GRAU INCOMPLETO,JARDIM TAVARES,URBANA,UPA 24 HORAS DR MAIA (ALTO BRANCO),2022,DENGUE,04,01/23/22,NaN,Campina Grande
43,57,HOMEM,PARDO,VERAO,Março,ENSINO MÉDIO INCOMPLETO,JOSE PINHEIRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2022,DENGUE,07,02/17/22,NaN,Campina Grande
49,36,HOMEM,PARDO,VERAO,Fevereiro,ENSINO MÉDIO INCOMPLETO,ALTO BRANCO,URBANA,UPA 24 HORAS DR MAIA (ALTO BRANCO),2022,DENGUE,07,02/19/22,NaN,Campina Grande

In [47]:
df_final2022.fillna('URBANA',inplace=True)

/tmp/ipython-input-2728704030.py:1: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'URBANA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

In [48]:
df_final2022['GRAU ESCOLARIDADE'].replace('IGNORADO','ENSINO MÉDIO COMPLETO',inplace=True)

/tmp/ipython-input-2556923203.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [49]:
df_final2022['CLASS DOENCA'].value_counts()

CLASS DOENCA
DENGUE              228
DENGUE C/ ALARME      6
DENGUE GRAVE          1
URBANA                1
Name: count, dtype: int64

In [51]:
df_final2022.to_csv('dengue2022_tratado.csv',index=False)