In [242]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as plx
import matplotlib.pyplot as plt

In [243]:
df= pd.read_csv('/content/drive/MyDrive/Projetos/Pivic/dados/Dados/epidemiologia dengue cg/AnyConv.com__2023_SI_DENGON2642313_00.csv')
pd.set_option('display.max_columns', None)
df.head()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","ID_AGRAVO,C,5","DT_NOTIFIC,D","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","DT_SIN_PRI,D","SEM_PRI,C,6","DT_NASC,D","SOUNDEX,C,70","NU_IDADE_N,N,4,0","CS_SEXO,C,1","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_DISTRIT,C,9","ID_BAIRRO,C,8","NM_BAIRRO,C,60","ID_GEO1,C,8","ID_GEO2,C,8","CS_ZONA,C,1","ID_PAIS,C,4","DT_INVEST,D","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","DT_CHIK_S2,D","DT_PRNT,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_PRNT,C,1","DT_SORO,D","RESUL_SORO,C,1","DT_NS1,D","RESUL_NS1,C,1","DT_VIRAL,D","RESUL_VI_N,C,1","DT_PCR,D","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","DT_INTERNA,D","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CODISINF,C,4","CO_BAINF,C,8","NOBAIINF,C,60","CLASSI_FIN,C,2","CRITERIO,C,1","DOENCA_TRA,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","DT_OBITO,D","DT_ENCERRA,D","ALRM_HIPOT,C,1","ALRM_PLAQ,C,1","ALRM_VOM,C,1","ALRM_SANG,C,1","ALRM_HEMAT,C,1","ALRM_ABDOM,C,1","ALRM_LETAR,C,1","ALRM_HEPAT,C,1","ALRM_LIQ,C,1","DT_ALRM,D","GRAV_PULSO,C,1","GRAV_CONV,C,1","GRAV_ENCH,C,1","GRAV_INSUF,C,1","GRAV_TAQUI,C,1","GRAV_EXTRE,C,1","GRAV_HIPOT,C,1","GRAV_HEMAT,C,1","GRAV_MELEN,C,1","GRAV_METRO,C,1","GRAV_SANG,C,1","GRAV_AST,C,1","GRAV_MIOC,C,1","GRAV_CONSC,C,1","GRAV_ORGAO,C,1","DT_GRAV,D","MANI_HEMOR,C,1","EPISTAXE,C,1","GENGIVO,C,1","METRO,C,1","PETEQUIAS,C,1","HEMATURA,C,1","SANGRAM,C,1","LACO_N,C,1","PLASMATICO,C,1","EVIDENCIA,C,1","PLAQ_MENOR,C,7","CON_FHD,C,1","COMPLICA,C,1","NU_LOTE_I,C,9","DS_OBS,C,255","TP_SISTEMA,C,1","NDUPLIC_N,C,1","DT_DIGITA,D","DT_TRANSUS,D","DT_TRANSDM,D","DT_TRANSSM,D","DT_TRANSRM,D","DT_TRANSRS,D","DT_TRANSSE,D","NU_LOTE_V,C,7","NU_LOTE_H,C,7","CS_FLXRET,C,1","FLXRECEBI,C,7","IDENT_MICR,C,50","MIGRADO_W,C,1"
0,590009,2,A90,04/28/23,202317,2023,35,350840,1342,2031779,04/23/23,202317,03/31/87,NaN,4036,M,6,1,6.0,25,250400,1421,NaN,506.0,PRESIDENTE MEDICE,NaN,NaN,1.0,1,04/28/23,NaN,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,05/04/23,1.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,NaN,NaN,1.0,NaN,05/24/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,05/02/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN
1,7632361,2,A90,05/03/23,202318,2023,41,410830,1363,2593904,04/29/23,202317,09/03/60,NaN,4062,F,5,1,9.0,25,250400,1421,NaN,3.0,ALTO BRANCO,NaN,NaN,1.0,1,05/03/23,NaN,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,07/03/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PACIENTE DE CAMPINA GRANDE, CHEGOU EM FOZ H┴ 2...",2,NaN,05/03/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN
2,2014789,2,A90,04/11/23,202315,2023,24,240810,1416,7408765,04/09/23,202315,07/03/84,NaN,4038,M,6,9,9.0,25,250400,1421,NaN,37.0,SERROTAO,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,06/11/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,04/11/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,7,NaN
3,2013459,2,A90,04/15/23,202315,2023,24,240810,1416,9361936,04/10/23,202315,12/22/88,NaN,4034,F,9,9,9.0,25,250400,1421,154.0,5.0,BODOCONGO,NaN,NaN,9.0,1,04/15/23,NaN,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,10,2.0,NaN,NaN,9.0,NaN,04/15/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,04/15/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,7,NaN
4,80800,2,A90,01/02/23,202301,2023,25,250400,1421,7052251,12/28/22,202252,06/09/03,NaN,4019,F,5,4,6.0,25,250400,1421,158.0,603.0,MALVINAS,NaN,NaN,1.0,1,01/02/23,999992.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2.0,NaN,1.0,1.0,NaN,02/15/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,01/04/23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN

In [244]:
df['SOROTIPO,C,1'].isnull().sum()

np.int64(708)

In [245]:
classificacao={
    5: 'DESCARTADO',
    10: 'DENGUE',
    11: 'DENGUE C/ ALARME',
    12: 'DENGUE GRAVE',
    13: 'CHIKUNGUNYA'
}
df['CLASSI_FIN,C,2']=df['CLASSI_FIN,C,2'].replace(classificacao)

In [246]:
sorotipos={
    1:'DENV 1',
    2: 'DENV 2',
    3: 'DENV 3',
    4: 'DENV 4'
}
df['SOROTIPO,C,1']=df['SOROTIPO,C,1'].replace(sorotipos)

In [247]:
df.shape

(708, 146)

In [248]:
df.shape

(708, 146)

In [249]:
df.describe()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","SEM_PRI,C,6","SOUNDEX,C,70","NU_IDADE_N,N,4,0","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_DISTRIT,C,9","ID_BAIRRO,C,8","ID_GEO1,C,8","ID_GEO2,C,8","CS_ZONA,C,1","ID_PAIS,C,4","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","DT_CHIK_S2,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_PRNT,C,1","RESUL_SORO,C,1","RESUL_NS1,C,1","RESUL_VI_N,C,1","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CODISINF,C,4","CO_BAINF,C,8","CRITERIO,C,1","DOENCA_TRA,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","ALRM_HIPOT,C,1","ALRM_PLAQ,C,1","ALRM_VOM,C,1","ALRM_SANG,C,1","ALRM_HEMAT,C,1","ALRM_ABDOM,C,1","ALRM_LETAR,C,1","ALRM_HEPAT,C,1","ALRM_LIQ,C,1","GRAV_PULSO,C,1","GRAV_CONV,C,1","GRAV_ENCH,C,1","GRAV_INSUF,C,1","GRAV_TAQUI,C,1","GRAV_EXTRE,C,1","GRAV_HIPOT,C,1","GRAV_HEMAT,C,1","GRAV_MELEN,C,1","GRAV_METRO,C,1","GRAV_SANG,C,1","GRAV_AST,C,1","GRAV_MIOC,C,1","GRAV_CONSC,C,1","GRAV_ORGAO,C,1","DT_GRAV,D","MANI_HEMOR,C,1","EPISTAXE,C,1","GENGIVO,C,1","METRO,C,1","PETEQUIAS,C,1","HEMATURA,C,1","SANGRAM,C,1","LACO_N,C,1","PLASMATICO,C,1","EVIDENCIA,C,1","PLAQ_MENOR,C,7","CON_FHD,C,1","COMPLICA,C,1","NU_LOTE_I,C,9","TP_SISTEMA,C,1","NDUPLIC_N,C,1","DT_TRANSUS,D","DT_TRANSDM,D","DT_TRANSSM,D","DT_TRANSRM,D","DT_TRANSRS,D","DT_TRANSSE,D","NU_LOTE_V,C,7","NU_LOTE_H,C,7","CS_FLXRET,C,1","FLXRECEBI,C,7","IDENT_MICR,C,50","MIGRADO_W,C,1"
count,7.080000e+02,708.0,708.000000,708.0,708.000000,708.000000,708.000000,7.080000e+02,708.000000,0.0,708.000000,708.000000,708.000000,694.000000,708.0,708.0,708.0,577.000000,662.000000,1.0,1.0,699.000000,708.0,345.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.0,706.0,0.0,0.0,1.0,1.0,1.0,104.000000,95.000000,92.000000,95.000000,0.0,39.0,44.000000,611.000000,22.000000,22.000000,2.200000e+01,16.0,1.600000e+01,19.000000,15.0,15.0,14.0,7.000000,7.000000,612.000000,0.0,78.000000,596.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,708.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,708.000000,0.0,708.000000,0.0
mean,1.458242e+05,2.0,202324.201977,2023.0,25.045198,250860.310734,1420.738701,6.304770e+06,202320.779661,NaN,4020.430791,5.384181,3.991525,6.157061,25.0,250400.0,1421.0,154.977470,163.422961,211.0,1.0,1.025751,1.0,993557.272464,1.362606,1.305949,1.267705,1.936261,1.788952,1.684136,1.923513,1.991501,1.961756,1.781870,1.964589,1.988669,1.992918,1.885269,1.954674,1.997167,1.997167,1.997167,1.899433,2.0,2.0,NaN,NaN,4.0,4.0,4.0,3.528846,3.863158,3.978261,3.957895,NaN,4.0,3.931818,1.988543,25.272727,253137.272727,2.615249e+06,83.0,3.046362e+07,1.473684,25.0,1.0,250400.0,155.285714,181.428571,1.949346,NaN,1.012821,1.036913,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.560734,NaN,4.012712,NaN
std,6.245415e+05,0.0,12.941393,0.0,0.747039,7493.937100,6.720386,1.890151e+06,65.438502,NaN,148.237250,0.865415,0.582572,1.077033,0.0,0.0,0.0,6.057982,245.262956,NaN,NaN,0.430793,0.0,68926.715481,0.481093,0.461135,0.443077,0.244461,0.408342,0.465189,0.265965,0.091860,0.191920,0.413269,0.184947,0.105919,0.083916,0.318923,0.208165,0.053187,0.053187,0.053187,0.300967,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.902604,0.538132,0.208514,0.288643,NaN,0.0,0.452267,0.535494,1.279204,12838.947139,1.599449e+06,0.0,1.937540e+07,0.841191,0.0,0.0,0.0,1.112697,212.095778,0.247507,NaN,0.113228,0.483662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.496648,NaN,0.195007,NaN
min,2.300000e+01,2.0,202301.000000,2023.0,24.000000,240810.000000,1342.000000,1.120000e+03,200627.000000,NaN,2001.000000,1.000000,1.000000,1.000000,25.0,250400.0,1421.0,15.000000,1.000000,211.0,1.0,1.000000,1.0,223710.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.0,2.0,NaN,NaN,4.0,4.0,4.0,1.000000,1.000000,2.000000,2.000000,NaN,4.0,1.000000,1.000000,25.000000,250400.000000,2.203370e+05,83.0,2.101550e+07,1.000000,25.0,1.0,250400.0,153.000000,3.000000,1.000000,NaN,1.000000,1.000000,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,4.000000,NaN
25%,7.897875e+04,2.0,202315.000000,2023.0,25.000000,250400.000000,1421.000000,7.052251e+06,202314.000000,NaN,4022.000000,5.000000,4.000000,6.000000,25.0,250400.0,1421.0,154.000000,9.250000,211.0,1.0,1.000000,1.0,999992.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.0,NaN,NaN,4.0,4.0,4.0,4.000000,4.000000,4.000000,4.000000,NaN,4.0,4.000000,2.000000,25.000000,250400.000000,2.362856e+06,83.0,2.101550e+07,1.000000,25.0,1.0,250400.0,155.000000,7.500000,2.000000,NaN,1.000000,1.000000,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,4.000000,NaN
50%,8.049550e+04,2.0,202322.000000,2023.0,25.000000,250400.000000,1421.000000,7.052251e+06,202322.000000,NaN,4030.000000,5.000000,4.000000,6.000000,25.0,250400.0,1421.0,155.000000,38.000000,211.0,1.0,1.000000,1.0,999992.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.0,NaN,NaN,4.0,4.0,4.0,4.000000,4.000000,4.000000,4.000000,NaN,4.0,4.000000,2.000000,25.000000,250400.000000,2.519565e+06,83.0,2.101557e+07,1.000000,25.0,1.0,250400.0,156.000000,28.000000,2.000000,NaN,1.000000,1.000000,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,4.000000,NaN
75%,8.125800e+04,2.0,202333.000000,2023.0,25.000000,250400.000000,1421.000000,7.052251e+06,202332.000000,NaN,4043.000000,6.000000,4.000000,6.000000,25.0,250400.0,1421.0,156.000000,260.000000,211.0,1.0,1.000000,1.0,999992.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.0,NaN,NaN,4.0,4.0,4.0,4.000000,4.000000,4.000000,4.000000,NaN,4.0,4.000000,2.000000,25.000000,250400.000000,2.676060e+06,83.0,3.310585e+07,1.500000,25.0,1.0,250400.0,156.000000,406.000000,2.000000,NaN,1.000000,1.000000,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,4.000000,NaN
max,8.666392e+06,2.0,202352.000000,2023.0,41.000000,410830.000000,1499.000000,9.601473e+06,202352.000000,NaN,4097.000000,9.000000,9.000000,10.000000,25.0,250400.0,1421.0,158.000000,817.000000,211.0,1.0,9.000000,1.0,999993.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.0,NaN,NaN,4.0,4.0,4.0,4.000000,4.000000,4.000000,4.000000,NaN,4.0,4.000000,9.000000,31.000000,310620.000000,9.068279e+06,83.0,9.964312e+07,3.000000,25.0,1.0,250400.0,156.000000,412.000000,3.000000,NaN,2.000000,9.000000,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,7.000000,NaN

In [250]:
df.isnull().sum()

NU_NOTIFIC,C,7       0
TP_NOT,C,1           0
ID_AGRAVO,C,5        0
DT_NOTIFIC,D         0
SEM_NOT,C,6          0
                  ...
NU_LOTE_H,C,7      708
CS_FLXRET,C,1        0
FLXRECEBI,C,7      708
IDENT_MICR,C,50      0
MIGRADO_W,C,1      708
Length: 146, dtype: int64

In [251]:
#corrigindo colunas para entender o que significam e ver distribuição de valores

df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace({
    1: 'BRANCO',
    2: 'PRETO',
    3: 'AMARELO',
    4: 'PARDO',
    5: 'INDIGENA',
    9: 'IGNORADO'
})

generos={
    'M': 'HOMEM',
    'F': 'MULHER'
}
df['CS_SEXO,C,1']=df['CS_SEXO,C,1'].replace(generos)



escolaridade={
    0: 'ANALFABETO',
    1: 'PRIMARIO INCOMPLETO',
    2: 'PRIMARIO COMPLETO',
    3: '1 GRAU INCOMPLETO',
    4: 'FUNDAMENTAL COMPLETO',
    5: 'ENSINO MÉDIO INCOMPLETO',
    6: 'ENSINO MÉDIO COMPLETO',
    7: 'SUPERIOR INCOMPLETO',
    8: 'SUPERIOR COMPLETO',
    9: 'IGNORADO',
    10: 'NÃO SE APLICA'
}
df['CS_ESCOL_N,C,2']=df['CS_ESCOL_N,C,2'].replace(escolaridade)

In [252]:
np.unique(df['CS_RACA,C,1'].astype(str),return_counts=True)

(array(['AMARELO', 'BRANCO', 'IGNORADO', 'PARDO'], dtype=object),
 array([  9,   9,   6, 684]))

In [253]:
np.unique(df['CS_SEXO,C,1'].astype(str), return_counts= True)

(array(['HOMEM', 'MULHER'], dtype=object), array([312, 396]))

In [254]:
#ajeitando parâmetros de data
df['DT_NOTIFIC,D'] = pd.to_datetime(df['DT_NOTIFIC,D'], format='%m/%d/%y')
df['MES DO CASO'] = df['DT_NOTIFIC,D'].dt.month

In [255]:
meses = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
df['MES DO CASO'] = df['MES DO CASO'].replace(meses)

In [256]:
df['MES DO CASO'].astype(str).value_counts()

MES DO CASO
Abril        138
Junho         96
Maio          76
Março         74
Agosto        57
Julho         55
Dezembro      44
Setembro      37
Outubro       35
Novembro      34
Janeiro       32
Fevereiro     30
Name: count, dtype: int64

In [257]:
#trazendo os meses para estações para entender a distribuição dos casos

estacoes_por_mes={
    'Dezembro' : 'VERAO',
    'Janeiro': 'VERAO',
    'Fevereiro': 'VERAO',
    'Março': 'VERAO',
    'Abril': 'OUTONO',
    'Maio': 'OUTONO',
    'Junho': 'OUTONO',
    'Julho': 'INVERNO',
    'Agosto': 'INVERNO',
    'Setembro': 'INVERNO',
    'Outubro': 'PRIMAVERA',
    'Novembro': 'PRIMAVERA'
}
df['ESTACAO POR CASO']=df['MES DO CASO'].replace(estacoes_por_mes)

In [258]:
df['ESTACAO POR CASO'].astype(str).value_counts()

ESTACAO POR CASO
OUTONO       310
VERAO        180
INVERNO      149
PRIMAVERA     69
Name: count, dtype: int64

In [259]:
df.rename(columns={
    'DT_NOTIFIC,D': 'DATA REGISTRO',
    'CS_SEXO,C,1': 'SEXO DO PACIENTE',
    'CS_RACA,C,1': 'RAÇA',
    'CS_ESCOL_N,C,2': 'GRAU ESCOLARIDADE',
    'NM_BAIRRO,C,60': 'BAIRRO',
    'CS_ZONA,C,1': 'ZONA',
    'ID_UNIDADE,C,7': 'UNIDADE DE ATENDIMENTO',
    'DT_NASC,D': 'DATA DE NASCIMENTO',
    'CLASSI_FIN,C,2': 'CLASS DOENCA',
    'SEM_PRI,C,6': 'SEMANA EPDM',
    'DT_SIN_PRI,D': 'DATA PRIMEIROS SINTOMAS',
    'SOROTIPO,C,1': 'SOROTIPO'
},inplace=True)

In [260]:
df['DATA DE NASCIMENTO'] = pd.to_datetime(df['DATA DE NASCIMENTO'], format='%m/%d/%y', errors='coerce')

# Correcting years that are in the future (e.g., '25' interpreted as 2025 instead of 1925)
def adjust_year(date_series):
    current_year = pd.Timestamp.now().year
    adjusted_dates = []
    for date in date_series:
        if pd.isna(date):
            adjusted_dates.append(pd.NaT)
            continue
        if date.year > current_year:
            adjusted_dates.append(date - pd.DateOffset(years=100))
        else:
            adjusted_dates.append(date)
    return pd.Series(adjusted_dates, index=date_series.index)

df['DATA DE NASCIMENTO'] = adjust_year(df['DATA DE NASCIMENTO'])

# Calculate age in years
df['IDADE EM ANOS'] = (df['DATA REGISTRO'] - df['DATA DE NASCIMENTO']).dt.days / 365.25

# Round the age to the nearest integer
df['IDADE EM ANOS'] = df['IDADE EM ANOS'].round().astype('Int64')

In [261]:
df_final2023 = df[['IDADE EM ANOS', 'SEXO DO PACIENTE','RAÇA','ESTACAO POR CASO','MES DO CASO','GRAU ESCOLARIDADE','BAIRRO','ZONA','UNIDADE DE ATENDIMENTO','DATA REGISTRO', 'CLASS DOENCA','SEMANA EPDM', 'DATA PRIMEIROS SINTOMAS','SOROTIPO']]

In [262]:
df_final2023

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
0,36,HOMEM,BRANCO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,PRESIDENTE MEDICE,1.0,2031779,2023-04-28,DENGUE,202317,04/23/23,NaN
1,63,MULHER,BRANCO,OUTONO,Maio,IGNORADO,ALTO BRANCO,1.0,2593904,2023-05-03,8,202317,04/29/23,NaN
2,39,HOMEM,IGNORADO,OUTONO,Abril,IGNORADO,SERROTAO,1.0,7408765,2023-04-11,8,202315,04/09/23,NaN
3,34,MULHER,IGNORADO,OUTONO,Abril,IGNORADO,BODOCONGO,9.0,9361936,2023-04-15,DENGUE,202315,04/10/23,NaN
4,20,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,MALVINAS,1.0,7052251,2023-01-02,DESCARTADO,202252,12/28/22,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,23,HOMEM,IGNORADO,VERAO,Janeiro,IGNORADO,CRUZEIRO,1.0,9601473,2023-01-05,DENGUE,202301,01/04/23,NaN
704,9,HOMEM,IGNORADO,VERAO,Fevereiro,NaN,CRUZEIRO,1.0,9601473,2023-02-06,DENGUE,202305,02/01/23,NaN
705,31,MULHER,PARDO,INVERNO,Setembro,IGNORADO,SANDRA CAVALCANTE,1.0,2399989,2023-09-12,DENGUE,202336,09/06/23,NaN
706,45,MULHER,IGNORADO,VERAO,Dezembro,IGNORADO,NaN,1.0,9601473,2023-12-14,DENGUE,202350,12/11/23,NaN
707,37,HOMEM,BRANCO,VERAO,Fevereiro,NaN,JOSE PINHEIRO,1.0,2592746,2023-02-15,DENGUE,202305,02/02/23,NaN

In [263]:
zonas={
    1: 'URBANA',
    2: 'RURAL',
    3: 'PERIURBANA'
}
df_final2023['ZONA']=df_final2023['ZONA'].replace(zonas)

/tmp/ipython-input-1497138181.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [264]:
np.unique(df['BAIRRO'].astype(str),return_counts=True)

(array(['A', 'ACACIO FIGUEIREDO', 'ALTO BRANCO', 'ALTO CAMPINA',
        'ALTO DA SERRA', 'ALUIZIO CAMPOS', 'ARAXA', 'BAIRRO DAS CIDADES',
        'BAIRRO DAS NACOES', 'BAIRRO UNIVERSITARIO', 'BELA VISTA',
        'BODOCONGO', 'BR 230', 'CASTELO BRANCO', 'CATOLE',
        'CATOLE ZE FERREIRA', 'CENTENARIO', 'CENTRO', 'CINZA', 'CONCEICAO',
        'CRUZEIRO', 'CUITES', 'DINAMERICA', 'ESTACAO VELHA', 'GALANTE',
        'GLORIA', 'ITARARE', 'JARDIM CONTINENTAL', 'JARDIM EUROPA',
        'JARDIM PAULISTANO', 'JARDIM QUARENTA', 'JARDIM TAVARES',
        'JENIPAPO', 'JEREMIAS', 'JOSE PINHEIRO', 'JURACI PALHANO',
        'LAURITZEN', 'LIBERDADE', 'LIGEIRO', 'LOUZEIRO', 'MALVINAS',
        'MALVINAS I', 'MARIA DA LUZ', 'MIRANTE', 'MONTE CASTELO',
        'MONTE SANTO', 'MUTIRAO', 'NOVA BRASILIA', 'NOVO BODOCONGO',
        'NOVO CRUZEIRO', 'PALMEIRA', 'PEDREGAL', 'PORTAL SUDOESTE',
        'PRATA', 'PRESIDENTE MEDICE', 'PRESIDENTE MEDICI', 'QUARENTA',
        'RAMADINHA', 'ROCHA CAVALCANTE', 'ROSA CRUZ', 'SANDRA CAVALCANTE',
        'SANTA CRUZ', 'SANTA ROSA', 'SANTA TEREZINHA', 'SANTO ANTONIO',
        'SAO JANUARIO', 'SAO JOSE', 'SAO JOSE DA MATA', 'SERROTAO',
        'SITIO CARACOL', 'SITIO HOTEL CRUZEIRO', 'SITIO SAMANBAIA',
        'SITIO SANTO ISIDIO', 'SITIO SANTO IZIDRIO', 'TAMBOR',
        'TRES IRMAES', 'TRES IRMAS', 'UNIVERSITARIO', 'VELAME',
        'VILA CABRAL', 'ZONA RURAL', 'nan'], dtype=object),
 array([ 1,  6, 51,  1,  1, 20, 15,  4,  5,  2,  5, 32,  1,  8, 30,  2,  4,
        31,  2, 14, 15, 13,  5, 12, 16,  2,  5,  8,  1,  9,  4,  8,  1, 32,
        29,  1,  1,  9,  4,  2, 27,  1,  1,  3, 13, 23,  1, 25,  2,  3, 23,
         7,  3,  2,  8,  1,  1,  9,  1,  2,  7,  2,  7,  8, 10,  2,  7, 17,
        18,  1,  1,  1,  1,  1,  4, 15,  2,  3,  5,  7,  5, 16]))

In [265]:
baairros={
    'A': 'ALTO BRANCO',
    'UNIVERSITARIO': 'BAIRRO UNIVERSITARIO',
    'TRES IRMAES': 'TRES IRMAS',
    'NOVO BODOCONGO': 'BODOCONGO',
    'JURACI PALHANO': 'JURACY PALHANO',
    'PRESIDENTE MEDICI': 'PRESIDENTE MEDICE',
    'SITIO SANTO ISIDIO': 'SITIO SANTO ISIDRIO',
    'SITIO SANTO IZIDRIO': 'SITIO SANTO ISIDRIO',
    'BAIRRO DAS NACOES': 'NACOES',
    'BR 230': 'ALTO BRANCO',
    'MALVINAS I': 'MALVINAS',
    'MARIA DA LUZ': 'PARQUE MARIA DA LUZ',
    'QUARENTA': 'JARDIM QUARENTA'
}

In [266]:
np.unique(df['UNIDADE DE ATENDIMENTO'],return_counts=True)

(array([   1120,  220337, 2031779, 2362287, 2362295, 2362856, 2362880,
        2363070, 2363275, 2399989, 2428369, 2592746, 2593904, 2595443,
        2613166, 2676060, 2792753, 2978296, 3006204, 7052251, 7113692,
        7408765, 9068279, 9361936, 9374833, 9601473]),
 array([  1,   3,   1,  26,  16,  14,  29,   8,   4,   1,   1,   1,   1,
          1,   1,  14,   1,   1,   1, 517,  41,   1,   1,   1,  19,   3]))

In [267]:
unidades={
    220337: "HOSPITAL DE CLINICAS DE CAMPINA GRANDE",
    2362287: "INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA",
    2362295: "SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE",
    2362856: "HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES",
    2362880: "HOSPITAL MUNICIPAL DR EDGLEY",
    2363070: "HOSPITAL MUNICIPAL PEDRO I",
    2363275: "VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE",
    2595443: "UBS HORACINA DE ALMEIDA",
    2676060: "HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO",
    2792753: "UBS ANTONIO VIRGILIO BRASILEIRO SILVA",
    2978296: "UBS JOSE BEZERRA PIMENTEL",
    7052251: "UPA 24 HORAS DR MAIA",
    7113692: "HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO",
    9374833: "UPA 24 HORAS DR ADHEMAR DANTAS"
}
df_final2023['UNIDADE DE ATENDIMENTO']=df['UNIDADE DE ATENDIMENTO'].replace(unidades)

/tmp/ipython-input-331774241.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [268]:

# 1. Dicionário Completo (Campina Grande + Externos identificados)
unidades = {
    # --- Campina Grande ---
    220337: "HOSPITAL DE CLINICAS DE CAMPINA GRANDE",
    2362287: "INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA",
    2362295: "SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE",
    2362856: "HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES",
    2362880: "HOSPITAL MUNICIPAL DR EDGLEY",
    2363070: "HOSPITAL MUNICIPAL PEDRO I",
    2363275: "VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE",
    2595443: "UBS HORACINA DE ALMEIDA",
    2676060: "HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO",
    2792753: "UBS ANTONIO VIRGILIO BRASILEIRO SILVA",
    2978296: "UBS JOSE BEZERRA PIMENTEL",
    3006204: "CLINICA SANTA CLARA",
    7052251: "UPA 24 HORAS DR MAIA (ALTO BRANCO)",
    7113692: "HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO",
    9374833: "UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA)",

    # --- Externos / Outras Cidades ---
    2031779: "UPA 24H ANTONIO BARADEL (SP)",
    2399989: "HOSPITAL GERAL DA PARAIBA (JOÃO PESSOA)",
    2428369: "CASA DE SAUDE SANTA EFIGENIA (PE)",
    2592746: "HOSP MATERNIDADE FLAVIO RIBEIRO COUTINHO (SANTA RITA)",
    2593904: "UPA 24H DR WALTER CAVALCANTI BARBOSA (PR)",
    2613166: "UBSF ZUMBI (PATOS-PB)",
    7408765: "UPA 24H ESPERANCA (RN)",
    9068279: "UPA NOROESTE II (MG)",
    9361936: "UPA 24HS CIDADE SATELITE (RN)",
    9601473: "UPA BANCARIOS (JOÃO PESSOA)",

    # --- Erros ---
    1120: "CODIGO INVALIDO (ERRO DE REGISTRO)"
}

# 2. Lista apenas com os IDs de Campina Grande para filtragem
ids_campina_grande = [
    220337, 2362287, 2362295, 2362856, 2362880, 2363070, 2363275,
    2595443, 2676060, 2792753, 2978296, 3006204, 7052251, 7113692, 9374833
]

# --- APLICAÇÃO NO DATAFRAME ---

# Certifique-se de que a coluna é numérica para bater com as chaves do dicionário
# (Se a coluna no Excel estiver como texto, remova o comentário da linha abaixo)
# df_final2023['UNIDADE DE ATENDIMENTO'] = pd.to_numeric(df_final2023['UNIDADE DE ATENDIMENTO'], errors='coerce')

# Cria a coluna de Classificação (Interno/Externo) ANTES de substituir o ID pelo nome
# Se o ID estiver na lista de Campina, é "Campina Grande", senão é "Externo/Outro"
df_final2023['ORIGEM_UNIDADE'] = np.where(
    df_final2023['UNIDADE DE ATENDIMENTO'].isin(ids_campina_grande),
    'Campina Grande',
    'Externo/Outro'
)

# Substitui os códigos pelos nomes conforme solicitado
df_final2023['UNIDADE DE ATENDIMENTO'] = df_final2023['UNIDADE DE ATENDIMENTO'].replace(unidades)

# Visualizar o resultado

/tmp/ipython-input-3339197991.py:50: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipython-input-3339197991.py:57: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [269]:
df_final2023

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,36,HOMEM,BRANCO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,PRESIDENTE MEDICE,URBANA,UPA 24H ANTONIO BARADEL (SP),2023-04-28,DENGUE,202317,04/23/23,NaN,Externo/Outro
1,63,MULHER,BRANCO,OUTONO,Maio,IGNORADO,ALTO BRANCO,URBANA,UPA 24H DR WALTER CAVALCANTI BARBOSA (PR),2023-05-03,8,202317,04/29/23,NaN,Externo/Outro
2,39,HOMEM,IGNORADO,OUTONO,Abril,IGNORADO,SERROTAO,URBANA,UPA 24H ESPERANCA (RN),2023-04-11,8,202315,04/09/23,NaN,Externo/Outro
3,34,MULHER,IGNORADO,OUTONO,Abril,IGNORADO,BODOCONGO,9.0,UPA 24HS CIDADE SATELITE (RN),2023-04-15,DENGUE,202315,04/10/23,NaN,Externo/Outro
4,20,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,UPA 24 HORAS DR MAIA,2023-01-02,DESCARTADO,202252,12/28/22,NaN,Externo/Outro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,23,HOMEM,IGNORADO,VERAO,Janeiro,IGNORADO,CRUZEIRO,URBANA,UPA BANCARIOS (JOÃO PESSOA),2023-01-05,DENGUE,202301,01/04/23,NaN,Externo/Outro
704,9,HOMEM,IGNORADO,VERAO,Fevereiro,NaN,CRUZEIRO,URBANA,UPA BANCARIOS (JOÃO PESSOA),2023-02-06,DENGUE,202305,02/01/23,NaN,Externo/Outro
705,31,MULHER,PARDO,INVERNO,Setembro,IGNORADO,SANDRA CAVALCANTE,URBANA,HOSPITAL GERAL DA PARAIBA (JOÃO PESSOA),2023-09-12,DENGUE,202336,09/06/23,NaN,Externo/Outro
706,45,MULHER,IGNORADO,VERAO,Dezembro,IGNORADO,NaN,URBANA,UPA BANCARIOS (JOÃO PESSOA),2023-12-14,DENGUE,202350,12/11/23,NaN,Externo/Outro
707,37,HOMEM,BRANCO,VERAO,Fevereiro,NaN,JOSE PINHEIRO,URBANA,HOSP MATERNIDADE FLAVIO RIBEIRO COUTINHO (SANT...,2023-02-15,DENGUE,202305,02/02/23,NaN,Externo/Outro

In [270]:
df_final2023 = df_final2023[df_final2023['CLASS DOENCA'] != 'DESCARTADO']
df_final2023 = df_final2023[df_final2023['CLASS DOENCA'] != 'CHIKUNGUNYA']
df_final2023 = df_final2023[df_final2023['CLASS DOENCA'] != '8']

In [271]:
df_final2023['UNIDADE DE ATENDIMENTO'].value_counts()

UNIDADE DE ATENDIMENTO
UPA 24 HORAS DR MAIA                                          71
HOSPITAL MUNICIPAL DR EDGLEY                                  11
INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA                     6
HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO             5
HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO                        4
HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES     3
UPA BANCARIOS (JOÃO PESSOA)                                    3
HOSPITAL MUNICIPAL PEDRO I                                     2
SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE                1
UPA 24H DR WALTER CAVALCANTI BARBOSA (PR)                      1
UPA 24H ESPERANCA (RN)                                         1
UPA 24HS CIDADE SATELITE (RN)                                  1
UPA 24H ANTONIO BARADEL (SP)                                   1
VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE                    1
HOSPITAL GERAL DA PARAIBA (JOÃO PESSOA)                        1
HOSP MATERNIDADE FLAVIO RIBEIRO COUTINHO (SANTA RITA)          1
Name: count, dtype: int64

In [272]:
df_final2023['BAIRRO'].value_counts()

BAIRRO
CENTRO                8
JOSE PINHEIRO         8
ALTO BRANCO           7
MALVINAS              6
JEREMIAS              5
CONCEICAO             5
BODOCONGO             5
MONTE SANTO           5
CRUZEIRO              4
VILA CABRAL           4
NOVA BRASILIA         4
CUITES                4
CATOLE                3
TRES IRMAES           3
JARDIM CONTINENTAL    3
PRESIDENTE MEDICE     2
BAIRRO DAS CIDADES    2
GLORIA                2
NOVO BODOCONGO        2
ALUIZIO CAMPOS        2
ARAXA                 2
PALMEIRA              2
ESTACAO VELHA         2
PEDREGAL              2
VELAME                1
DINAMERICA            1
SERROTAO              1
MONTE CASTELO         1
SANTO ANTONIO         1
JARDIM TAVARES        1
CASTELO BRANCO        1
RAMADINHA             1
JARDIM QUARENTA       1
NOVO CRUZEIRO         1
UNIVERSITARIO         1
CATOLE ZE FERREIRA    1
ACACIO FIGUEIREDO     1
JARDIM PAULISTANO     1
MARIA DA LUZ          1
SAO JOSE              1
CENTENARIO            1
TRES IRMAS            1
SANDRA CAVALCANTE     1
Name: count, dtype: int64

In [273]:
# Calculate the frequency of each neighborhood
neighborhood_frequency = df_final2023['BAIRRO'].value_counts().reset_index()
neighborhood_frequency.columns = ['Bairro', 'Frequência']

# Sort the DataFrame by frequency in descending order
neighborhood_frequency = neighborhood_frequency.sort_values(by='Frequência', ascending=False)

# Get the top N neighborhoods for better visualization (optional, adjust N as needed)
# For now, let's display all, but if there are too many, we might limit it.
# neighborhood_frequency_top = neighborhood_frequency.head(20)

# Create the bar chart
fig = plx.bar(
    neighborhood_frequency,
    x='Bairro',
    y='Frequência',
    title='Frequência de Casos por Bairro',
    labels={'Bairro': 'Bairro', 'Frequência': 'Número de Casos'},
    color_discrete_sequence=plx.colors.qualitative.Pastel
)

fig.update_layout(
    xaxis_title='Bairro',
    yaxis_title='Número de Casos',
    xaxis_tickangle=-45 # Rotate x-axis labels for better readability
)

fig.show()

In [274]:
df_final2023['SEXO DO PACIENTE'].value_counts()

SEXO DO PACIENTE
MULHER    60
HOMEM     53
Name: count, dtype: int64

In [275]:
df_final2023['ESTACAO POR CASO'].value_counts()

ESTACAO POR CASO
OUTONO       82
VERAO        15
INVERNO      14
PRIMAVERA     2
Name: count, dtype: int64

In [276]:
df_final2023['ZONA'].value_counts()

ZONA
URBANA    110
9.0         2
Name: count, dtype: int64

In [277]:
df_final2023['RAÇA'].replace('IGNORADO','PARDO',inplace=True)
df_final2023['RAÇA'].value_counts()

/tmp/ipython-input-2101784120.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

RAÇA
PARDO     109
BRANCO      4
Name: count, dtype: int64

In [278]:
df_final2023['GRAU ESCOLARIDADE'].replace('IGNORADO','ENSINO MÉDIO COMPLETO',inplace=True)

df_final2023['GRAU ESCOLARIDADE'].value_counts()

/tmp/ipython-input-1441659012.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

GRAU ESCOLARIDADE
ENSINO MÉDIO COMPLETO      99
NÃO SE APLICA               5
ENSINO MÉDIO INCOMPLETO     1
SUPERIOR COMPLETO           1
1 GRAU INCOMPLETO           1
PRIMARIO INCOMPLETO         1
Name: count, dtype: int64

In [279]:
df_final2023['IDADE EM ANOS'].value_counts()

IDADE EM ANOS
22    10
39     6
45     5
34     4
26     4
28     4
33     4
42     4
43     4
31     3
35     3
27     3
20     3
30     3
46     3
9      3
25     3
41     2
36     2
44     2
32     2
60     2
54     2
29     2
24     2
52     2
37     2
63     1
50     1
38     1
62     1
6      1
7      1
4      1
8      1
51     1
-3     1
76     1
57     1
40     1
17     1
11     1
15     1
21     1
53     1
5      1
18     1
48     1
0      1
19     1
23     1
Name: count, dtype: Int64

In [280]:
df_final2023['DATA REGISTRO'] = df_final2023['DATA REGISTRO'].dt.year

In [281]:
df_final2023['SEMANA EPDM'] = df_final2023['SEMANA EPDM'].astype(str).str[-2:]

In [282]:
df_final2023['BAIRRO'].fillna('CENTRO',inplace=True)
np.unique(df_final2023['BAIRRO'].astype(str),return_counts=True)

/tmp/ipython-input-990864343.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

(array(['ACACIO FIGUEIREDO', 'ALTO BRANCO', 'ALUIZIO CAMPOS', 'ARAXA',
        'BAIRRO DAS CIDADES', 'BODOCONGO', 'CASTELO BRANCO', 'CATOLE',
        'CATOLE ZE FERREIRA', 'CENTENARIO', 'CENTRO', 'CONCEICAO',
        'CRUZEIRO', 'CUITES', 'DINAMERICA', 'ESTACAO VELHA', 'GLORIA',
        'JARDIM CONTINENTAL', 'JARDIM PAULISTANO', 'JARDIM QUARENTA',
        'JARDIM TAVARES', 'JEREMIAS', 'JOSE PINHEIRO', 'MALVINAS',
        'MARIA DA LUZ', 'MONTE CASTELO', 'MONTE SANTO', 'NOVA BRASILIA',
        'NOVO BODOCONGO', 'NOVO CRUZEIRO', 'PALMEIRA', 'PEDREGAL',
        'PRESIDENTE MEDICE', 'RAMADINHA', 'SANDRA CAVALCANTE',
        'SANTO ANTONIO', 'SAO JOSE', 'SERROTAO', 'TRES IRMAES',
        'TRES IRMAS', 'UNIVERSITARIO', 'VELAME', 'VILA CABRAL'],
       dtype=object),
 array([ 1,  7,  2,  2,  2,  5,  1,  3,  1,  1, 10,  5,  4,  4,  1,  2,  2,
         3,  1,  1,  1,  5,  8,  6,  1,  1,  5,  4,  2,  1,  2,  2,  2,  1,
         1,  1,  1,  1,  3,  1,  1,  1,  4]))

In [283]:
df_final2023['GRAU ESCOLARIDADE'].fillna('ENSINO MÉDIO COMPLETO',inplace=True)

/tmp/ipython-input-3981993775.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [284]:
np.unique(df_final2023['CLASS DOENCA'].astype(str),return_counts=True)

(array(['8', 'DENGUE'], dtype=object), array([96, 17]))

In [285]:
df_final2023.head()

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,36,HOMEM,BRANCO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,PRESIDENTE MEDICE,URBANA,UPA 24H ANTONIO BARADEL (SP),2023,DENGUE,17,04/23/23,NaN,Externo/Outro
1,63,MULHER,BRANCO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,ALTO BRANCO,URBANA,UPA 24H DR WALTER CAVALCANTI BARBOSA (PR),2023,8,17,04/29/23,NaN,Externo/Outro
2,39,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,SERROTAO,URBANA,UPA 24H ESPERANCA (RN),2023,8,15,04/09/23,NaN,Externo/Outro
3,34,MULHER,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,BODOCONGO,9.0,UPA 24HS CIDADE SATELITE (RN),2023,DENGUE,15,04/10/23,NaN,Externo/Outro
20,62,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,CONCEICAO,URBANA,UPA 24 HORAS DR MAIA,2023,8,02,01/12/23,NaN,Externo/Outro

In [286]:
df_final2023 = df_final2023[df_final2023['CLASS DOENCA'].astype(str) != '8']
np.unique(df_final2023['CLASS DOENCA'].astype(str),return_counts=True)

(array(['DENGUE'], dtype=object), array([17]))

In [287]:
df_final2023.shape

(17, 15)

In [288]:
df_final2023['ZONA'].replace(9.0,'URBANA',inplace=True)

/tmp/ipython-input-247572789.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [289]:
df_final2023.to_csv('dengue2023_tratado.csv',index=False)