In [1]:
import pandas as pd
import numpy as np
import plotly.express as plx
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df= pd.read_csv('/content/drive/MyDrive/Pivic/dados/Dados/epidemiologia dengue cg/AnyConv.com__2025_SI_DENGON2642310_00.csv')
pd.set_option('display.max_columns', None)
df.head()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","ID_AGRAVO,C,5","DT_NOTIFIC,D","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","DT_SIN_PRI,D","SEM_PRI,C,6","DT_NASC,D","SOUNDEX,C,70","NU_IDADE_N,N,4,0","CS_SEXO,C,1","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_DISTRIT,C,9","ID_BAIRRO,C,8","NM_BAIRRO,C,60","ID_GEO1,C,8","ID_GEO2,C,8","CS_ZONA,C,1","ID_PAIS,C,4","DT_INVEST,D","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","DT_CHIK_S2,D","DT_PRNT,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_PRNT,C,1","DT_SORO,D","RESUL_SORO,C,1","DT_NS1,D","RESUL_NS1,C,1","DT_VIRAL,D","RESUL_VI_N,C,1","DT_PCR,D","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","DT_INTERNA,D","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CODISINF,C,4","CO_BAINF,C,8","NOBAIINF,C,60","CLASSI_FIN,C,2","CRITERIO,C,1","DOENCA_TRA,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","DT_OBITO,D","DT_ENCERRA,D","ALRM_HIPOT,C,1","ALRM_PLAQ,C,1","ALRM_VOM,C,1","ALRM_SANG,C,1","ALRM_HEMAT,C,1","ALRM_ABDOM,C,1","ALRM_LETAR,C,1","ALRM_HEPAT,C,1","ALRM_LIQ,C,1","DT_ALRM,D","GRAV_PULSO,C,1","GRAV_CONV,C,1","GRAV_ENCH,C,1","GRAV_INSUF,C,1","GRAV_TAQUI,C,1","GRAV_EXTRE,C,1","GRAV_HIPOT,C,1","GRAV_HEMAT,C,1","GRAV_MELEN,C,1","GRAV_METRO,C,1","GRAV_SANG,C,1","GRAV_AST,C,1","GRAV_MIOC,C,1","GRAV_CONSC,C,1","GRAV_ORGAO,C,1","DT_GRAV,D","MANI_HEMOR,C,1","EPISTAXE,C,1","GENGIVO,C,1","METRO,C,1","PETEQUIAS,C,1","HEMATURA,C,1","SANGRAM,C,1","LACO_N,C,1","PLASMATICO,C,1","EVIDENCIA,C,1","PLAQ_MENOR,C,7","CON_FHD,C,1","COMPLICA,C,1","NU_LOTE_I,C,9","DS_OBS,C,255","TP_SISTEMA,C,1","NDUPLIC_N,C,1","DT_DIGITA,D","DT_TRANSUS,D","DT_TRANSDM,D","DT_TRANSSM,D","DT_TRANSRM,D","DT_TRANSRS,D","DT_TRANSSE,D","NU_LOTE_V,C,7","NU_LOTE_H,C,7","CS_FLXRET,C,1","FLXRECEBI,C,7","IDENT_MICR,C,50","MIGRADO_W,C,1"
0,6902153,2,A90,02/21/25,202508,2025,41,410690,1356,2639548,02/18/25,202508,06/05/85,NaN,4039,M,6,4,9.0,25,250400,1421,NaN,606.0,TRES IRMAS,NaN,NaN,NaN,1,02/21/25,998999.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2.0,NaN,NaN,1.0,NaN,04/23/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PACIENTE REFERE SENSAÃ├O FEBRIL, MIALGIA, ARD╩...",2.0,NaN,02/23/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN
1,93151,2,A90,09/14/25,202538,2025,25,250400,1421,9374833,09/13/25,202537,09/15/81,NaN,4043,M,6,4,6.0,25,250400,1421,NaN,603.0,MALVINAS,NaN,NaN,1.0,1,09/14/25,NaN,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,1.0,NaN,09/23/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,09/23/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN
2,93227,2,A90,09/23/25,202539,2025,25,250400,1421,9374833,09/22/25,202539,12/08/93,NaN,4031,F,9,4,6.0,25,250400,1421,NaN,5.0,BODOCONGO,NaN,NaN,1.0,1,09/23/25,NaN,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,NaN,NaN,1.0,NaN,09/30/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,09/30/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN
3,93254,2,A90,09/11/25,202537,2025,25,250400,1421,9352902,09/06/25,202536,07/26/05,NaN,4020,F,5,4,6.0,25,250400,1421,NaN,606.0,TRES IRMAS,NaN,NaN,1.0,1,09/11/25,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,NaN,NaN,1.0,NaN,09/30/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,09/30/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN
4,93193,2,A90,09/26/25,202539,2025,25,250400,1421,7052251,09/24/25,202539,05/01/99,NaN,4026,M,6,4,6.0,25,250400,1421,NaN,3.0,ALTO BRANCO,NaN,NaN,1.0,1,09/26/25,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09/26/25,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,1.0,NaN,09/30/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,09/29/25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Columns: 146 entries, NU_NOTIFIC,C,7 to MIGRADO_W,C,1
dtypes: float64(111), int64(17), object(18)
memory usage: 3.4+ MB

In [ ]:
df['CLASSI_FIN,C,2']

0       10.0
1        5.0
2        5.0
3        5.0
4        5.0
        ...
3045     8.0
3046    10.0
3047    10.0
3048     5.0
3049     8.0
Name: CLASSI_FIN,C,2, Length: 3050, dtype: float64

In [ ]:
df['SEM_PRI,C,6']

0       202508
1       202537
2       202539
3       202536
4       202539
         ...
3045    202513
3046    202504
3047    202520
3048    202516
3049    202530
Name: SEM_PRI,C,6, Length: 3050, dtype: int64

In [ ]:
df['DT_SIN_PRI,D']

0       02/18/25
1       09/13/25
2       09/22/25
3       09/06/25
4       09/24/25
          ...
3045    03/26/25
3046    01/23/25
3047    05/13/25
3048    04/13/25
3049    07/21/25
Name: DT_SIN_PRI,D, Length: 3050, dtype: object

In [ ]:
classificacao={
    5: 'DESCARTADO',
    10: 'DENGUE',
    11: 'DENGUE C/ ALARME',
    12: 'DENGUE GRAVE',
    13: 'CHIKUNGUNYA'
}
df['CLASSI_FIN,C,2']=df['CLASSI_FIN,C,2'].replace(classificacao)

In [ ]:
df['CLASSI_FIN,C,2'].value_counts()

CLASSI_FIN,C,2
DESCARTADO    2830
DENGUE         209
8.0              4
Name: count, dtype: int64

In [ ]:
df['DT_SIN_PRI,D']

0       02/18/25
1       09/13/25
2       09/22/25
3       09/06/25
4       09/24/25
          ...
3045    03/26/25
3046    01/23/25
3047    05/13/25
3048    04/13/25
3049    07/21/25
Name: DT_SIN_PRI,D, Length: 3050, dtype: object

In [ ]:
df.shape

(3050, 146)

In [ ]:
df=df.dropna(axis=1, how='all')

In [ ]:
df.shape

(3050, 86)

In [ ]:
df.describe()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","SEM_PRI,C,6","NU_IDADE_N,N,4,0","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_BAIRRO,C,8","CS_ZONA,C,1","ID_PAIS,C,4","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_SORO,C,1","RESUL_NS1,C,1","RESUL_VI_N,C,1","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CO_BAINF,C,8","CRITERIO,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","TP_SISTEMA,C,1","CS_FLXRET,C,1","IDENT_MICR,C,50"
count,3.050000e+03,3050.0,3050.000000,3050.0,3050.000000,3050.000000,3050.000000,3.050000e+03,3050.000000,3050.000000,3050.000000,3050.000000,3030.000000,3050.0,3050.0,3050.0,2999.000000,3020.000000,3050.0,14.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.000000,3049.0,3049.000000,3049.000000,3049.000000,3049.000000,3.0,1.0,365.000000,94.000000,93.000000,2451.000000,96.000000,110.000000,115.000000,209.000000,30.0,29.0,2.700000e+01,21.0,2.100000e+01,88.000000,82.0,82.0,81.0,1.0,3039.000000,48.0,3036.000000,2945.0,3050.000000,2921.000000
mean,1.151894e+05,2.0,202521.706557,2025.0,25.025902,250663.478033,1421.438689,6.979965e+06,202520.527541,4027.456066,5.665246,4.010492,6.016172,25.0,250400.0,1421.0,268.183394,1.017881,1.0,834781.357143,1.239423,1.285667,1.261725,1.920958,1.766809,1.710397,1.920302,1.990489,1.963595,1.721876,1.960643,1.985569,1.996720,1.791735,1.975402,1.999016,2.0,1.999016,1.944900,1.999344,1.997048,2.0,1.0,2.095890,3.829787,3.935484,2.016728,1.708333,3.963636,3.947826,1.870813,25.0,250400.0,2.820389e+06,83.0,2.759680e+07,1.125000,25.0,1.0,250400.0,21.0,1.105627,1.0,1.000988,2.0,0.068852,4.004108
std,3.562710e+05,0.0,13.207633,0.0,0.760399,7639.194316,10.335263,2.957703e+06,43.921432,96.998924,1.118909,0.390803,0.826718,0.0,0.0,0.0,278.857365,0.132540,0.0,330022.927820,0.426801,0.451806,0.439646,0.269849,0.422932,0.453653,0.270870,0.097077,0.187327,0.448148,0.194475,0.119279,0.057185,0.406134,0.154923,0.031357,0.0,0.031357,0.228213,0.025607,0.054259,0.0,NaN,0.957394,0.598175,0.323246,0.385616,0.560388,0.268440,0.320183,0.618279,0.0,0.0,1.321437e+06,0.0,1.712777e+07,0.450096,0.0,0.0,0.0,NaN,0.308479,0.0,0.040577,0.0,0.253245,0.110959
min,2.100000e+01,2.0,202501.000000,2025.0,23.000000,230440.000000,1356.000000,1.120000e+03,200211.000000,2001.000000,1.000000,1.000000,1.000000,25.0,250400.0,1421.0,1.000000,1.000000,1.0,142105.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.0,1.000000,1.000000,1.000000,1.000000,2.0,1.0,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,25.0,250400.0,2.362856e+06,83.0,2.101550e+07,1.000000,25.0,1.0,250400.0,21.0,1.000000,1.0,1.000000,2.0,0.000000,4.000000
25%,9.118750e+04,2.0,202510.000000,2025.0,25.000000,250400.000000,1421.000000,2.606475e+06,202509.000000,4023.000000,5.000000,4.000000,6.000000,25.0,250400.0,1421.0,22.000000,1.000000,1.0,999247.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.000000,2.000000,2.000000,2.000000,2.0,1.0,1.000000,4.000000,4.000000,2.000000,1.000000,4.000000,4.000000,2.000000,25.0,250400.0,2.362856e+06,83.0,2.101550e+07,1.000000,25.0,1.0,250400.0,21.0,1.000000,1.0,1.000000,2.0,0.000000,4.000000
50%,9.199150e+04,2.0,202519.000000,2025.0,25.000000,250400.000000,1421.000000,9.374833e+06,202519.000000,4030.000000,6.000000,4.000000,6.000000,25.0,250400.0,1421.0,51.000000,1.000000,1.0,999992.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.000000,2.000000,2.000000,2.000000,2.0,1.0,2.000000,4.000000,4.000000,2.000000,2.000000,4.000000,4.000000,2.000000,25.0,250400.0,2.676060e+06,83.0,2.101550e+07,1.000000,25.0,1.0,250400.0,21.0,1.000000,1.0,1.000000,2.0,0.000000,4.000000
75%,9.283775e+04,2.0,202534.000000,2025.0,25.000000,250400.000000,1421.000000,9.374833e+06,202534.000000,4042.000000,6.000000,4.000000,6.000000,25.0,250400.0,1421.0,603.000000,1.000000,1.0,999992.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.000000,2.000000,2.000000,2.000000,2.0,1.0,2.000000,4.000000,4.000000,2.000000,2.000000,4.000000,4.000000,2.000000,25.0,250400.0,2.676060e+06,83.0,3.310585e+07,1.000000,25.0,1.0,250400.0,21.0,1.000000,1.0,1.000000,2.0,0.000000,4.000000
max,7.040821e+06,2.0,202549.000000,2025.0,52.000000,521973.000000,1779.000000,9.387927e+06,202548.000000,4098.000000,9.000000,9.000000,10.000000,25.0,250400.0,1421.0,818.000000,2.000000,1.0,999993.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.0,2.000000,2.000000,2.000000,2.000000,2.0,1.0,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,4.000000,9.000000,25.0,250400.0,9.374833e+06,83.0,9.877095e+07,3.000000,25.0,1.0,250400.0,21.0,3.000000,1.0,3.000000,2.0,1.000000,7.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 86 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NU_NOTIFIC,C,7    3050 non-null   int64
 1   TP_NOT,C,1        3050 non-null   int64
 2   ID_AGRAVO,C,5     3050 non-null   object
 3   DT_NOTIFIC,D      3050 non-null   object
 4   SEM_NOT,C,6       3050 non-null   int64
 5   NU_ANO,C,4        3050 non-null   int64
 6   SG_UF_NOT,C,2     3050 non-null   int64
 7   ID_MUNICIP,C,6    3050 non-null   int64
 8   ID_REGIONA,C,8    3050 non-null   int64
 9   ID_UNIDADE,C,7    3050 non-null   int64
 10  DT_SIN_PRI,D      3050 non-null   object
 11  SEM_PRI,C,6       3050 non-null   int64
 12  DT_NASC,D         3050 non-null   object
 13  NU_IDADE_N,N,4,0  3050 non-null   int64
 14  CS_SEXO,C,1       3050 non-null   object
 15  CS_GESTANT,C,1    3050 non-null   int64
 16  CS_RACA,C,1       3050 non-null   int64
 17  CS_ESCOL_N,C,2    3030 non-null   float64
 18  SG_UF,C,2         3050 non-null   int64
 19  ID_MN_RESI,C,6    3050 non-null   int64
 20  ID_RG_RESI,C,8    3050 non-null   int64
 21  ID_BAIRRO,C,8     2999 non-null   float64
 22  NM_BAIRRO,C,60    3014 non-null   object
 23  CS_ZONA,C,1       3020 non-null   float64
 24  ID_PAIS,C,4       3050 non-null   int64
 25  DT_INVEST,D       3049 non-null   object
 26  ID_OCUPA_N,C,6    14 non-null     float64
 27  FEBRE,C,1         3049 non-null   float64
 28  MIALGIA,C,1       3049 non-null   float64
 29  CEFALEIA,C,1      3049 non-null   float64
 30  EXANTEMA,C,1      3049 non-null   float64
 31  VOMITO,C,1        3049 non-null   float64
 32  NAUSEA,C,1        3049 non-null   float64
 33  DOR_COSTAS,C,1    3049 non-null   float64
 34  CONJUNTVIT,C,1    3049 non-null   float64
 35  ARTRITE,C,1       3049 non-null   float64
 36  ARTRALGIA,C,1     3049 non-null   float64
 37  PETEQUIA_N,C,1    3049 non-null   float64
 38  LEUCOPENIA,C,1    3049 non-null   float64
 39  LACO,C,1          3049 non-null   float64
 40  DOR_RETRO,C,1     3049 non-null   float64
 41  DIABETES,C,1      3049 non-null   float64
 42  HEMATOLOG,C,1     3049 non-null   float64
 43  HEPATOPAT,C,1     3049 non-null   float64
 44  RENAL,C,1         3049 non-null   float64
 45  HIPERTENSA,C,1    3049 non-null   float64
 46  ACIDO_PEPT,C,1    3049 non-null   float64
 47  AUTO_IMUNE,C,1    3049 non-null   float64
 48  DT_CHIK_S1,D      4 non-null      object
 49  RES_CHIKS1,C,1    3 non-null      float64
 50  RES_CHIKS2,C,1    1 non-null      float64
 51  DT_SORO,D         311 non-null    object
 52  RESUL_SORO,C,1    365 non-null    float64
 53  DT_NS1,D          4 non-null      object
 54  RESUL_NS1,C,1     94 non-null     float64
 55  DT_VIRAL,D        3 non-null      object
 56  RESUL_VI_N,C,1    93 non-null     float64
 57  DT_PCR,D          2391 non-null   object
 58  RESUL_PCR_,C,1    2451 non-null   float64
 59  SOROTIPO,C,1      96 non-null     float64
 60  HISTOPA_N,C,1     110 non-null    float64
 61  IMUNOH_N,C,1      115 non-null    float64
 62  HOSPITALIZ,C,1    209 non-null    float64
 63  DT_INTERNA,D      28 non-null     object
 64  UF,C,2            30 non-null     float64
 65  MUNICIPIO,C,6     29 non-null     float64
 66  HOSPITAL,C,7      27 non-null     float64
 67  DDD_HOSP,C,2      21 non-null     float64
 68  TEL_HOSP,C,9      21 non-null     float64
 69  TPAUTOCTO,C,1     88 non-null     float64
 70  COUFINF,C,2       82 non-null     float64
 71  COPAISINF,C,4     82 non-null     float64
 72  COMUNINF,C,6      81 non-null     float64
 73  CO_BAINF,C,8      1 non-null      float64
 74  NOBAIINF,C,60     1 non-null      object
 75  CLASSI_FIN,C,2    3043 non-null   object
 76  CRITERIO,C,1      3039 non-null   float64
 77  CLINC_CHIK,C,1    48 non-null     float64
 78  EVOLUCAO,C,1      3036 non-null   float64
 79  DT_OBITO,D        2 non-null      object
 80  DT_ENCERRA,D      3042 non-null   object
 81  DS_OBS,C,255      18 non-null     object
 82  TP_SISTEMA,C,1    2945 non-null   float64
 83  DT_DIGITA,D       3049 non-null   object
 84  CS_FLXRET,C,1     3050 non-null   int64
 85  IDENT_MICR,C,50   2921 non-null   float64
dtypes: float64(50), int64(17), object(19)
memory usage: 2.0+ MB

**TRATANDO ALGUMAS INFORMAÇÕES NAS COLUNAS:**

Algumas infomrações estão com encodificações, então visando facilitar abordagens e o entendimento, estou "traduzindo" alguns valores

In [ ]:
df.isnull().sum()

NU_NOTIFIC,C,7        0
TP_NOT,C,1            0
ID_AGRAVO,C,5         0
DT_NOTIFIC,D          0
SEM_NOT,C,6           0
                   ...
DS_OBS,C,255       3032
TP_SISTEMA,C,1      105
DT_DIGITA,D           1
CS_FLXRET,C,1         0
IDENT_MICR,C,50     129
Length: 86, dtype: int64

In [ ]:
#Corrigindo as codificações de raça

df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace({
    1: 'BRANCO',
    2: 'PRETO',
    3: 'AMARELO',
    4: 'PARDO',
    5: 'INDIGENA',
    9: 'IGNORADO'
})

In [ ]:
#Organizando a coluna de gêneros

generos={
    'M': 'HOMEM',
    'F': 'MULHER'
}
df['CS_SEXO,C,1']=df['CS_SEXO,C,1'].replace(generos)

In [ ]:
#Tratando codificação de zonas

zonas={
    1: 'URBANA',
    2: 'RURAL',
    3: 'PERIURBANA',
    9: 'IGNORADO'
}
df['CS_ZONA,C,1']=df['CS_ZONA,C,1'].replace(zonas)

In [ ]:
#Tratando codificação de sorotipos circulantes

sorotipos={
    1:'DENV 1',
    2: 'DENV 2',
    3: 'DENV 3',
    4: 'DENV 4'
}
df['SOROTIPO,C,1']=df['SOROTIPO,C,1'].replace(sorotipos)

**-----------------------------FIM DO TRATAMENTO DE COLUNAS--------------------------**

In [ ]:
np.unique(df['CS_SEXO,C,1'].astype(str), return_counts= True)

(array(['HOMEM', 'MULHER'], dtype=object), array([1382, 1668]))

In [ ]:
df['DT_NOTIFIC,D'] = pd.to_datetime(df['DT_NOTIFIC,D'], format='%m/%d/%y')
df['MES DO CASO'] = df['DT_NOTIFIC,D'].dt.month

In [ ]:
#Organizando os meses de incidencia

meses = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
df['MES DO CASO'] = df['MES DO CASO'].replace(meses)

In [ ]:
df

,"NU_NOTIFIC,C,7","TP_NOT,C,1","ID_AGRAVO,C,5","DT_NOTIFIC,D","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","DT_SIN_PRI,D","SEM_PRI,C,6","DT_NASC,D","NU_IDADE_N,N,4,0","CS_SEXO,C,1","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_BAIRRO,C,8","NM_BAIRRO,C,60","CS_ZONA,C,1","ID_PAIS,C,4","DT_INVEST,D","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","DT_SORO,D","RESUL_SORO,C,1","DT_NS1,D","RESUL_NS1,C,1","DT_VIRAL,D","RESUL_VI_N,C,1","DT_PCR,D","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","DT_INTERNA,D","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CO_BAINF,C,8","NOBAIINF,C,60","CLASSI_FIN,C,2","CRITERIO,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","DT_OBITO,D","DT_ENCERRA,D","DS_OBS,C,255","TP_SISTEMA,C,1","DT_DIGITA,D","CS_FLXRET,C,1","IDENT_MICR,C,50",MES DO CASO
0,6902153,2,A90,2025-02-21,202508,2025,41,410690,1356,2639548,02/18/25,202508,06/05/85,4039,HOMEM,6,PARDO,9.0,25,250400,1421,606.0,TRES IRMAS,NaN,1,02/21/25,998999.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DENGUE,2.0,NaN,1.0,NaN,04/23/25,"PACIENTE REFERE SENSAÃ├O FEBRIL, MIALGIA, ARD╩...",2.0,02/23/25,1,4.0,Fevereiro
1,93151,2,A90,2025-09-14,202538,2025,25,250400,1421,9374833,09/13/25,202537,09/15/81,4043,HOMEM,6,PARDO,6.0,25,250400,1421,603.0,MALVINAS,URBANA,1,09/14/25,NaN,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESCARTADO,1.0,NaN,1.0,NaN,09/23/25,NaN,2.0,09/23/25,0,4.0,Setembro
2,93227,2,A90,2025-09-23,202539,2025,25,250400,1421,9374833,09/22/25,202539,12/08/93,4031,MULHER,9,PARDO,6.0,25,250400,1421,5.0,BODOCONGO,URBANA,1,09/23/25,NaN,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESCARTADO,2.0,NaN,1.0,NaN,09/30/25,NaN,2.0,09/30/25,0,4.0,Setembro
3,93254,2,A90,2025-09-11,202537,2025,25,250400,1421,9352902,09/06/25,202536,07/26/05,4020,MULHER,5,PARDO,6.0,25,250400,1421,606.0,TRES IRMAS,URBANA,1,09/11/25,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESCARTADO,2.0,NaN,1.0,NaN,09/30/25,NaN,2.0,09/30/25,0,4.0,Setembro
4,93193,2,A90,2025-09-26,202539,2025,25,250400,1421,7052251,09/24/25,202539,05/01/99,4026,HOMEM,6,PARDO,6.0,25,250400,1421,3.0,ALTO BRANCO,URBANA,1,09/26/25,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09/26/25,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESCARTADO,1.0,NaN,1.0,NaN,09/30/25,NaN,2.0,09/29/25,0,4.0,Setembro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3045,7040821,2,A90,2025-03-27,202513,2025,23,230440,1519,6985483,03/26/25,202513,07/26/01,4023,MULHER,5,BRANCO,9.0,25,250400,1421,NaN,BAIRRO - GALETO,NaN,1,03/27/25,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,05/27/25,NaN,2.0,10/24/25,1,4.0,Março
3046,5917940,2,A90,2025-01-28,202505,2025,52,520870,1779,4313593,01/23/25,202504,11/08/99,4025,HOMEM,6,IGNORADO,NaN,25,250400,1421,NaN,NaN,NaN,1,01/28/25,NaN,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,DENGUE,1.0,NaN,1.0,NaN,03/30/25,NaN,2.0,01/28/25,1,4.0,Janeiro
3047,5703527,2,A90,2025-05-16,202520,2025,52,521973,1779,2336960,05/13/25,202520,11/26/73,4051,HOMEM,6,PARDO,NaN,25,250400,1421,7.0,CATOLE,NaN,1,05/16/25,NaN,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,05/16/25,1.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,DENGUE,1.0,NaN,1.0,NaN,05/20/25,NaN,2.0,05/20/25,1,4.0,Maio
3048,902713,2,A90,2025-04-16,202516,2025,25,250750,1377,7870930,04/13/25,202516,09/20/74,4050,HOMEM,6,IGNORADO,9.0,25,250400,1421,52.0,SANTA CRUZ,URBANA,1,04/16/25,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,4.0,04/16/25,2.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESCARTADO,2.0,NaN,1.0,NaN,06/16/25,NaN,2.0,05/07/25,1,4.0,Abril
3049,5003111,2,A90,2025-07-25,202530,2025,25,250750,1377,3056724,07/21/25,202530,01/10/96,4029,MULHER,5,PARDO,NaN,25,250400,1421,13.0,UNIVERSITARIO,URBANA,1,07/25/25,NaN,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,25.0,1.0,250400.0,NaN,NaN,8.0,NaN,NaN,NaN,NaN,09/24/25,NaN,2.0,07/25/25,1,4.0,Julho

In [ ]:
np.unique(df['ID_MN_RESI,C,6'])

array([250400])

In [ ]:
np.unique(df['MES DO CASO'].astype(str), return_counts=True)

(array(['Abril', 'Agosto', 'Fevereiro', 'Janeiro', 'Julho', 'Junho',
        'Maio', 'Março', 'Novembro', 'Outubro', 'Setembro'], dtype=object),
 array([283, 233, 537, 217, 173, 240, 296, 396, 131, 240, 304]))

In [ ]:
np.unique(df['NM_BAIRRO,C,60'].astype(str), return_counts=True)

(array(['ACACIO FIGUEIREDO', 'ACUDE DE DENTRO', 'ALTO BRANCO',
        'ALUISIO CAMPOS', 'ALUIZIO CAMPOS', 'ARAXA', 'BAIRRO - GALETO',
        'BAIRRO DAS CIDADES', 'BAIRRO DAS NACOES', 'BAIRRO UNIVERSITARIO',
        'BELA VISTA', 'BODOCONGO', 'BOSQUE', 'CAJAZEIRAS', 'CAPIM GRANDE',
        'CARDOSO DE BAIXO', 'CASTELO BRANCO', 'CATOLE',
        'CATOLE DE BOA VISTA', 'CATOLE DE JOSE FERREIRA',
        'CATOLE ZE FERREIRA', 'CENTENARIO', 'CENTRO', 'CINZA', 'CONCEICAO',
        'CONJ SEVERINO CABRAL', 'CRUZEIRO', 'CUITES', 'DINAMERICA',
        'DISTRITO INDUSTRIAL', 'ESTACAO VELHA', 'ESTREITO', 'FELIX AMARO',
        'GALANTE', 'GLORIA', 'ITARARE', 'JARDIM CONTINENTAL',
        'JARDIM PAULISTANO', 'JARDIM QUARENTA', 'JARDIM TAVARES',
        'JARDIM VERDEJANTE', 'JEREMIAS', 'JORGE', 'JOSE PINHEIRO',
        'LAGOA DE DENTRO', 'LARANJEIRAS', 'LAURITZEN', 'LIBERDADE',
        'LIGEIRO', 'LOUZEIRO', 'LUCAS', 'MALVINAS', 'MALVINAS I',
        'MARINHO', 'MATIAS', 'MIRANTE', 'MONTE CASTELO', 'MONTE SANTO',
        'NOVA BRASILIA', 'NOVO BODOCONGO', 'NOVO CRUZEIRO',
        'NOVO HORIZONTE', 'PALMEIRA', 'PALMEIRA IMPERIAL', 'PEDREGAL',
        'PORTAL SUDOESTE', 'PORTEIRA DE PEDRA', 'PRATA',
        'PRESIDENTE MEDICE', 'PRESIDENTE MEDICI', 'QUARENTA',
        'QUEIMADAS DA EMA', 'RAMADINHA', 'RAMADINHA II', 'RESSUREICAO',
        'ROCHA CAVALCANTE', 'RONALDO CUNHA LIMA', 'ROSA CRUZ',
        'SALGADINHO', 'SANDRA CAVALCANTE', 'SANTA CRUZ', 'SANTA ROSA',
        'SANTA TEREZINHA', 'SANTO ANTONIO', 'SAO JANUARIO', 'SAO JOSE',
        'SAO JOSE DA MATA', 'SERRA DE JOAQUIM VIEIRA', 'SERROTAO', 'SITI',
        'SITIO BOI VELHA', 'SÒO JOSE', 'TAMBOR', 'TRES IRMAES',
        'TRES IRMAS', 'UNIVERSITARIO', 'VELAME', 'VELHA', 'VERDEJANTE',
        'VILA CABRAL', 'ZONA RURAL', 'nan'], dtype=object),
 array([ 66,   4,  50,   1,  65,  17,   1,  55,  10,  10,  24, 161,   1,
          1,   2,   1,  10,  96,   3,   4,   7,  56,  67,   4,  21,   2,
        112,  16,  41,  30,  14,   8,   1,  26,   3,  18,  14,  48,  13,
         14,   7,  41,   1,  59,   3,   1,   2,  95,  12,   7,   9, 270,
          1,   4,   1,   8,  23,  56,  40,  14,  22,  12,  32,  16,  65,
          1,   1,  12,  46,  24,  70,   1,  78,   1,   2,  15,   4,   5,
          2,  21,  70, 119,  12,  25,   4,  23,  54,   1, 114,   1,   1,
          1,  28,   8, 250,  22,  68,   2,   4,  22,   4,  36]))

In [ ]:
#Corrigindo incoerências na coluna de bairros


df['NM_BAIRRO,C,60']=df['NM_BAIRRO,C,60'].replace({
    'VELHA' : 'ESTACAO VELHA',
    'MALVINAS I': 'MALVINAS',
    'TRES IRMAES': 'TRES IRMAS',
    'BOSQUE': 'SAO JOSE DA MATA',
    'PRESIDENTE MEDICE': 'PRESIDENTE MEDICI',
    'QUARENTA': 'JARDIM QUARENTA',
    'MALVINAS I': 'MALVINAS',
    'SÒO JOSE': 'SAO JOSE',
    'ALUISIO CAMPOS': 'ALUIZIO CAMPOS',
    'BAIRRO - GALETO': 'CATOLE',
    'CAPIM GRANDE': 'SITIO CAPIM GRANDE',
    'CATOLE DE JOSE FERREIRA': 'CATOLE DE ZE FERREIRA',
    'CATOLE ZE FERREIRA': 'CATOLE DE ZE FERREIRA',
    'FELIX AMARO': 'SITIO FELIX AMARO',
    'JORGE': 'SITIO JORGE',
    'RAMADINHA II': 'RAMADINHA',
    'SITI': 'SITIO BOI VELHA',
    'LUCAS': 'SITIO LUCAS'

})

In [ ]:
#Arrumando os graus de escolaridade

escolaridade={
    0: 'ANALFABETO',
    1: 'PRIMARIO INCOMPLETO',
    2: 'PRIMARIO COMPLETO',
    3: '1 GRAU INCOMPLETO',
    4: 'FUNDAMENTAL COMPLETO',
    5: 'ENSINO MÉDIO INCOMPLETO',
    6: 'ENSINO MÉDIO COMPLETO',
    7: 'SUPERIOR INCOMPLETO',
    8: 'SUPERIOR COMPLETO',
    9: 'IGNORADO',
    10: 'NÃO SE APLICA'
}
df['CS_ESCOL_N,C,2']=df['CS_ESCOL_N,C,2'].replace(escolaridade)

In [ ]:
df['NM_BAIRRO,C,60'] = df['NM_BAIRRO,C,60'].str.strip()


bairros_limpos, freq_limpa = np.unique(df['NM_BAIRRO,C,60'].astype(str), return_counts=True)
display(pd.DataFrame({'NM_BAIRRO,C,60': bairros_limpos, 'Count': freq_limpa}).sort_values(by='Count', ascending=False).head(20))

       NM_BAIRRO,C,60  Count
43           MALVINAS    271
83         TRES IRMAS    258
9           BODOCONGO    161
69         SANTA ROSA    119
76           SERROTAO    114
21           CRUZEIRO    112
13             CATOLE     97
40          LIBERDADE     95
32    JARDIM QUARENTA     83
61          RAMADINHA     79
68         SANTA CRUZ     70
59  PRESIDENTE MEDICI     70
85             VELAME     68
17             CENTRO     67
3      ALUIZIO CAMPOS     66
0   ACACIO FIGUEIREDO     66
55           PEDREGAL     65
36      JOSE PINHEIRO     59
16         CENTENARIO     56
48        MONTE SANTO     56

In [ ]:
# Calculate the frequency of each neighborhood
neighborhood_frequency = df['NM_BAIRRO,C,60'].value_counts().reset_index()
neighborhood_frequency.columns = ['Bairro', 'Frequência']

# Sort the DataFrame by frequency in descending order
neighborhood_frequency = neighborhood_frequency.sort_values(by='Frequência', ascending=False)

# Get the top N neighborhoods for better visualization (optional, adjust N as needed)
# For now, let's display all, but if there are too many, we might limit it.
# neighborhood_frequency_top = neighborhood_frequency.head(20)

# Create the bar chart
fig = plx.bar(
    neighborhood_frequency,
    x='Bairro',
    y='Frequência',
    title='Frequência de Casos por Bairro',
    labels={'Bairro': 'Bairro', 'Frequência': 'Número de Casos'},
    color_discrete_sequence=plx.colors.qualitative.Pastel
)

fig.update_layout(
    xaxis_title='Bairro',
    yaxis_title='Número de Casos',
    xaxis_tickangle=-45 # Rotate x-axis labels for better readability
)

fig.show()

In [ ]:
#Trazendo as estações para trabalhar abordagens

estacoes_por_mes={
    'Dezembro' : 'VERAO',
    'Janeiro': 'VERAO',
    'Fevereiro': 'VERAO',
    'Março': 'VERAO',
    'Abril': 'OUTONO',
    'Maio': 'OUTONO',
    'Junho': 'OUTONO',
    'Julho': 'INVERNO',
    'Agosto': 'INVERNO',
    'Setembro': 'INVERNO',
    'Outubro': 'PRIMAVERA',
    'Novembro': 'PRIMAVERA'
}
df['ESTACAO POR CASO']=df['MES DO CASO'].replace(estacoes_por_mes)

In [ ]:
df['ESTACAO POR CASO'].value_counts()

ESTACAO POR CASO
VERAO        1150
OUTONO        819
INVERNO       710
PRIMAVERA     371
Name: count, dtype: int64

In [ ]:
df['CS_ZONA,C,1'].value_counts()

CS_ZONA,C,1
URBANA    2966
RURAL       54
Name: count, dtype: int64

In [ ]:
df['CS_RACA,C,1'].value_counts()

CS_RACA,C,1
PARDO       3003
AMARELO       14
IGNORADO      14
BRANCO        10
INDIGENA       8
PRETO          1
Name: count, dtype: int64

In [ ]:
df['SOROTIPO,C,1'].astype(str).value_counts()

SOROTIPO,C,1
nan       2954
DENV 2      58
DENV 1      33
DENV 3       5
Name: count, dtype: int64

In [ ]:
df.rename(columns={
    'DT_NOTIFIC,D': 'DATA REGISTRO',
    'CS_SEXO,C,1': 'SEXO DO PACIENTE',
    'CS_RACA,C,1': 'RAÇA',
    'CS_ESCOL_N,C,2': 'GRAU ESCOLARIDADE',
    'NM_BAIRRO,C,60': 'BAIRRO',
    'CS_ZONA,C,1': 'ZONA',
    'ID_UNIDADE,C,7': 'UNIDADE DE ATENDIMENTO',
    'DT_NASC,D': 'DATA DE NASCIMENTO',
    'CLASSI_FIN,C,2': 'CLASS DOENCA',
    'SEM_PRI,C,6': 'SEMANA EPDM',
    'DT_SIN_PRI,D': 'DATA PRIMEIROS SINTOMAS',
    'SOROTIPO,C,1': 'SOROTIPO'

},inplace=True)

In [ ]:
df['GRAU ESCOLARIDADE'].astype(str).value_counts()

GRAU ESCOLARIDADE
ENSINO MÉDIO COMPLETO      2810
NÃO SE APLICA                53
ENSINO MÉDIO INCOMPLETO      50
IGNORADO                     35
1 GRAU INCOMPLETO            22
PRIMARIO COMPLETO            21
nan                          20
FUNDAMENTAL COMPLETO         19
PRIMARIO INCOMPLETO           9
SUPERIOR INCOMPLETO           7
SUPERIOR COMPLETO             4
Name: count, dtype: int64

In [ ]:
df['DATA DE NASCIMENTO'] = pd.to_datetime(df['DATA DE NASCIMENTO'], format='%m/%d/%y', errors='coerce')

# Correcting years that are in the future (e.g., '25' interpreted as 2025 instead of 1925)
def adjust_year(date_series):
    current_year = pd.Timestamp.now().year
    adjusted_dates = []
    for date in date_series:
        if pd.isna(date):
            adjusted_dates.append(pd.NaT)
            continue
        if date.year > current_year:
            adjusted_dates.append(date - pd.DateOffset(years=100))
        else:
            adjusted_dates.append(date)
    return pd.Series(adjusted_dates, index=date_series.index)

df['DATA DE NASCIMENTO'] = adjust_year(df['DATA DE NASCIMENTO'])

# Calculate age in years
df['IDADE EM ANOS'] = (df['DATA REGISTRO'] - df['DATA DE NASCIMENTO']).dt.days / 365.25

# Round the age to the nearest integer
df['IDADE EM ANOS'] = df['IDADE EM ANOS'].round().astype('Int64')

display(df[['DATA DE NASCIMENTO', 'DATA REGISTRO', 'IDADE EM ANOS']].head())

  DATA DE NASCIMENTO DATA REGISTRO  IDADE EM ANOS
0         1985-06-05    2025-02-21             40
1         1981-09-15    2025-09-14             44
2         1993-12-08    2025-09-23             32
3         2005-07-26    2025-09-11             20
4         1999-05-01    2025-09-26             26

In [ ]:
df['IDADE EM ANOS'].value_counts()

IDADE EM ANOS
23    144
25    128
26    122
24    115
22    110
     ...
87      1
98      1
94      1
88      1
90      1
Name: count, Length: 92, dtype: Int64

In [ ]:
df_final2025 = df[['IDADE EM ANOS', 'SEXO DO PACIENTE','RAÇA','ESTACAO POR CASO','MES DO CASO','GRAU ESCOLARIDADE','BAIRRO','ZONA','UNIDADE DE ATENDIMENTO','DATA REGISTRO', 'CLASS DOENCA','SEMANA EPDM', 'DATA PRIMEIROS SINTOMAS','SOROTIPO']]

In [ ]:
df_final2025.head()

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
0,40,HOMEM,PARDO,VERAO,Fevereiro,IGNORADO,TRES IRMAS,NaN,2639548,2025-02-21,DENGUE,202508,02/18/25,NaN
1,44,HOMEM,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,9374833,2025-09-14,DESCARTADO,202537,09/13/25,NaN
2,32,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,9374833,2025-09-23,DESCARTADO,202539,09/22/25,NaN
3,20,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,TRES IRMAS,URBANA,9352902,2025-09-11,DESCARTADO,202536,09/06/25,NaN
4,26,HOMEM,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,ALTO BRANCO,URBANA,7052251,2025-09-26,DESCARTADO,202539,09/24/25,NaN

In [ ]:
df_final2025 = df_final2025[df_final2025['CLASS DOENCA'] != 'DESCARTADO']
df_final2025 = df_final2025[df_final2025['CLASS DOENCA'] != 'CHIKUNGUNYA']

# Map the unclassified '8.0' to 'DENGUE'
df_final2025['CLASS DOENCA'] = df_final2025['CLASS DOENCA'].replace({8.0: 'DENGUE'})

# The previous fillna(None) was causing an error. NaN values will remain as NaN in object dtype columns.

display(df_final2025.head())

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
0,40,HOMEM,PARDO,VERAO,Fevereiro,IGNORADO,TRES IRMAS,NaN,2639548,2025-02-21,DENGUE,202508,02/18/25,NaN
32,22,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,GALANTE,URBANA,9374833,2025-01-21,DENGUE,202504,01/20/25,NaN
35,47,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,URBANA,2363275,2025-01-06,DENGUE,202501,12/29/24,NaN
87,23,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,JARDIM QUARENTA,NaN,3006204,2025-01-03,DENGUE,202501,12/29/24,DENV 2
89,26,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,7052251,2025-04-03,DENGUE,202514,04/02/25,NaN

In [ ]:

np.unique(df_final2025['ZONA'].astype(str),return_counts=True)

(array(['RURAL', 'URBANA', 'nan'], dtype=object), array([  6, 206,   8]))

In [ ]:


# 1. Dicionário Exclusivo (Baseado na sua lista fornecida)
unidades = {
    # --- Grandes Hospitais / Maternidades ---
    220337: "HOSPITAL DE CLINICAS DE CAMPINA GRANDE",
    2362287: "INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA",
    2362848: "HOSPITAL DA FAP",
    2362856: "HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES",
    2362880: "HOSPITAL MUNICIPAL DR EDGLEY",
    2363070: "HOSPITAL MUNICIPAL PEDRO I",
    2676060: "HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO (HUAC)",
    7113692: "HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO",

    # --- UPAs (Unidades de Pronto Atendimento) ---
    3056724: "UPA 24H DR MAIA (ALTO BRANCO) - ANTIGO",
    7052251: "UPA 24H DR MAIA (ALTO BRANCO)",
    5480957: "UPA 24H DR ADHEMAR DANTAS (DINAMERICA) - ANTIGO",
    9374833: "UPA 24H DR ADHEMAR DANTAS (DINAMERICA)",

    # --- Clínicas Especializadas / Centros de Referência ---
    2362627: "CLIPE CLINICA PEDIATRICA",
    2362678: "UROCLINICA",
    2362732: "CENTRO MEDICO SANTA CLARA",
    2362767: "CLINICA E MATERNIDADE DR LUIZ G MOURA",
    2362821: "INSTITUTO SAO VICENTE DE PAULO",
    2362953: "APAE",
    2363275: "VIGILANCIA EPIDEMIOLOGICA",
    2415631: "HEMOCENTRO REGIONAL DE CAMPINA GRANDE",
    2639548: "CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS",
    2806045: "CAPS AD III",
    2975637: "LABORATORIO DE ANALISES CLINICAS DO MUNICIPIO",
    3006204: "CLINICA SANTA CLARA",
    4313593: "CEREST REGIONAL",
    5116279: "SAMU 192",
    6267939: "POLICLINICA DO CATOLE",
    6985483: "CAPS I",
    9145133: "ACADEMIA DE SAUDE",

    # --- Centros de Saúde e UBS (Atenção Básica) ---
    2336960: "CENTRO DE SAUDE DA PALMEIRA",
    2362260: "CENTRO DE SAUDE DE SAO JOSE DA MATA",
    2362279: "CENTRO DE SAUDE DA LIBERDADE",
    2362309: "CENTRO DE SAUDE DE SANTA ROSA",
    2362317: "CENTRO DE SAUDE FRANCISCO PINTO",
    2362325: "CENTRO DE SAUDE DO CATOLE",
    2362392: "UNIDADE MISTA DE GALANTE",
    2362406: "CENTRO DE SAUDE DE BODOCONGO",
    2595397: "UBS RAIMUNDO CARNEIRO",
    2595400: "UBS BENJAMIN B MARANHAO",
    2595451: "UBS MALVINAS IV",
    2677725: "UBS CIDADES",
    2792788: "UBS MARIA DE LOURDES LEONCIO",
    2792877: "UBS PARQUE DOS SERIDO",
    5053129: "UBS GALANTE I",
    5053269: "UBS SAO JOSE DA MATA I",
    5116457: "UBS ODETE LEANDRO",
    5131960: "UBS BAIRRO DAS CIDADES",
    5485754: "UBS RESIDENCIAL MAJOR VENEZIANO",
    5491215: "UBS PORTAL SUDOESTE",
    5616212: "UBS ALOISIO PEREIRA LIMA",
    5932416: "UBS NOVO CRUZEIRO",
    5968992: "UBS ANA CANTALICE",
    6045340: "UBS JOSEFA VENTURA TOME",
    6679528: "UBS ACACIO FIGUEIREDO",
    7417659: "UBS COLINAS DO SOL",
    7870930: "UBS JARDIM VERDEJANTE",
    9263691: "UBS GRANDE CAMPINA",
    9352899: "UBS RAMADINHA II",
    9352902: "UBS BAIRRO DAS NACOES",
    9385924: "UBS NOVA BRASILIA",
    9387927: "UBS VILA NOVA",

    # --- Erros / Outros ---
    1120: "CODIGO INVALIDO (ERRO DE REGISTRO)"
}

# 2. Lista de IDs considerados de Campina Grande (Todos exceto o 1120)
ids_campina_grande = [
    220337, 2336960, 2362260, 2362279, 2362287, 2362309, 2362317, 2362325,
    2362392, 2362406, 2362627, 2362678, 2362732, 2362767, 2362821, 2362848,
    2362856, 2362880, 2362953, 2363070, 2363275, 2415631, 2595397, 2595400,
    2595451, 2639548, 2676060, 2677725, 2792788, 2792877, 2806045, 2975637,
    3006204, 3056724, 4313593, 5053129, 5053269, 5116279, 5116457, 5131960,
    5480957, 5485754, 5491215, 5616212, 5932416, 5968992, 6045340, 6267939,
    6679528, 6985483, 7052251, 7113692, 7417659, 7870930, 9145133, 9263691,
    9352899, 9352902, 9374833, 9385924, 9387927
]

# --- APLICAÇÃO NO DATAFRAME ---

# 1. Converter para numérico para garantir que o 'join' funcione com o dicionário
df_final2025['UNIDADE DE ATENDIMENTO'] = pd.to_numeric(df_final2025['UNIDADE DE ATENDIMENTO'], errors='coerce')

# 2. Criar a classificação de Origem (Campina Grande vs Outros/Erro)
df_final2025['ORIGEM_UNIDADE'] = np.where(
    df_final2025['UNIDADE DE ATENDIMENTO'].isin(ids_campina_grande),
    'Campina Grande',
    'Externo/Outro/Erro'
)

# 3. Substituir os códigos pelos nomes das unidades
df_final2025['UNIDADE DE ATENDIMENTO'] = df_final2025['UNIDADE DE ATENDIMENTO'].replace(unidades)

In [ ]:
df_final2025

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,40,HOMEM,PARDO,VERAO,Fevereiro,IGNORADO,TRES IRMAS,NaN,CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS,2025-02-21,DENGUE,202508,02/18/25,NaN,Campina Grande
32,22,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,GALANTE,URBANA,UPA 24H DR ADHEMAR DANTAS (DINAMERICA),2025-01-21,DENGUE,202504,01/20/25,NaN,Campina Grande
35,47,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,URBANA,VIGILANCIA EPIDEMIOLOGICA,2025-01-06,DENGUE,202501,12/29/24,NaN,Campina Grande
87,23,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,JARDIM QUARENTA,NaN,CLINICA SANTA CLARA,2025-01-03,DENGUE,202501,12/29/24,DENV 2,Campina Grande
89,26,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,UPA 24H DR MAIA (ALTO BRANCO),2025-04-03,DENGUE,202514,04/02/25,NaN,Campina Grande
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3044,55,MULHER,IGNORADO,INVERNO,Agosto,IGNORADO,DINAMERICA,URBANA,HEMOCENTRO REGIONAL DE CAMPINA GRANDE,2025-08-29,DENGUE,202534,08/22/25,NaN,Campina Grande
3045,24,MULHER,BRANCO,VERAO,Março,IGNORADO,CATOLE,NaN,CAPS I,2025-03-27,DENGUE,202513,03/26/25,NaN,Campina Grande
3046,25,HOMEM,IGNORADO,VERAO,Janeiro,NaN,NaN,NaN,CEREST REGIONAL,2025-01-28,DENGUE,202504,01/23/25,NaN,Campina Grande
3047,51,HOMEM,PARDO,OUTONO,Maio,NaN,CATOLE,NaN,CENTRO DE SAUDE DA PALMEIRA,2025-05-16,DENGUE,202520,05/13/25,NaN,Campina Grande
3049,30,MULHER,PARDO,INVERNO,Julho,NaN,UNIVERSITARIO,URBANA,UPA 24H DR MAIA (ALTO BRANCO) - ANTIGO,2025-07-25,DENGUE,202530,07/21/25,NaN,Campina Grande

In [ ]:
df_final2025['RAÇA'].replace('IGNORADO','PARDO',inplace=True)

/tmp/ipython-input-722296122.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [ ]:
# Fill NaN values in the 'ZONA' column with 'URBANA'
df_final2025['ZONA'].fillna('URBANA', inplace=True)

# Display unique values and their counts for 'ZONA' to confirm the change
np.unique(df_final2025['ZONA'].astype(str), return_counts=True)

/tmp/ipython-input-1317722477.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

(array(['RURAL', 'URBANA'], dtype=object), array([  6, 214]))

In [ ]:
np.unique(df_final2025['UNIDADE DE ATENDIMENTO'].astype(str),return_counts=True)

(array(['ACADEMIA DE SAUDE', 'APAE', 'CAPS AD III', 'CAPS I',
        'CENTRO DE SAUDE DA PALMEIRA',
        'CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS', 'CEREST REGIONAL',
        'CLINICA SANTA CLARA', 'CODIGO INVALIDO (ERRO DE REGISTRO)',
        'HEMOCENTRO REGIONAL DE CAMPINA GRANDE',
        'HOSPITAL DE CLINICAS DE CAMPINA GRANDE',
        'HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES',
        'HOSPITAL MUNICIPAL DR EDGLEY',
        'HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO',
        'HOSPITAL MUNICIPAL PEDRO I',
        'HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO (HUAC)',
        'INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA',
        'INSTITUTO SAO VICENTE DE PAULO', 'UBS ALOISIO PEREIRA LIMA',
        'UBS COLINAS DO SOL', 'UBS GRANDE CAMPINA', 'UBS VILA NOVA',
        'UPA 24H DR ADHEMAR DANTAS (DINAMERICA)',
        'UPA 24H DR MAIA (ALTO BRANCO)',
        'UPA 24H DR MAIA (ALTO BRANCO) - ANTIGO',
        'VIGILANCIA EPIDEMIOLOGICA'], dtype=object),
 array([ 5,  2,  1,  1,  1,  1,  1,  8,  2,  1,  2,  5, 16, 10, 52,  5,  5,
         1,  3,  1,  1,  1, 62, 22,  1, 10]))

In [ ]:
df_final2025['UNIDADE DE ATENDIMENTO'].value_counts()

UNIDADE DE ATENDIMENTO
UPA 24H DR ADHEMAR DANTAS (DINAMERICA)                        62
HOSPITAL MUNICIPAL PEDRO I                                    52
UPA 24H DR MAIA (ALTO BRANCO)                                 22
HOSPITAL MUNICIPAL DR EDGLEY                                  16
HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO            10
VIGILANCIA EPIDEMIOLOGICA                                     10
CLINICA SANTA CLARA                                            8
HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES     5
INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA                     5
HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO (HUAC)                 5
ACADEMIA DE SAUDE                                              5
UBS ALOISIO PEREIRA LIMA                                       3
CODIGO INVALIDO (ERRO DE REGISTRO)                             2
HOSPITAL DE CLINICAS DE CAMPINA GRANDE                         2
APAE                                                           2
CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS                  1
INSTITUTO SAO VICENTE DE PAULO                                 1
UBS VILA NOVA                                                  1
CAPS AD III                                                    1
UBS GRANDE CAMPINA                                             1
UBS COLINAS DO SOL                                             1
HEMOCENTRO REGIONAL DE CAMPINA GRANDE                          1
CAPS I                                                         1
CEREST REGIONAL                                                1
CENTRO DE SAUDE DA PALMEIRA                                    1
UPA 24H DR MAIA (ALTO BRANCO) - ANTIGO                         1
Name: count, dtype: int64

In [ ]:
unidades_s, freq_limpa = np.unique(df_final2025['UNIDADE DE ATENDIMENTO'].astype(str), return_counts=True)
display(pd.DataFrame({'UNIDADE DE ATENDIMENTO': unidades_s, 'Count': freq_limpa}).sort_values(by='Count', ascending=False).head(20))

                               UNIDADE DE ATENDIMENTO  Count
22             UPA 24H DR ADHEMAR DANTAS (DINAMERICA)     62
14                         HOSPITAL MUNICIPAL PEDRO I     52
23                      UPA 24H DR MAIA (ALTO BRANCO)     22
12                       HOSPITAL MUNICIPAL DR EDGLEY     16
25                          VIGILANCIA EPIDEMIOLOGICA     10
13  HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...     10
7                                 CLINICA SANTA CLARA      8
16         INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA      5
11  HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...      5
0                                   ACADEMIA DE SAUDE      5
15     HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO (HUAC)      5
18                           UBS ALOISIO PEREIRA LIMA      3
10             HOSPITAL DE CLINICAS DE CAMPINA GRANDE      2
1                                                APAE      2
8                  CODIGO INVALIDO (ERRO DE REGISTRO)      2
2                                         CAPS AD III      1
3                                              CAPS I      1
5       CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS      1
9               HEMOCENTRO REGIONAL DE CAMPINA GRANDE      1
6                                     CEREST REGIONAL      1

In [ ]:
df_final2025['SEXO DO PACIENTE'].astype(str).value_counts()

SEXO DO PACIENTE
MULHER    125
HOMEM      95
Name: count, dtype: int64

In [ ]:
df_final2025['DATA REGISTRO'] = df_final2025['DATA REGISTRO'].dt.year
display(df_final2025.head())

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,40,HOMEM,PARDO,VERAO,Fevereiro,IGNORADO,TRES IRMAS,URBANA,CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS,2025,DENGUE,202508,02/18/25,NaN,Campina Grande
32,22,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,GALANTE,URBANA,UPA 24H DR ADHEMAR DANTAS (DINAMERICA),2025,DENGUE,202504,01/20/25,NaN,Campina Grande
35,47,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,URBANA,VIGILANCIA EPIDEMIOLOGICA,2025,DENGUE,202501,12/29/24,NaN,Campina Grande
87,23,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,JARDIM QUARENTA,URBANA,CLINICA SANTA CLARA,2025,DENGUE,202501,12/29/24,DENV 2,Campina Grande
89,26,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,UPA 24H DR MAIA (ALTO BRANCO),2025,DENGUE,202514,04/02/25,NaN,Campina Grande

In [ ]:
df_final2025['SEMANA EPDM'] = df_final2025['SEMANA EPDM'].astype(str).str[-2:]
display(df_final2025.head())

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,40,HOMEM,PARDO,VERAO,Fevereiro,IGNORADO,TRES IRMAS,URBANA,CEO II CENTRO DE ESPECIALIDADES ODONTOLOGICAS,2025,DENGUE,08,02/18/25,NaN,Campina Grande
32,22,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,GALANTE,URBANA,UPA 24H DR ADHEMAR DANTAS (DINAMERICA),2025,DENGUE,04,01/20/25,NaN,Campina Grande
35,47,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,URBANA,VIGILANCIA EPIDEMIOLOGICA,2025,DENGUE,01,12/29/24,NaN,Campina Grande
87,23,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,JARDIM QUARENTA,URBANA,CLINICA SANTA CLARA,2025,DENGUE,01,12/29/24,DENV 2,Campina Grande
89,26,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,UPA 24H DR MAIA (ALTO BRANCO),2025,DENGUE,14,04/02/25,NaN,Campina Grande

In [ ]:
df_final2025['GRAU ESCOLARIDADE'].replace('IGNORADO','ENSINO MÉDIO COMPLETO',inplace=True)
df_final2025['GRAU ESCOLARIDADE'].value_counts()

/tmp/ipython-input-1775076814.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

GRAU ESCOLARIDADE
ENSINO MÉDIO COMPLETO      188
ENSINO MÉDIO INCOMPLETO      7
1 GRAU INCOMPLETO            5
NÃO SE APLICA                5
PRIMARIO INCOMPLETO          3
FUNDAMENTAL COMPLETO         1
SUPERIOR INCOMPLETO          1
PRIMARIO COMPLETO            1
SUPERIOR COMPLETO            1
Name: count, dtype: int64

In [ ]:
np.unique(df_final2025['BAIRRO'].astype(str))

array(['ACACIO FIGUEIREDO', 'ALTO BRANCO', 'ALUIZIO CAMPOS', 'ARAXA',
       'BAIRRO DAS CIDADES', 'BAIRRO DAS NACOES', 'BAIRRO UNIVERSITARIO',
       'BELA VISTA', 'BODOCONGO', 'CATOLE', 'CATOLE DE ZE FERREIRA',
       'CENTENARIO', 'CENTRO', 'CRUZEIRO', 'DINAMERICA', 'ESTACAO VELHA',
       'GALANTE', 'ITARARE', 'JARDIM PAULISTANO', 'JARDIM QUARENTA',
       'JARDIM TAVARES', 'JEREMIAS', 'JOSE PINHEIRO', 'LAGOA DE DENTRO',
       'LIBERDADE', 'LIGEIRO', 'LOUZEIRO', 'MALVINAS', 'MARINHO',
       'MIRANTE', 'MONTE SANTO', 'NOVA BRASILIA', 'NOVO HORIZONTE',
       'PALMEIRA', 'PALMEIRA IMPERIAL', 'PEDREGAL', 'PRESIDENTE MEDICI',
       'RAMADINHA', 'ROCHA CAVALCANTE', 'SANDRA CAVALCANTE', 'SANTA CRUZ',
       'SANTA ROSA', 'SANTO ANTONIO', 'SAO JOSE', 'SAO JOSE DA MATA',
       'SERRA DE JOAQUIM VIEIRA', 'SERROTAO', 'SITIO BOI VELHA',
       'SITIO LUCAS', 'TAMBOR', 'TRES IRMAS', 'UNIVERSITARIO', 'VELAME',
       'VILA CABRAL', 'ZONA RURAL', 'nan'], dtype=object)

In [ ]:
df_final2025['BAIRRO']=df_final2025['BAIRRO'].replace({
    'BAIRRO - GALETO': 'CATOLE',
    'LUCAS': 'SITIO LUACAS',
    'PALMEIRA IMPERIAL': 'PALMEIRA',
    'URBANA': 'JARDIM QUARENTA',
    'ZONA RURAL': 'JARDIM QUARENTA',
    'RAMADINHA II': 'RAMADINHA',
    'BAIRRO DAS NACOES': 'NACOES',
    'CATOLE DE JOSE FERREIRA': 'CATOLE DE ZE FERREIRA',
    'PRESIDENTE MEDICI': 'PRESIDENTE MEDICE',
    'UNIVERSITARIO': 'BAIRRO UNIVERSITARIO',
    'SITIO BOI VELHA': 'SITIO BOI VELHO'
})

In [ ]:
# Calculate the frequency of each neighborhood
neighborhood_frequency = df_final2025['BAIRRO'].value_counts().reset_index()
neighborhood_frequency.columns = ['Bairro', 'Frequência']

# Sort the DataFrame by frequency in descending order
neighborhood_frequency = neighborhood_frequency.sort_values(by='Frequência', ascending=False)

# Get the top N neighborhoods for better visualization (optional, adjust N as needed)
# For now, let's display all, but if there are too many, we might limit it.
# neighborhood_frequency_top = neighborhood_frequency.head(20)

# Create the bar chart
fig = plx.bar(
    neighborhood_frequency,
    x='Bairro',
    y='Frequência',
    title='Frequência de Casos por Bairro',
    labels={'Bairro': 'Bairro', 'Frequência': 'Número de Casos'},
    color_discrete_sequence=plx.colors.qualitative.Pastel
)

fig.update_layout(
    xaxis_title='Bairro',
    yaxis_title='Número de Casos',
    xaxis_tickangle=-45 # Rotate x-axis labels for better readability
)

fig.show()

In [ ]:
df_final2025['CLASS DOENCA'].value_counts()

CLASS DOENCA
DENGUE    213
Name: count, dtype: int64

In [ ]:
df_final2025['SOROTIPO'].value_counts()

SOROTIPO
DENV 2    56
DENV 1    28
DENV 3     5
Name: count, dtype: int64

In [ ]:
np.unique(df_final2025['BAIRRO'].astype(str),return_counts=True)

(array(['ACACIO FIGUEIREDO', 'ALTO BRANCO', 'ALUIZIO CAMPOS', 'ARAXA',
        'BAIRRO DAS CIDADES', 'BAIRRO UNIVERSITARIO', 'BELA VISTA',
        'BODOCONGO', 'CATOLE', 'CATOLE DE ZE FERREIRA', 'CENTENARIO',
        'CENTRO', 'CRUZEIRO', 'DINAMERICA', 'ESTACAO VELHA', 'GALANTE',
        'ITARARE', 'JARDIM PAULISTANO', 'JARDIM QUARENTA',
        'JARDIM TAVARES', 'JEREMIAS', 'JOSE PINHEIRO', 'LAGOA DE DENTRO',
        'LIBERDADE', 'LIGEIRO', 'LOUZEIRO', 'MALVINAS', 'MARINHO',
        'MIRANTE', 'MONTE SANTO', 'NACOES', 'NOVA BRASILIA',
        'NOVO HORIZONTE', 'PALMEIRA', 'PEDREGAL', 'PRESIDENTE MEDICE',
        'RAMADINHA', 'ROCHA CAVALCANTE', 'SANDRA CAVALCANTE', 'SANTA CRUZ',
        'SANTA ROSA', 'SANTO ANTONIO', 'SAO JOSE', 'SAO JOSE DA MATA',
        'SERRA DE JOAQUIM VIEIRA', 'SERROTAO', 'SITIO BOI VELHO',
        'SITIO LUCAS', 'TAMBOR', 'TRES IRMAS', 'VELAME', 'VILA CABRAL',
        'nan'], dtype=object),
 array([ 2,  2,  5,  2,  3,  3,  3,  8, 10,  2,  7, 10,  4,  7,  1,  3,  1,
         1, 28,  1,  2,  8,  1,  4,  2,  1, 25,  2,  4,  2,  2,  3,  2,  3,
         2,  4,  6,  1,  3,  2, 10,  3,  1,  3,  1,  2,  1,  1,  2,  7,  2,
         2,  3]))

In [ ]:
df_final2025['BAIRRO'].fillna('JARDIM QUARENTA',inplace=True)

/tmp/ipython-input-2866307632.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [ ]:
df_final2025['CLASS DOENCA'].value_counts()

CLASS DOENCA
DENGUE    213
Name: count, dtype: int64

In [ ]:
df_final2025.to_csv('dengue2025_tratado.csv',index=False)