In [72]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as plx
import matplotlib.pyplot as plt

In [73]:
df=pd.read_csv('/content/drive/MyDrive/Projetos/Pivic/dados/Dados/epidemiologia dengue cg/AnyConv.com__2018_SI_DENGON2642320_00.csv')
pd.set_option('display.max_columns',None)
df.head()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","ID_AGRAVO,C,5","DT_NOTIFIC,D","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","DT_SIN_PRI,D","SEM_PRI,C,6","DT_NASC,D","SOUNDEX,C,70","NU_IDADE_N,N,4,0","CS_SEXO,C,1","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_DISTRIT,C,9","ID_BAIRRO,C,8","NM_BAIRRO,C,60","ID_GEO1,C,8","ID_GEO2,C,8","CS_ZONA,C,1","ID_PAIS,C,4","DT_INVEST,D","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","DT_CHIK_S2,D","DT_PRNT,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_PRNT,C,1","DT_SORO,D","RESUL_SORO,C,1","DT_NS1,D","RESUL_NS1,C,1","DT_VIRAL,D","RESUL_VI_N,C,1","DT_PCR,D","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","DT_INTERNA,D","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CODISINF,C,4","CO_BAINF,C,8","NOBAIINF,C,60","CLASSI_FIN,C,2","CRITERIO,C,1","DOENCA_TRA,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","DT_OBITO,D","DT_ENCERRA,D","ALRM_HIPOT,C,1","ALRM_PLAQ,C,1","ALRM_VOM,C,1","ALRM_SANG,C,1","ALRM_HEMAT,C,1","ALRM_ABDOM,C,1","ALRM_LETAR,C,1","ALRM_HEPAT,C,1","ALRM_LIQ,C,1","DT_ALRM,D","GRAV_PULSO,C,1","GRAV_CONV,C,1","GRAV_ENCH,C,1","GRAV_INSUF,C,1","GRAV_TAQUI,C,1","GRAV_EXTRE,C,1","GRAV_HIPOT,C,1","GRAV_HEMAT,C,1","GRAV_MELEN,C,1","GRAV_METRO,C,1","GRAV_SANG,C,1","GRAV_AST,C,1","GRAV_MIOC,C,1","GRAV_CONSC,C,1","GRAV_ORGAO,C,1","DT_GRAV,D","MANI_HEMOR,C,1","EPISTAXE,C,1","GENGIVO,C,1","METRO,C,1","PETEQUIAS,C,1","HEMATURA,C,1","SANGRAM,C,1","LACO_N,C,1","PLASMATICO,C,1","EVIDENCIA,C,1","PLAQ_MENOR,C,7","CON_FHD,C,1","COMPLICA,C,1","NU_LOTE_I,C,9","DS_OBS,C,255","TP_SISTEMA,C,1","NDUPLIC_N,C,1","DT_DIGITA,D","DT_TRANSUS,D","DT_TRANSDM,D","DT_TRANSSM,D","DT_TRANSRM,D","DT_TRANSRS,D","DT_TRANSSE,D","NU_LOTE_V,C,7","NU_LOTE_H,C,7","CS_FLXRET,C,1","FLXRECEBI,C,7","IDENT_MICR,C,50","MIGRADO_W,C,1"
0,46224,2,A90,04/02/18,201814,2018,25,250400,1421.0,2363070,03/28/18,201813,09/18/90,NaN,4027,M,6,4,6.0,25,250400,1421,158.0,605.0,SANTA ROSA,NaN,NaN,1.0,1,04/02/18,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,04/02/18,1.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,1.0,04/02/18,25.0,250400.0,2363070.0,NaN,NaN,1.0,25.0,1.0,250400.0,158.0,605.0,SANTA ROSA,10,1.0,NaN,NaN,1.0,NaN,04/11/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"PACIENTE COM FEBRE,CEFALEIA,MIALGIA,VOMITO.",2.0,NaN,04/05/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN
1,46888,2,A90,04/30/18,201818,2018,25,250400,1421.0,2363070,04/20/18,201816,07/26/63,NaN,4054,F,5,4,4.0,25,250400,1421,154.0,9.0,CENTENARIO,NaN,NaN,1.0,1,04/30/18,999992.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,04/30/18,2.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,1.0,04/30/18,25.0,250400.0,2363070.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1.0,NaN,NaN,1.0,NaN,05/25/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PACIENTE ENCAMINHADA DA UPA COM QUEIXA DE CEFA...,2.0,NaN,05/09/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN
2,46886,2,A90,04/30/18,201818,2018,25,250400,1421.0,7113692,04/20/18,201816,05/10/05,NaN,4012,M,6,2,3.0,25,250400,1421,157.0,503.0,CRUZEIRO,NaN,NaN,1.0,1,04/30/18,999991.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,04/26/18,1.0,NaN,4.0,NaN,4.0,NaN,4.0,NaN,4.0,4.0,1.0,04/24/18,25.0,250400.0,7113692.0,NaN,NaN,1.0,25.0,1.0,250400.0,157.0,503.0,CRUZEIRO,10,1.0,NaN,NaN,1.0,NaN,05/25/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,05/09/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN
3,48082,2,A90,06/20/18,201825,2018,25,250400,1421.0,2362287,06/20/18,201825,03/15/85,NaN,4033,F,3,4,7.0,25,250400,1421,157.0,504.0,JARDIM PAULISTANO,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,08/20/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,07/04/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,4.0,NaN
4,21860,2,A90,06/12/18,201824,2018,25,250400,1421.0,2362856,06/12/18,201824,05/23/81,NaN,4037,M,6,9,9.0,25,250400,1421,NaN,508.0,SANTA CRUZ,NaN,NaN,NaN,1,06/13/18,NaN,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,06/15/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,8,3.0,NaN,NaN,NaN,NaN,08/12/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AGUARDO EXAMES PARA ENCERRAR O CASO.,2.0,NaN,06/15/18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4.0,NaN

In [74]:
classificacao={
    5: 'DESCARTADO',
    10: 'DENGUE',
    11: 'DENGUE C/ ALARME',
    12: 'DENGUE GRAVE',
    13: 'CHIKUNGUNYA'
}
df['CLASSI_FIN,C,2']=df['CLASSI_FIN,C,2'].replace(classificacao)

In [75]:
df.shape

(925, 146)

In [76]:
df=df.dropna(axis=1,how='all')

In [77]:
df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace({
    1: 'BRANCO',
    2: 'PRETO',
    3: 'AMARELO',
    4: 'PARDO',
    5: 'INDIGENA',
    9: 'IGNORADO'
})
# Correcting the problematic assignment from qZsae-tpZGZL here
df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace('IGNORADO','PARDO')

generos={
    'M': 'HOMEM',
    'F': 'MULHER'
}
df['CS_SEXO,C,1']=df['CS_SEXO,C,1'].replace(generos)


escolaridade={
    0: 'ANALFABETO',
    1: 'PRIMARIO INCOMPLETO',
    2: 'PRIMARIO COMPLETO',
    3: '1 GRAU INCOMPLETO',
    4: 'FUNDAMENTAL COMPLETO',
    5: 'ENSINO MÉDIO INCOMPLETO',
    6: 'ENSINO MÉDIO COMPLETO',
    7: 'SUPERIOR INCOMPLETO',
    8: 'SUPERIOR COMPLETO',
    9: 'IGNORADO',
    10: 'NÃO SE APLICA'
}
df['CS_ESCOL_N,C,2']=df['CS_ESCOL_N,C,2'].replace(escolaridade)

sorotipos={
    1:'DENV 1',
    2: 'DENV 2',
    3: 'DENV 3',
    4: 'DENV 4'
}
df['SOROTIPO,C,1']=df['SOROTIPO,C,1'].replace(sorotipos)

In [78]:
np.unique(df['CS_RACA,C,1'].astype(str),return_counts=True)

(array(['AMARELO', 'BRANCO', 'INDIGENA', 'PARDO', 'PRETO'], dtype=object),
 array([  3, 274,   2, 610,  36]))

In [79]:
np.unique(df['CS_SEXO,C,1'].astype(str), return_counts= True)

(array(['HOMEM', 'MULHER'], dtype=object), array([408, 517]))

In [80]:
df['DT_NOTIFIC,D'] = pd.to_datetime(df['DT_NOTIFIC,D'], format='%m/%d/%y')
df['MES DO CASO'] = df['DT_NOTIFIC,D'].dt.month

In [81]:
meses = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
df['MES DO CASO'] = df['MES DO CASO'].replace(meses)

In [82]:
estacoes_por_mes={
    'Dezembro' : 'VERAO',
    'Janeiro': 'VERAO',
    'Fevereiro': 'VERAO',
    'Março': 'VERAO',
    'Abril': 'OUTONO',
    'Maio': 'OUTONO',
    'Junho': 'OUTONO',
    'Julho': 'INVERNO',
    'Agosto': 'INVERNO',
    'Setembro': 'INVERNO',
    'Outubro': 'PRIMAVERA',
    'Novembro': 'PRIMAVERA'
}
df['ESTACAO POR CASO']=df['MES DO CASO'].replace(estacoes_por_mes)

In [83]:
df.rename(columns={
    'DT_NOTIFIC,D': 'DATA REGISTRO',
    'CS_SEXO,C,1': 'SEXO DO PACIENTE',
    'CS_RACA,C,1': 'RAÇA',
    'CS_ESCOL_N,C,2': 'GRAU ESCOLARIDADE',
    'NM_BAIRRO,C,60': 'BAIRRO',
    'CS_ZONA,C,1': 'ZONA',
    'ID_UNIDADE,C,7': 'UNIDADE DE ATENDIMENTO',
    'DT_NASC,D': 'DATA DE NASCIMENTO',
    'CLASSI_FIN,C,2': 'CLASS DOENCA',
    'SEM_PRI,C,6': 'SEMANA EPDM',
    'DT_SIN_PRI,D': 'DATA PRIMEIROS SINTOMAS',
    'SOROTIPO,C,1': 'SOROTIPO'

},inplace=True)

In [84]:
df['DATA DE NASCIMENTO'] = pd.to_datetime(df['DATA DE NASCIMENTO'], format='%m/%d/%y', errors='coerce')

# Correcting years that are in the future (e.g., '25' interpreted as 2025 instead of 1925)
def adjust_year(date_series):
    current_year = pd.Timestamp.now().year
    adjusted_dates = []
    for date in date_series:
        if pd.isna(date):
            adjusted_dates.append(pd.NaT)
            continue
        if date.year > current_year:
            adjusted_dates.append(date - pd.DateOffset(years=100))
        else:
            adjusted_dates.append(date)
    return pd.Series(adjusted_dates, index=date_series.index)

df['DATA DE NASCIMENTO'] = adjust_year(df['DATA DE NASCIMENTO'])

# Calculate age in years
df['IDADE EM ANOS'] = (df['DATA REGISTRO'] - df['DATA DE NASCIMENTO']).dt.days / 365.25

# Round the age to the nearest integer
df['IDADE EM ANOS'] = df['IDADE EM ANOS'].round().astype('Int64')

In [85]:
df_final2018 = df[['IDADE EM ANOS', 'SEXO DO PACIENTE','RAÇA','ESTACAO POR CASO','MES DO CASO','GRAU ESCOLARIDADE','BAIRRO','ZONA','UNIDADE DE ATENDIMENTO','DATA REGISTRO', 'CLASS DOENCA','SEMANA EPDM', 'DATA PRIMEIROS SINTOMAS','SOROTIPO']]

In [86]:
df_final2018 = df_final2018[df_final2018['CLASS DOENCA'] != 'DESCARTADO']
df_final2018 = df_final2018[df_final2018['CLASS DOENCA'] != 'CHIKUNGUNYA']
df_final2018 = df_final2018[df_final2018['CLASS DOENCA'] != 8]

In [87]:
df_final2018['RAÇA'].replace('IGNORADO','PARDO',inplace=True)

/tmp/ipython-input-2590605241.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final2018['RAÇA'].replace('IGNORADO','PARDO',inplace=True)

In [88]:
df_final2018['ZONA'] = df_final2018['ZONA'].astype(str)
df_final2018['ZONA'] = df_final2018['ZONA'].replace({'nan': 'URBANA', '9.0': 'URBANA'})

In [89]:
df_final2018['SEMANA EPDM'] = df_final2018['SEMANA EPDM'].astype(str).str[-2:]

In [90]:
df_final2018['GRAU ESCOLARIDADE'].replace('IGNORADO','ENSINO MÉDIO COMPLETO',inplace=True)

/tmp/ipython-input-3923624455.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final2018['GRAU ESCOLARIDADE'].replace('IGNORADO','ENSINO MÉDIO COMPLETO',inplace=True)

In [91]:
df_final2018

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
0,28,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,SANTA ROSA,1.0,2363070,2018-04-02,DENGUE,13,03/28/18,NaN
2,13,HOMEM,PRETO,OUTONO,Abril,1 GRAU INCOMPLETO,CRUZEIRO,1.0,7113692,2018-04-30,DENGUE,16,04/20/18,NaN
5,44,MULHER,PARDO,OUTONO,Junho,NaN,MALVINAS,1.0,2362856,2018-06-28,DENGUE,24,06/16/18,NaN
6,8,HOMEM,PARDO,OUTONO,Junho,PRIMARIO INCOMPLETO,BODOCONGO,1.0,2362821,2018-06-21,DENGUE,25,06/17/18,NaN
7,37,MULHER,PARDO,OUTONO,Junho,1 GRAU INCOMPLETO,MALVINAS,1.0,2362880,2018-06-25,DENGUE,23,06/09/18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,37,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,SERROTAO,1.0,9374833,2018-08-01,DENGUE,31,08/01/18,NaN
921,8,HOMEM,PARDO,INVERNO,Julho,PRIMARIO INCOMPLETO,SAO JOSE DA MATA,2.0,7113692,2018-07-27,DENGUE,29,07/19/18,NaN
922,19,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,SAO JOSE DA MATA,1.0,2362287,2018-08-06,DENGUE,30,07/23/18,NaN
923,24,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,BODOCONGO,1.0,9374833,2018-08-12,DENGUE,32,08/08/18,NaN
924,21,HOMEM,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,LIBERDADE,1.0,2362856,2018-07-10,DENGUE C/ ALARME,26,06/24/18,NaN

In [92]:
np.unique(df_final2018['ZONA'].astype(str),return_counts=True)

(array(['1.0', '2.0', 'URBANA'], dtype=object), array([620,  20,   5]))

In [93]:
df_final2018['ZONA']=df_final2018['ZONA'].fillna('URBANA')

In [94]:
np.unique(df_final2018['UNIDADE DE ATENDIMENTO'])

array([2090589, 2362236, 2362287, 2362295, 2362317, 2362392, 2362406,
       2362678, 2362686, 2362767, 2362821, 2362848, 2362856, 2362880,
       2362953, 2363070, 2400243, 2595389, 2595397, 2595419, 2595427,
       2617293, 2676060, 2677733, 2757702, 2792745, 2792869, 3006204,
       3708926, 5053285, 5116457, 5968992, 6267939, 6940315, 7052251,
       7113692, 9352910, 9374833])

In [95]:

unidades = {
    # --- Campina Grande (Rede Própria e Conveniada) ---
    220337:  "HOSPITAL DE CLINICAS DE CAMPINA GRANDE",
    2343207: "LABORATORIO CLINICO DA PARAIBA (PRIVADO)",
    2362201: "UBS SAO JOSE DA MATA",
    2362236: "CENTRO DE SAUDE DE BODOCONGO",
    2362244: "CENTRO DE SAUDE DO CATOLE",
    2362287: "INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA",
    2362295: "SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE",
    2362317: "CENTRO DE SAUDE DA LIBERDADE",
    2362392: "CENTRO DE SAUDE FRANCISCO PINTO",
    2362406: "CENTRO DE SAUDE DA BELA VISTA",
    2362678: "CENTRO DE ESPECIALIDADES ODONTOLOGICAS CEO",
    2362686: "CAPS II (SAUDE MENTAL)",
    2362694: "CAPS III (REVIVER)",
    2362767: "APAE CAMPINA GRANDE",
    2362821: "HEMOCENTRO REGIONAL DE CAMPINA GRANDE",
    2362848: "HOSPITAL MUNICIPAL DR JOAO RIBEIRO (GALANTE)",
    2362856: "HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES",
    2362880: "HOSPITAL MUNICIPAL DR EDGLEY",
    2362953: "BANCO DE LEITE HUMANO DR VIRGILIO BRASILEIRO",
    2363070: "HOSPITAL MUNICIPAL PEDRO I",
    2363275: "VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE",
    2595389: "UBS MARIA DE LOURDES LEONE",
    2595397: "UBS ROMULO GOUVEIA",
    2595419: "UBS MALVINAS V",
    2595427: "UBS RAMADINHA I",
    2676060: "HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO",
    2792745: "UBS SAO JOSE",
    2792869: "UBS SANTA ROSA",
    3006204: "CLINICA SANTA CLARA",
    3056724: "CLINICA ULTRA DIAGNOSTICO (PRIVADO)",
    4015673: "UBS GLORIA I",
    5053250: "UBS VELAME",
    5053285: "UBS NOVO HORIZONTE",
    5116457: "UBS BAIRRO DAS CIDADES",
    5968976: "UBS JARDIM PAULISTANO",
    5968992: "UBS SANTA ROSA I E II",
    6267939: "CENTRO DE GENETICA MEDICA",
    7052251: "UPA 24 HORAS DR MAIA (ALTO BRANCO)",
    7113692: "HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO",
    9374833: "UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA)",

    # --- Externos (Paraíba - Outros Municípios) ---
    2400243: "INSTITUTO CANDIDA VARGAS (JOAO PESSOA)",
    2617293: "UBSF MARIA MARQUES (PATOS)",
    2677733: "SVO - SERVICO DE VERIFICACAO DE OBITO (JOAO PESSOA)",
    2757702: "UNIDADE MISTA DE SAUDE (TAPEROA)",
    3562212: "HOSPITAL MEMORIAL SAO FRANCISCO (JOAO PESSOA)",
    3708926: "HOSPITAL REGIONAL DE PATOS (PATOS)",
    6443370: "UPA 24H ALHANDRA (ALHANDRA)",
    6613136: "UPA 24H QUEIMADAS (QUEIMADAS)",
    6940315: "UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)",
    7182686: "UPA 24H SOUSA (SOUSA)",
    9352910: "UPA 24H MANGABEIRA (JOAO PESSOA)",

    # --- Externos (Pernambuco - Recife) ---
    2090589: "HOSPITAL SANTA JOANA (RECIFE-PE)",
    2315793: "REAL HOSPITAL PORTUGUES (RECIFE-PE)",
    2427419: "HOSPITAL DA RESTAURACAO (RECIFE-PE)",

    # --- Erros / Indefinidos ---
    434: "CODIGO INVALIDO (ERRO DE REGISTRO)"
}

# 2. Lista apenas com os IDs de Campina Grande (Cód Mun 250400)
ids_campina_grande = [
    220337, 2343207, 2362201, 2362236, 2362244, 2362287, 2362295,
    2362317, 2362392, 2362406, 2362678, 2362686, 2362694, 2362767,
    2362821, 2362848, 2362856, 2362880, 2362953, 2363070, 2363275,
    2595389, 2595397, 2595419, 2595427, 2676060, 2792745, 2792869,
    3006204, 3056724, 4015673, 5053250, 5053285, 5116457, 5968976,
    5968992, 6267939, 7052251, 7113692, 9374833
]

# --- APLICAÇÃO NO DATAFRAME ---

# (Opcional) Converter para numérico
# df_final2023['UNIDADE DE ATENDIMENTO'] = pd.to_numeric(df_final2023['UNIDADE DE ATENDIMENTO'], errors='coerce')

# 1. Cria a coluna de Classificação (Interno/Externo)
df_final2018['ORIGEM_UNIDADE'] = np.where(
    df_final2018['UNIDADE DE ATENDIMENTO'].isin(ids_campina_grande),
    'Campina Grande',
    'Externo/Outro'
)

# 2. Substitui os códigos pelos nomes
df_final2018['UNIDADE DE ATENDIMENTO'] = df_final2018['UNIDADE DE ATENDIMENTO'].replace(unidades)

In [96]:
df_final2018

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,28,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,SANTA ROSA,1.0,HOSPITAL MUNICIPAL PEDRO I,2018-04-02,DENGUE,13,03/28/18,NaN,Campina Grande
2,13,HOMEM,PRETO,OUTONO,Abril,1 GRAU INCOMPLETO,CRUZEIRO,1.0,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2018-04-30,DENGUE,16,04/20/18,NaN,Campina Grande
5,44,MULHER,PARDO,OUTONO,Junho,NaN,MALVINAS,1.0,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2018-06-28,DENGUE,24,06/16/18,NaN,Campina Grande
6,8,HOMEM,PARDO,OUTONO,Junho,PRIMARIO INCOMPLETO,BODOCONGO,1.0,HEMOCENTRO REGIONAL DE CAMPINA GRANDE,2018-06-21,DENGUE,25,06/17/18,NaN,Campina Grande
7,37,MULHER,PARDO,OUTONO,Junho,1 GRAU INCOMPLETO,MALVINAS,1.0,HOSPITAL MUNICIPAL DR EDGLEY,2018-06-25,DENGUE,23,06/09/18,NaN,Campina Grande
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,37,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,SERROTAO,1.0,UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA),2018-08-01,DENGUE,31,08/01/18,NaN,Campina Grande
921,8,HOMEM,PARDO,INVERNO,Julho,PRIMARIO INCOMPLETO,SAO JOSE DA MATA,2.0,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2018-07-27,DENGUE,29,07/19/18,NaN,Campina Grande
922,19,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,SAO JOSE DA MATA,1.0,INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA,2018-08-06,DENGUE,30,07/23/18,NaN,Campina Grande
923,24,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,BODOCONGO,1.0,UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA),2018-08-12,DENGUE,32,08/08/18,NaN,Campina Grande
924,21,HOMEM,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,LIBERDADE,1.0,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2018-07-10,DENGUE C/ ALARME,26,06/24/18,NaN,Campina Grande

In [97]:
np.unique(df_final2018['GRAU ESCOLARIDADE'].astype(str),return_counts=True)

(array(['1 GRAU INCOMPLETO', 'ANALFABETO', 'ENSINO MÉDIO COMPLETO',
        'ENSINO MÉDIO INCOMPLETO', 'FUNDAMENTAL COMPLETO', 'NÃO SE APLICA',
        'PRIMARIO COMPLETO', 'PRIMARIO INCOMPLETO', 'SUPERIOR COMPLETO',
        'SUPERIOR INCOMPLETO', 'nan'], dtype=object),
 array([ 48,   5, 192,  85,  17,  72,  41,  80,  57,  26,  22]))

In [98]:
df_final2018['GRAU ESCOLARIDADE'].value_counts()

GRAU ESCOLARIDADE
ENSINO MÉDIO COMPLETO      192
ENSINO MÉDIO INCOMPLETO     85
PRIMARIO INCOMPLETO         80
NÃO SE APLICA               72
SUPERIOR COMPLETO           57
1 GRAU INCOMPLETO           48
PRIMARIO COMPLETO           41
SUPERIOR INCOMPLETO         26
FUNDAMENTAL COMPLETO        17
ANALFABETO                   5
Name: count, dtype: int64

In [99]:
df_final2018['DATA REGISTRO'] = df_final2018['DATA REGISTRO'].dt.year

In [100]:
zonas={
    '1.0': 'URBANA',
    '2.0': 'RURAL',
    '3.0': 'PERIURBANA'
}
df_final2018['ZONA']=df_final2018['ZONA'].replace(zonas)
df_final2018['ZONA']=df_final2018['ZONA'].replace('nan','URBANA')

In [101]:
df_final2018

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
0,28,HOMEM,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,SANTA ROSA,URBANA,HOSPITAL MUNICIPAL PEDRO I,2018,DENGUE,13,03/28/18,NaN,Campina Grande
2,13,HOMEM,PRETO,OUTONO,Abril,1 GRAU INCOMPLETO,CRUZEIRO,URBANA,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2018,DENGUE,16,04/20/18,NaN,Campina Grande
5,44,MULHER,PARDO,OUTONO,Junho,NaN,MALVINAS,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2018,DENGUE,24,06/16/18,NaN,Campina Grande
6,8,HOMEM,PARDO,OUTONO,Junho,PRIMARIO INCOMPLETO,BODOCONGO,URBANA,HEMOCENTRO REGIONAL DE CAMPINA GRANDE,2018,DENGUE,25,06/17/18,NaN,Campina Grande
7,37,MULHER,PARDO,OUTONO,Junho,1 GRAU INCOMPLETO,MALVINAS,URBANA,HOSPITAL MUNICIPAL DR EDGLEY,2018,DENGUE,23,06/09/18,NaN,Campina Grande
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,37,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,SERROTAO,URBANA,UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA),2018,DENGUE,31,08/01/18,NaN,Campina Grande
921,8,HOMEM,PARDO,INVERNO,Julho,PRIMARIO INCOMPLETO,SAO JOSE DA MATA,RURAL,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2018,DENGUE,29,07/19/18,NaN,Campina Grande
922,19,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,SAO JOSE DA MATA,URBANA,INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA,2018,DENGUE,30,07/23/18,NaN,Campina Grande
923,24,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,BODOCONGO,URBANA,UPA 24 HORAS DR ADHEMAR DANTAS (DINAMERICA),2018,DENGUE,32,08/08/18,NaN,Campina Grande
924,21,HOMEM,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,LIBERDADE,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2018,DENGUE C/ ALARME,26,06/24/18,NaN,Campina Grande

In [102]:
df_final2018.shape

(645, 15)

In [103]:
df_final2018['CLASS DOENCA'].value_counts()

CLASS DOENCA
DENGUE              608
DENGUE C/ ALARME     33
DENGUE GRAVE          4
Name: count, dtype: int64

In [104]:
df_final2018['ZONA'].info

<bound method Series.info of 0      URBANA
2      URBANA
5      URBANA
6      URBANA
7      URBANA
        ...
919    URBANA
921     RURAL
922    URBANA
923    URBANA
924    URBANA
Name: ZONA, Length: 645, dtype: object>

In [105]:
df_final2018['GRAU ESCOLARIDADE'].fillna('ENSINO MÉDIO COMPLETO',inplace=True)

/tmp/ipython-input-3681841567.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final2018['GRAU ESCOLARIDADE'].fillna('ENSINO MÉDIO COMPLETO',inplace=True)

In [106]:
df_final2018.to_csv('dengue2018_tratado.csv',index=False)