In [86]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.express as plx
import matplotlib.pyplot as plt

In [87]:
df = pd.read_csv('/content/drive/MyDrive/Projetos/Pivic/dados/Dados/epidemiologia dengue cg/AnyConv.com__2021_SI_DENGON2642316_00.csv')
pd.set_option('display.max_columns', None)
df.head()

,"NU_NOTIFIC,C,7","TP_NOT,C,1","ID_AGRAVO,C,5","DT_NOTIFIC,D","SEM_NOT,C,6","NU_ANO,C,4","SG_UF_NOT,C,2","ID_MUNICIP,C,6","ID_REGIONA,C,8","ID_UNIDADE,C,7","DT_SIN_PRI,D","SEM_PRI,C,6","DT_NASC,D","SOUNDEX,C,70","NU_IDADE_N,N,4,0","CS_SEXO,C,1","CS_GESTANT,C,1","CS_RACA,C,1","CS_ESCOL_N,C,2","SG_UF,C,2","ID_MN_RESI,C,6","ID_RG_RESI,C,8","ID_DISTRIT,C,9","ID_BAIRRO,C,8","NM_BAIRRO,C,60","ID_GEO1,C,8","ID_GEO2,C,8","CS_ZONA,C,1","ID_PAIS,C,4","DT_INVEST,D","ID_OCUPA_N,C,6","FEBRE,C,1","MIALGIA,C,1","CEFALEIA,C,1","EXANTEMA,C,1","VOMITO,C,1","NAUSEA,C,1","DOR_COSTAS,C,1","CONJUNTVIT,C,1","ARTRITE,C,1","ARTRALGIA,C,1","PETEQUIA_N,C,1","LEUCOPENIA,C,1","LACO,C,1","DOR_RETRO,C,1","DIABETES,C,1","HEMATOLOG,C,1","HEPATOPAT,C,1","RENAL,C,1","HIPERTENSA,C,1","ACIDO_PEPT,C,1","AUTO_IMUNE,C,1","DT_CHIK_S1,D","DT_CHIK_S2,D","DT_PRNT,D","RES_CHIKS1,C,1","RES_CHIKS2,C,1","RESUL_PRNT,C,1","DT_SORO,D","RESUL_SORO,C,1","DT_NS1,D","RESUL_NS1,C,1","DT_VIRAL,D","RESUL_VI_N,C,1","DT_PCR,D","RESUL_PCR_,C,1","SOROTIPO,C,1","HISTOPA_N,C,1","IMUNOH_N,C,1","HOSPITALIZ,C,1","DT_INTERNA,D","UF,C,2","MUNICIPIO,C,6","HOSPITAL,C,7","DDD_HOSP,C,2","TEL_HOSP,C,9","TPAUTOCTO,C,1","COUFINF,C,2","COPAISINF,C,4","COMUNINF,C,6","CODISINF,C,4","CO_BAINF,C,8","NOBAIINF,C,60","CLASSI_FIN,C,2","CRITERIO,C,1","DOENCA_TRA,C,1","CLINC_CHIK,C,1","EVOLUCAO,C,1","DT_OBITO,D","DT_ENCERRA,D","ALRM_HIPOT,C,1","ALRM_PLAQ,C,1","ALRM_VOM,C,1","ALRM_SANG,C,1","ALRM_HEMAT,C,1","ALRM_ABDOM,C,1","ALRM_LETAR,C,1","ALRM_HEPAT,C,1","ALRM_LIQ,C,1","DT_ALRM,D","GRAV_PULSO,C,1","GRAV_CONV,C,1","GRAV_ENCH,C,1","GRAV_INSUF,C,1","GRAV_TAQUI,C,1","GRAV_EXTRE,C,1","GRAV_HIPOT,C,1","GRAV_HEMAT,C,1","GRAV_MELEN,C,1","GRAV_METRO,C,1","GRAV_SANG,C,1","GRAV_AST,C,1","GRAV_MIOC,C,1","GRAV_CONSC,C,1","GRAV_ORGAO,C,1","DT_GRAV,D","MANI_HEMOR,C,1","EPISTAXE,C,1","GENGIVO,C,1","METRO,C,1","PETEQUIAS,C,1","HEMATURA,C,1","SANGRAM,C,1","LACO_N,C,1","PLASMATICO,C,1","EVIDENCIA,C,1","PLAQ_MENOR,C,7","CON_FHD,C,1","COMPLICA,C,1","NU_LOTE_I,C,9","DS_OBS,C,255","TP_SISTEMA,C,1","NDUPLIC_N,C,1","DT_DIGITA,D","DT_TRANSUS,D","DT_TRANSDM,D","DT_TRANSSM,D","DT_TRANSRM,D","DT_TRANSRS,D","DT_TRANSSE,D","NU_LOTE_V,C,7","NU_LOTE_H,C,7","CS_FLXRET,C,1","FLXRECEBI,C,7","IDENT_MICR,C,50","MIGRADO_W,C,1"
0,8651937,2,A90,09/16/21,202137,2021,35,355030,1331.0,248991,09/14/21,202137,11/13/82,NaN,4038,M,6,9,9.0,25,250400,1421,NaN,40.0,PRATA,NaN,NaN,1.0,1,09/16/21,998999,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,11/16/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"EXAMES SOLICITADOS: DENGUE, NS1, SOROLOGIA IGM...",2,NaN,09/16/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN
1,7241208,2,A90,06/18/21,202124,2021,35,355030,1331.0,248991,06/14/21,202124,06/16/73,NaN,4047,F,5,9,NaN,25,250400,1421,NaN,32.0,MIRANTE,NaN,NaN,NaN,1,06/18/21,NaN,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,08/18/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"EXAMES SOLICITADOS: DENGUE,ANT═GENO NS1, SORO,...",2,NaN,06/22/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN
2,7358375,2,A90,05/31/21,202122,2021,35,355030,1331.0,248991,05/26/21,202121,04/19/14,NaN,4007,M,6,9,10.0,25,250400,1421,NaN,609.0,SANDRA CAVALCANTE,NaN,NaN,NaN,1,05/31/21,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,07/31/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"EXAMES SOLICITADOS: DENGUE,ANT═GENO NS1,SORO. ...",2,NaN,06/02/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN
3,7016773,2,A90,04/04/21,202114,2021,35,354980,1354.0,2052474,04/02/21,202113,01/15/67,NaN,4054,F,5,1,6.0,25,250400,1421,NaN,1.0,CENTRO,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,06/04/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,04/16/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,4,NaN
4,1678341,2,A90,01/01/21,202053,2021,24,240810,1416.0,7408765,12/30/20,202053,06/03/95,NaN,4025,F,9,9,9.0,25,250400,1421,NaN,603.0,MALVINAS,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,03/03/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,01/07/21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,7,NaN

In [88]:
classificacao={
    5: 'DESCARTADO',
    10: 'DENGUE',
    11: 'DENGUE C/ ALARME',
    12: 'DENGUE GRAVE',
    13: 'CHIKUNGUNYA'
}
df['CLASSI_FIN,C,2']=df['CLASSI_FIN,C,2'].replace(classificacao)

In [89]:
np.unique(df['CS_RACA,C,1'],return_counts=True)

(array([1, 2, 3, 4, 9]), array([ 24,   7,   1, 226,  14]))

In [90]:
df.shape

(272, 146)

In [91]:
df=df.dropna(axis=1,how='all')

In [92]:
df.shape

(272, 99)

In [93]:
df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace({
    1: 'BRANCO',
    2: 'PRETO',
    3: 'AMARELO',
    4: 'PARDO',
    5: 'INDIGENA',
    9: 'IGNORADO'
})
# Correcting the problematic assignment from qZsae-tpZGZL here
df['CS_RACA,C,1'] = df['CS_RACA,C,1'].replace('IGNORADO','PARDO')

generos={
    'M': 'HOMEM',
    'F': 'MULHER'
}
df['CS_SEXO,C,1']=df['CS_SEXO,C,1'].replace(generos)


escolaridade={
    0: 'ANALFABETO',
    1: 'PRIMARIO INCOMPLETO',
    2: 'PRIMARIO COMPLETO',
    3: '1 GRAU INCOMPLETO',
    4: 'FUNDAMENTAL COMPLETO',
    5: 'ENSINO MÉDIO INCOMPLETO',
    6: 'ENSINO MÉDIO COMPLETO',
    7: 'SUPERIOR INCOMPLETO',
    8: 'SUPERIOR COMPLETO',
    9: 'IGNORADO',
    10: 'NÃO SE APLICA'
}
df['CS_ESCOL_N,C,2']=df['CS_ESCOL_N,C,2'].replace(escolaridade)

In [94]:
np.unique(df['CS_RACA,C,1'].astype(str),return_counts=True)

(array(['AMARELO', 'BRANCO', 'PARDO', 'PRETO'], dtype=object),
 array([  1,  24, 240,   7]))

In [95]:
np.unique(df['CS_RACA,C,1'].astype(str),return_counts=True)

(array(['AMARELO', 'BRANCO', 'PARDO', 'PRETO'], dtype=object),
 array([  1,  24, 240,   7]))

In [96]:
# This cell was causing the error and its logic has been moved to 'vrtEchcSY5Ui'.

In [97]:
np.unique(df['CS_SEXO,C,1'].astype(str), return_counts= True)

(array(['HOMEM', 'MULHER'], dtype=object), array([ 97, 175]))

In [98]:
df['DT_NOTIFIC,D'] = pd.to_datetime(df['DT_NOTIFIC,D'], format='%m/%d/%y')
df['MES DO CASO'] = df['DT_NOTIFIC,D'].dt.month

In [99]:
meses = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
df['MES DO CASO'] = df['MES DO CASO'].replace(meses)

In [100]:
estacoes_por_mes={
    'Dezembro' : 'VERAO',
    'Janeiro': 'VERAO',
    'Fevereiro': 'VERAO',
    'Março': 'VERAO',
    'Abril': 'OUTONO',
    'Maio': 'OUTONO',
    'Junho': 'OUTONO',
    'Julho': 'INVERNO',
    'Agosto': 'INVERNO',
    'Setembro': 'INVERNO',
    'Outubro': 'PRIMAVERA',
    'Novembro': 'PRIMAVERA'
}
df['ESTACAO POR CASO']=df['MES DO CASO'].replace(estacoes_por_mes)

In [101]:
df.rename(columns={
    'DT_NOTIFIC,D': 'DATA REGISTRO',
    'CS_SEXO,C,1': 'SEXO DO PACIENTE',
    'CS_RACA,C,1': 'RAÇA',
    'CS_ESCOL_N,C,2': 'GRAU ESCOLARIDADE',
    'NM_BAIRRO,C,60': 'BAIRRO',
    'CS_ZONA,C,1': 'ZONA',
    'ID_UNIDADE,C,7': 'UNIDADE DE ATENDIMENTO',
    'DT_NASC,D': 'DATA DE NASCIMENTO',
    'CLASSI_FIN,C,2': 'CLASS DOENCA',
    'SEM_PRI,C,6': 'SEMANA EPDM',
    'DT_SIN_PRI,D': 'DATA PRIMEIROS SINTOMAS',
    'SOROTIPO,C,1': 'SOROTIPO'

},inplace=True)

In [102]:
np.unique(df['BAIRRO'].astype(str),return_counts=True)

(array(['ACACIO FIGUEIREDO', 'ALAMEDA', 'ALTO BRANCO', 'ALUISIO CAMPOS',
        'ARAXA', 'BAIRRO DAS CIDADES', 'BAIRRO DAS NACOES',
        'BAIRRO UNIVERSITARIO', 'BELA VISTA', 'BODOCONGO', 'BODOCONGO III',
        'BR 104 KM 119', 'CAMPINA GRANDE', 'CATOLE', 'CENTENARIO',
        'CENTRO', 'CIDADES', 'CINZA', 'CONJ SEVERINO CABRAL', 'CRUZEIRO',
        'CUITES', 'DINAMERICA', 'GALANTE', 'ITARARE', 'JARDIM PAULISTANO',
        'JARDIM QUARENTA', 'JARDIM TAVARES', 'JEREMIAS', 'JOSE PINHEIRO',
        'LAGOA DE DENTRO', 'LIBERDADE', 'LIGEIRO', 'LOUZEIRO', 'MALVINAS',
        'MIRANTE', 'MONTE CASTELO', 'MONTE SANTO', 'NOVA BRASILIA',
        'NOVO CRUZEIRO', 'NOVO HORIZONTE', 'PALMEIRA', 'PEDREGAL',
        'PORTAL SUDOESTE', 'PRATA', 'PRESIDENTE MEDICE', 'QUARENTA',
        'RAMADINHA', 'ROCHA CAVALCANTE', 'SANDRA CAVALCANTE', 'SANTA CRUZ',
        'SANTA ROSA', 'SANTA TEREZINHA', 'SANTA TREZINHA', 'SANTO ANTONIO',
        'SAO JOSE DA MATA', 'SERROTAO', 'SÒO JOSÚ', 'TAMBOR',
        'TRES IRMAES', 'TRES IRMAS', 'TRÛS IRMAS', 'VELAME', 'VILA CABRAL',
        'nan'], dtype=object),
 array([ 1,  1,  4,  1,  1,  1,  1,  2,  3, 21,  1,  1,  1, 12,  2, 10,  1,
         1,  1, 10,  1,  4,  2,  2,  4,  2,  2,  4,  8,  1, 15,  2,  1, 39,
         3,  6,  1,  4,  2,  1,  2,  2,  1,  5,  5,  1, 11,  2,  3,  1, 13,
         2,  1,  2,  1,  6,  1,  3, 10,  1,  2,  2,  7,  8]))

In [103]:
bairros={
    'ALUISIO CAMPOS': 'ALUIZIO CAMPOS',
    'BAIRRO DAS NACOES': 'NACOES',
    'BODOCONGO III': 'NOVO BODOCONGO',
    'CIDADES': 'BAIRRO DAS CIDADES',
    'NOVO CRUZEIRO': 'CRUZEIRO',
    'QUARENTA': 'JARDIM QUARENTA',
    'SÒO JOSÚ': 'SAO JOSE',
    'TRÛS IRMAS': 'TRES IRMAS',
    'BR 104 KM 119': 'JURACY PALHANO'
}

In [104]:
df['DATA DE NASCIMENTO'] = pd.to_datetime(df['DATA DE NASCIMENTO'], format='%m/%d/%y', errors='coerce')

# Correcting years that are in the future (e.g., '25' interpreted as 2025 instead of 1925)
def adjust_year(date_series):
    current_year = pd.Timestamp.now().year
    adjusted_dates = []
    for date in date_series:
        if pd.isna(date):
            adjusted_dates.append(pd.NaT)
            continue
        if date.year > current_year:
            adjusted_dates.append(date - pd.DateOffset(years=100))
        else:
            adjusted_dates.append(date)
    return pd.Series(adjusted_dates, index=date_series.index)

df['DATA DE NASCIMENTO'] = adjust_year(df['DATA DE NASCIMENTO'])

# Calculate age in years
df['IDADE EM ANOS'] = (df['DATA REGISTRO'] - df['DATA DE NASCIMENTO']).dt.days / 365.25

# Round the age to the nearest integer
df['IDADE EM ANOS'] = df['IDADE EM ANOS'].round().astype('Int64')

In [105]:
df_final2021 = df[['IDADE EM ANOS', 'SEXO DO PACIENTE','RAÇA','ESTACAO POR CASO','MES DO CASO','GRAU ESCOLARIDADE','BAIRRO','ZONA','UNIDADE DE ATENDIMENTO','DATA REGISTRO', 'CLASS DOENCA','SEMANA EPDM', 'DATA PRIMEIROS SINTOMAS','SOROTIPO']]

In [106]:
df_final2021 = df_final2021[df_final2021['CLASS DOENCA'] != 'DESCARTADO']
df_final2021 = df_final2021[df_final2021['CLASS DOENCA'] != 'CHIKUNGUNYA']
df_final2021 = df_final2021[df_final2021['CLASS DOENCA'] != 8]

In [107]:
df_final2021['DATA REGISTRO'] = df_final2021['DATA REGISTRO'].dt.year

In [108]:
df_final2021['SEMANA EPDM'] = df_final2021['SEMANA EPDM'].astype(str).str[-2:]

In [109]:
df_final2021['GRAU ESCOLARIDADE'].replace('IGNORADO','ENSINO MÉDIO COMPLETO',inplace=True)

/tmp/ipython-input-2119922578.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [110]:
df_final2021['RAÇA'].replace('IGNORADO','PARDO',inplace=True)

/tmp/ipython-input-1771655403.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [111]:
df_final2021

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
10,39,MULHER,PARDO,VERAO,Fevereiro,ENSINO MÉDIO COMPLETO,MONTE SANTO,1.0,2362295,2021,DENGUE,06,02/10/21,NaN
12,25,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,NaN,1.0,2362856,2021,DENGUE,02,01/12/21,NaN
28,52,MULHER,BRANCO,INVERNO,Julho,PRIMARIO COMPLETO,BODOCONGO,1.0,2363275,2021,DENGUE,27,07/09/21,NaN
33,32,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO INCOMPLETO,RAMADINHA,1.0,2363275,2021,DENGUE,28,07/14/21,NaN
34,36,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,CENTRO,1.0,2676060,2021,DENGUE,32,08/08/21,NaN
36,28,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,NOVA BRASILIA,1.0,2676060,2021,DENGUE,28,07/14/21,NaN
41,59,MULHER,PARDO,VERAO,Fevereiro,ENSINO MÉDIO COMPLETO,BODOCONGO,1.0,2595400,2021,DENGUE,06,02/08/21,NaN
51,43,HOMEM,PARDO,VERAO,Março,FUNDAMENTAL COMPLETO,ALTO BRANCO,1.0,2676060,2021,DENGUE C/ ALARME,08,02/25/21,NaN
52,26,MULHER,PARDO,VERAO,Fevereiro,SUPERIOR COMPLETO,RAMADINHA,1.0,2362295,2021,DENGUE,06,02/12/21,NaN
58,25,MULHER,PRETO,VERAO,Março,ENSINO MÉDIO INCOMPLETO,MONTE CASTELO,1.0,2363275,2021,DENGUE,10,03/08/21,NaN
64,6,HOMEM,PARDO,OUTONO,Junho,NÃO SE APLICA,VILA CABRAL,1.0,7113692,2021,DENGUE,22,05/31/21,NaN
66,35,MULHER,BRANCO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,TRES IRMAES,1.0,2363275,2021,DENGUE,26,06/29/21,NaN
71,69,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,LOUZEIRO,1.0,2363275,2021,DENGUE,19,05/14/21,NaN
75,14,HOMEM,PARDO,INVERNO,Julho,1 GRAU INCOMPLETO,NOVO HORIZONTE,1.0,7113692,2021,DENGUE,28,07/14/21,NaN
78,32,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,GALANTE,1.0,7052251,2021,DENGUE,18,05/02/21,NaN
83,33,MULHER,BRANCO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,NaN,1.0,2362856,2021,DENGUE,25,06/22/21,NaN
86,10,MULHER,PARDO,INVERNO,Agosto,1 GRAU INCOMPLETO,VELAME,1.0,2363275,2021,DENGUE,32,08/11/21,NaN
88,27,MULHER,PARDO,INVERNO,Julho,SUPERIOR COMPLETO,CATOLE,1.0,2362856,2021,DENGUE,28,07/11/21,NaN
89,56,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,BODOCONGO,1.0,2363275,2021,DENGUE,30,07/28/21,NaN
93,31,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,CRUZEIRO,1.0,2363275,2021,DENGUE,25,06/20/21,NaN
94,44,MULHER,PARDO,INVERNO,Julho,SUPERIOR COMPLETO,MALVINAS,1.0,2363275,2021,DENGUE,28,07/11/21,NaN
97,34,MULHER,PARDO,OUTONO,Junho,SUPERIOR COMPLETO,CENTRO,1.0,2363275,2021,DENGUE,21,05/23/21,NaN
99,31,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,LIGEIRO,1.0,7052251,2021,DENGUE,18,05/02/21,NaN
103,73,HOMEM,PARDO,OUTONO,Junho,PRIMARIO COMPLETO,LIBERDADE,1.0,2676060,2021,DENGUE,23,06/12/21,NaN
105,77,MULHER,PARDO,PRIMAVERA,Novembro,SUPERIOR COMPLETO,CATOLE,1.0,3006204,2021,DENGUE,43,10/25/21,NaN
108,12,HOMEM,PARDO,PRIMAVERA,Outubro,1 GRAU INCOMPLETO,CENTENARIO,1.0,2363275,2021,DENGUE,38,09/22/21,NaN
109,24,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,MONTE CASTELO,1.0,2363275,2021,DENGUE,39,09/30/21,NaN
110,0,MULHER,PARDO,PRIMAVERA,Novembro,NÃO SE APLICA,VILA CABRAL,1.0,7113692,2021,DENGUE,46,11/20/21,NaN
117,4,HOMEM,PARDO,VERAO,Dezembro,NÃO SE APLICA,PRATA,1.0,2362856,2021,DENGUE,50,12/17/21,NaN
121,57,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,CRUZEIRO,1.0,2676060,2021,DENGUE,19,05/15/21,NaN
126,35,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,MALVINAS,1.0,2676060,2021,DENGUE,21,05/25/21,NaN
128,57,HOMEM,PARDO,OUTONO,Junho,SUPERIOR COMPLETO,SANTA ROSA,1.0,2676060,2021,DENGUE,25,06/21/21,NaN
135,44,MULHER,PRETO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,MONTE CASTELO,1.0,2595443,2021,DENGUE,37,09/14/21,NaN
137,59,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,CENTRO,1.0,2676060,2021,DENGUE,24,06/17/21,NaN
143,65,HOMEM,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,MALVINAS,1.0,2363275,2021,DENGUE,20,05/16/21,NaN
144,7,HOMEM,PARDO,INVERNO,Julho,NÃO SE APLICA,NOVO CRUZEIRO,1.0,2363275,2021,DENGUE,28,07/14/21,NaN
146,10,MULHER,PARDO,INVERNO,Julho,PRIMARIO INCOMPLETO,CRUZEIRO,1.0,2363275,2021,DENGUE,26,07/02/21,NaN
147,38,HOMEM,PARDO,OUTONO,Junho,PRIMARIO INCOMPLETO,GALANTE,1.0,2363275,2021,DENGUE,25,06/20/21,NaN
150,47,HOMEM,BRANCO,PRIMAVERA,Novembro,PRIMARIO INCOMPLETO,JARDIM PAULISTANO,1.0,2363070,2021,DENGUE,47,11/22/21,NaN
157,14,MULHER,PARDO,INVERNO,Julho,1 GRAU INCOMPLETO,TAMBOR,1.0,2363275,2021,DENGUE,28,07/15/21,NaN
158,54,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,MALVINAS,1.0,2363275,2021,DENGUE,27,07/07/21,NaN
160,9,HOMEM,BRANCO,OUTONO,Maio,PRIMARIO INCOMPLETO,JEREMIAS,1.0,7113692,2021,DENGUE,20,05/16/21,NaN
165,17,HOMEM,PARDO,INVERNO,Agosto,FUNDAMENTAL COMPLETO,TRES IRMAES,1.0,2676060,2021,DENGUE,29,07/21/21,NaN
171,48,HOMEM,PARDO,INVERNO,Agosto,SUPERIOR COMPLETO,CENTRO,1.0,2363275,2021,DENGUE,33,08/19/21,NaN
174,38,HOMEM,PARDO,INVERNO,Julho,NaN,SANTA ROSA,1.0,2362856,2021,DENGUE,29,07/21/21,NaN
191,63,MULHER,PARDO,PRIMAVERA,Novembro,NaN,LAGOA DE DENTRO,1.0,2362856,2021,DENGUE,46,11/14/21,NaN
212,66,MULHER,PARDO,PRIMAVERA,Outubro,SUPERIOR INCOMPLETO,BODOCONGO,1.0,2676060,2021,DENGUE,39,10/01/21,NaN
213,61,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,MALVINAS,1.0,2363275,2021,DENGUE,29,07/21/21,NaN
216,54,MULHER,PARDO,INVERNO,Agosto,PRIMARIO INCOMPLETO,PRATA,1.0,3006204,2021,DENGUE,29,07/22/21,NaN
218,80,HOMEM,BRANCO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,BAIRRO DAS NACOES,1.0,3006204,2021,DENGUE,31,08/01/21,NaN
228,50,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,TAMBOR,1.0,2363275,2021,DENGUE,34,08/23/21,NaN
236,66,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,BODOCONGO,1.0,2676060,2021,DENGUE,39,10/02/21,2.0
253,64,MULHER,PARDO,VERAO,Dezembro,ANALFABETO,BODOCONGO,1.0,2363275,2021,DENGUE,49,12/07/21,NaN
256,50,MULHER,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,CATOLE,1.0,2607336,2021,DENGUE,14,04/08/21,NaN
267,32,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,1.0,2399989,2021,DENGUE,03,01/22/21,NaN
268,19,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,VILA CABRAL,1.0,6940315,2021,DENGUE,36,09/09/21,NaN
269,19,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,VILA CABRAL,NaN,6940315,2021,DENGUE,33,08/15/21,NaN
270,20,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,VILA CABRAL,1.0,6940315,2021,DENGUE,36,09/10/21,NaN
271,49,HOMEM,PARDO,INVERNO,Setembro,SUPERIOR COMPLETO,ACACIO FIGUEIREDO,1.0,7646526,2021,DENGUE,37,09/16/21,NaN

In [112]:
zonas={
    1: 'URBANA',
    2: 'RURAL',
    3: 'PERIURBANA'
}
df_final2021['ZONA']=df_final2021['ZONA'].replace(zonas)
df_final2021['ZONA']=df_final2021['ZONA'].replace('nan','URBANA')

In [113]:
df_final2021

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO
10,39,MULHER,PARDO,VERAO,Fevereiro,ENSINO MÉDIO COMPLETO,MONTE SANTO,URBANA,2362295,2021,DENGUE,06,02/10/21,NaN
12,25,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,NaN,URBANA,2362856,2021,DENGUE,02,01/12/21,NaN
28,52,MULHER,BRANCO,INVERNO,Julho,PRIMARIO COMPLETO,BODOCONGO,URBANA,2363275,2021,DENGUE,27,07/09/21,NaN
33,32,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO INCOMPLETO,RAMADINHA,URBANA,2363275,2021,DENGUE,28,07/14/21,NaN
34,36,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,CENTRO,URBANA,2676060,2021,DENGUE,32,08/08/21,NaN
36,28,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,NOVA BRASILIA,URBANA,2676060,2021,DENGUE,28,07/14/21,NaN
41,59,MULHER,PARDO,VERAO,Fevereiro,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,2595400,2021,DENGUE,06,02/08/21,NaN
51,43,HOMEM,PARDO,VERAO,Março,FUNDAMENTAL COMPLETO,ALTO BRANCO,URBANA,2676060,2021,DENGUE C/ ALARME,08,02/25/21,NaN
52,26,MULHER,PARDO,VERAO,Fevereiro,SUPERIOR COMPLETO,RAMADINHA,URBANA,2362295,2021,DENGUE,06,02/12/21,NaN
58,25,MULHER,PRETO,VERAO,Março,ENSINO MÉDIO INCOMPLETO,MONTE CASTELO,URBANA,2363275,2021,DENGUE,10,03/08/21,NaN
64,6,HOMEM,PARDO,OUTONO,Junho,NÃO SE APLICA,VILA CABRAL,URBANA,7113692,2021,DENGUE,22,05/31/21,NaN
66,35,MULHER,BRANCO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,TRES IRMAES,URBANA,2363275,2021,DENGUE,26,06/29/21,NaN
71,69,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,LOUZEIRO,URBANA,2363275,2021,DENGUE,19,05/14/21,NaN
75,14,HOMEM,PARDO,INVERNO,Julho,1 GRAU INCOMPLETO,NOVO HORIZONTE,URBANA,7113692,2021,DENGUE,28,07/14/21,NaN
78,32,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,GALANTE,URBANA,7052251,2021,DENGUE,18,05/02/21,NaN
83,33,MULHER,BRANCO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,NaN,URBANA,2362856,2021,DENGUE,25,06/22/21,NaN
86,10,MULHER,PARDO,INVERNO,Agosto,1 GRAU INCOMPLETO,VELAME,URBANA,2363275,2021,DENGUE,32,08/11/21,NaN
88,27,MULHER,PARDO,INVERNO,Julho,SUPERIOR COMPLETO,CATOLE,URBANA,2362856,2021,DENGUE,28,07/11/21,NaN
89,56,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,BODOCONGO,URBANA,2363275,2021,DENGUE,30,07/28/21,NaN
93,31,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,CRUZEIRO,URBANA,2363275,2021,DENGUE,25,06/20/21,NaN
94,44,MULHER,PARDO,INVERNO,Julho,SUPERIOR COMPLETO,MALVINAS,URBANA,2363275,2021,DENGUE,28,07/11/21,NaN
97,34,MULHER,PARDO,OUTONO,Junho,SUPERIOR COMPLETO,CENTRO,URBANA,2363275,2021,DENGUE,21,05/23/21,NaN
99,31,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,LIGEIRO,URBANA,7052251,2021,DENGUE,18,05/02/21,NaN
103,73,HOMEM,PARDO,OUTONO,Junho,PRIMARIO COMPLETO,LIBERDADE,URBANA,2676060,2021,DENGUE,23,06/12/21,NaN
105,77,MULHER,PARDO,PRIMAVERA,Novembro,SUPERIOR COMPLETO,CATOLE,URBANA,3006204,2021,DENGUE,43,10/25/21,NaN
108,12,HOMEM,PARDO,PRIMAVERA,Outubro,1 GRAU INCOMPLETO,CENTENARIO,URBANA,2363275,2021,DENGUE,38,09/22/21,NaN
109,24,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,MONTE CASTELO,URBANA,2363275,2021,DENGUE,39,09/30/21,NaN
110,0,MULHER,PARDO,PRIMAVERA,Novembro,NÃO SE APLICA,VILA CABRAL,URBANA,7113692,2021,DENGUE,46,11/20/21,NaN
117,4,HOMEM,PARDO,VERAO,Dezembro,NÃO SE APLICA,PRATA,URBANA,2362856,2021,DENGUE,50,12/17/21,NaN
121,57,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,CRUZEIRO,URBANA,2676060,2021,DENGUE,19,05/15/21,NaN
126,35,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,2676060,2021,DENGUE,21,05/25/21,NaN
128,57,HOMEM,PARDO,OUTONO,Junho,SUPERIOR COMPLETO,SANTA ROSA,URBANA,2676060,2021,DENGUE,25,06/21/21,NaN
135,44,MULHER,PRETO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,MONTE CASTELO,URBANA,2595443,2021,DENGUE,37,09/14/21,NaN
137,59,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,CENTRO,URBANA,2676060,2021,DENGUE,24,06/17/21,NaN
143,65,HOMEM,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,MALVINAS,URBANA,2363275,2021,DENGUE,20,05/16/21,NaN
144,7,HOMEM,PARDO,INVERNO,Julho,NÃO SE APLICA,NOVO CRUZEIRO,URBANA,2363275,2021,DENGUE,28,07/14/21,NaN
146,10,MULHER,PARDO,INVERNO,Julho,PRIMARIO INCOMPLETO,CRUZEIRO,URBANA,2363275,2021,DENGUE,26,07/02/21,NaN
147,38,HOMEM,PARDO,OUTONO,Junho,PRIMARIO INCOMPLETO,GALANTE,URBANA,2363275,2021,DENGUE,25,06/20/21,NaN
150,47,HOMEM,BRANCO,PRIMAVERA,Novembro,PRIMARIO INCOMPLETO,JARDIM PAULISTANO,URBANA,2363070,2021,DENGUE,47,11/22/21,NaN
157,14,MULHER,PARDO,INVERNO,Julho,1 GRAU INCOMPLETO,TAMBOR,URBANA,2363275,2021,DENGUE,28,07/15/21,NaN
158,54,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,2363275,2021,DENGUE,27,07/07/21,NaN
160,9,HOMEM,BRANCO,OUTONO,Maio,PRIMARIO INCOMPLETO,JEREMIAS,URBANA,7113692,2021,DENGUE,20,05/16/21,NaN
165,17,HOMEM,PARDO,INVERNO,Agosto,FUNDAMENTAL COMPLETO,TRES IRMAES,URBANA,2676060,2021,DENGUE,29,07/21/21,NaN
171,48,HOMEM,PARDO,INVERNO,Agosto,SUPERIOR COMPLETO,CENTRO,URBANA,2363275,2021,DENGUE,33,08/19/21,NaN
174,38,HOMEM,PARDO,INVERNO,Julho,NaN,SANTA ROSA,URBANA,2362856,2021,DENGUE,29,07/21/21,NaN
191,63,MULHER,PARDO,PRIMAVERA,Novembro,NaN,LAGOA DE DENTRO,URBANA,2362856,2021,DENGUE,46,11/14/21,NaN
212,66,MULHER,PARDO,PRIMAVERA,Outubro,SUPERIOR INCOMPLETO,BODOCONGO,URBANA,2676060,2021,DENGUE,39,10/01/21,NaN
213,61,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,2363275,2021,DENGUE,29,07/21/21,NaN
216,54,MULHER,PARDO,INVERNO,Agosto,PRIMARIO INCOMPLETO,PRATA,URBANA,3006204,2021,DENGUE,29,07/22/21,NaN
218,80,HOMEM,BRANCO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,BAIRRO DAS NACOES,URBANA,3006204,2021,DENGUE,31,08/01/21,NaN
228,50,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,TAMBOR,URBANA,2363275,2021,DENGUE,34,08/23/21,NaN
236,66,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,2676060,2021,DENGUE,39,10/02/21,2.0
253,64,MULHER,PARDO,VERAO,Dezembro,ANALFABETO,BODOCONGO,URBANA,2363275,2021,DENGUE,49,12/07/21,NaN
256,50,MULHER,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,CATOLE,URBANA,2607336,2021,DENGUE,14,04/08/21,NaN
267,32,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,URBANA,2399989,2021,DENGUE,03,01/22/21,NaN
268,19,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,VILA CABRAL,URBANA,6940315,2021,DENGUE,36,09/09/21,NaN
269,19,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,VILA CABRAL,NaN,6940315,2021,DENGUE,33,08/15/21,NaN
270,20,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,VILA CABRAL,URBANA,6940315,2021,DENGUE,36,09/10/21,NaN
271,49,HOMEM,PARDO,INVERNO,Setembro,SUPERIOR COMPLETO,ACACIO FIGUEIREDO,URBANA,7646526,2021,DENGUE,37,09/16/21,NaN

In [114]:
np.unique(df_final2021['ZONA'].astype(str),return_counts=True)

(array(['URBANA', 'nan'], dtype=object), array([58,  1]))

In [115]:
df_final2021['ZONA'] = df_final2021['ZONA'].replace('nan','URBANA')

In [116]:
# This cell was removed as its functionality is redundant and causing errors. The df_final2021 DataFrame is created correctly in cell 'PaKONXZaZhlh' and 'ZONA' transformations are handled in 'zvMOByq9Zlc4'.

In [117]:
bairros={
    'ALUISIO CAMPOS': 'ALUIZIO CAMPOS',
    'BAIRRO DAS NACOES': 'NACOES',
    'BODOCONGO III': 'NOVO BODOCONGO',
    'CIDADES': 'BAIRRO DAS CIDADES',
    'NOVO CRUZEIRO': 'CRUZEIRO',
    'QUARENTA': 'JARDIM QUARENTA',
    'SÒO JOSÚ': 'SAO JOSE',
    'TRÛS IRMAS': 'TRES IRMAS',
    'BR 104 KM 119': 'JURACY PALHANO',
    'SANTA TREZINHA': 'SANTA TEREZINHA'
}
df_final2021['BAIRRO']=df_final2021['BAIRRO'].replace(bairros)

In [118]:
import pandas as pd
import numpy as np

unidades = {
    # --- Campina Grande (Rede Própria e Conveniada) ---
    220337:  "HOSPITAL DE CLINICAS DE CAMPINA GRANDE",
    248991:  "LABORATORIO PREANALITICA (PRIVADO)",
    2344386: "POLICLINICA MUNICIPAL DA PRATA (LIBERDADE)",
    2362201: "UBS SAO JOSE DA MATA",
    2362287: "INSTITUTO DE SAUDE ELPIDIO DE ALMEIDA ISEA",
    2362295: "SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE", # Secretaria de Saúde
    2362309: "CENTRO DE SAUDE DA LIBERDADE",
    2362627: "CAPS AD",
    2362821: "HEMOCENTRO REGIONAL DE CAMPINA GRANDE",
    2362856: "HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES",
    2363070: "HOSPITAL MUNICIPAL PEDRO I",
    2363275: "VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE",
    2595400: "UBS WESLEY CARIRI TARGINO (NOVA FLORESTA)",
    2595443: "UBS HORACINA DE ALMEIDA",
    2607123: "HOSPITAL DE OLHOS DA PARAIBA",
    2607336: "UBS UNIDADE MISTA DE GALANTE",
    2608650: "UBS RAIF RAMALHO (ACUDE NOVO)",
    2676060: "HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO",
    3006204: "CLINICA SANTA CLARA",
    5053250: "UBS VELAME",
    5053269: "UBS JARDIM VERDEJANTE",
    5932416: "UBS PEDREGAL I E II",
    6267939: "CENTRO DE GENETICA MEDICA",
    7052251: "UPA 24 HORAS DR MAIA (ALTO BRANCO)",
    7113692: "HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO",

    # --- Externos (João Pessoa, Santa Rita, Bayeux, etc) ---
    2052474: "HOSPITAL SANTA ISABEL (JOAO PESSOA)",
    2399318: "COMPLEXO PSIQUIATRICO JULIANO MOREIRA (JOAO PESSOA)",
    2399989: "HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA)",
    2806045: "UPA 24H DR OTAVIO PIRES (PATOS)",
    6346510: "HOSPITAL METROPOLITANO DOM JOSE MARIA PIRES (SANTA RITA)",
    6679528: "UPA 24H TIBIRI - JOSENILDO LEITE (SANTA RITA)",
    6940315: "UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)",
    6962831: "UPA 24H SOBEUS (GUARABIRA)",
    7408765: "UPA 24H NOVA ESPERANCA (PARNAMIRIM-RN)",
    7646526: "UPA 24H OCEANIA (JOAO PESSOA - BESSA)",
    7742878: "UPA 24H EZEQUIEL EPIFANIO (BAYEUX)",

    # --- Erros / Indefinidos ---
    396:     "CODIGO INVALIDO (ERRO DE REGISTRO)"
}

# 2. Lista apenas com os IDs de Campina Grande (Cód Mun 250400)
ids_campina_grande = [
    220337, 248991, 2344386, 2362201, 2362287, 2362295, 2362309,
    2362627, 2362821, 2362856, 2363070, 2363275, 2595400, 2595443,
    2607123, 2607336, 2608650, 2676060, 3006204, 5053250, 5053269,
    5932416, 6267939, 7052251, 7113692
]

# --- APLICAÇÃO NO DATAFRAME ---

# (Opcional) Converter para numérico caso esteja como texto
# df_final2023['UNIDADE DE ATENDIMENTO'] = pd.to_numeric(df_final2023['UNIDADE DE ATENDIMENTO'], errors='coerce')

# 1. Cria a coluna de Classificação (Interno/Externo) baseada na lista de IDs de CG
df_final2021['ORIGEM_UNIDADE'] = np.where(
    df_final2021['UNIDADE DE ATENDIMENTO'].isin(ids_campina_grande),
    'Campina Grande',
    'Externo/Outro'
)

# 2. Substitui os códigos pelos nomes descritivos
df_final2021['UNIDADE DE ATENDIMENTO'] = df_final2021['UNIDADE DE ATENDIMENTO'].replace(unidades)

In [119]:
np.unique(df_final2021['UNIDADE DE ATENDIMENTO'].astype(str),return_counts=True)

(array(['CLINICA SANTA CLARA',
        'HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES',
        'HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA)',
        'HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO',
        'HOSPITAL MUNICIPAL PEDRO I',
        'HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO',
        'SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE',
        'UBS HORACINA DE ALMEIDA', 'UBS UNIDADE MISTA DE GALANTE',
        'UBS WESLEY CARIRI TARGINO (NOVA FLORESTA)',
        'UPA 24 HORAS DR MAIA (ALTO BRANCO)',
        'UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)',
        'UPA 24H OCEANIA (JOAO PESSOA - BESSA)',
        'VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE'], dtype=object),
 array([ 3,  6,  1,  4,  1, 11,  2,  1,  1,  1,  2,  3,  1, 22]))

In [120]:
df_final2021['UNIDADE DE ATENDIMENTO'].value_counts()

UNIDADE DE ATENDIMENTO
VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE                   22
HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO                       11
HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZAGA FERNANDES     6
HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARVALHO             4
UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS)                     3
CLINICA SANTA CLARA                                            3
UPA 24 HORAS DR MAIA (ALTO BRANCO)                             2
SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE                2
UBS WESLEY CARIRI TARGINO (NOVA FLORESTA)                      1
UBS HORACINA DE ALMEIDA                                        1
HOSPITAL MUNICIPAL PEDRO I                                     1
UBS UNIDADE MISTA DE GALANTE                                   1
HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA)                   1
UPA 24H OCEANIA (JOAO PESSOA - BESSA)                          1
Name: count, dtype: int64

In [121]:
df_final2021['RAÇA'].value_counts()

RAÇA
PARDO     51
BRANCO     6
PRETO      2
Name: count, dtype: int64

In [122]:
df_final2021['BAIRRO'].value_counts()

BAIRRO
BODOCONGO            6
VILA CABRAL          5
MALVINAS             5
CENTRO               4
CRUZEIRO             4
CATOLE               3
MONTE CASTELO        3
GALANTE              2
PRATA                2
RAMADINHA            2
TRES IRMAES          2
TAMBOR               2
SANTA ROSA           2
NOVO HORIZONTE       1
ALTO BRANCO          1
NOVA BRASILIA        1
MONTE SANTO          1
LOUZEIRO             1
VELAME               1
LIGEIRO              1
CENTENARIO           1
LIBERDADE            1
JARDIM PAULISTANO    1
JEREMIAS             1
LAGOA DE DENTRO      1
NACOES               1
DINAMERICA           1
ACACIO FIGUEIREDO    1
Name: count, dtype: int64

In [123]:
neighborhood_frequency = df_final2021['BAIRRO'].value_counts().reset_index()
neighborhood_frequency.columns = ['Bairro', 'Frequência']

# Sort the DataFrame by frequency in descending order
neighborhood_frequency = neighborhood_frequency.sort_values(by='Frequência', ascending=False)

# Get the top N neighborhoods for better visualization (optional, adjust N as needed)
# For now, let's display all, but if there are too many, we might limit it.
# neighborhood_frequency_top = neighborhood_frequency.head(20)

# Create the bar chart
fig = plx.bar(
    neighborhood_frequency,
    x='Bairro',
    y='Frequência',
    title='Frequência de Casos por Bairro',
    labels={'Bairro': 'Bairro', 'Frequência': 'Número de Casos'},
    color_discrete_sequence=plx.colors.qualitative.Pastel
)

fig.update_layout(
    xaxis_title='Bairro',
    yaxis_title='Número de Casos',
    xaxis_tickangle=-45 # Rotate x-axis labels for better readability
)

fig.show()

In [124]:
df_final2021.shape

(59, 15)

In [125]:
sorotipos={
    1:'DENV 1',
    2: 'DENV 2',
    3: 'DENV 3',
    4: 'DENV 4'
}
df_final2021['SOROTIPO']=df_final2021['SOROTIPO'].replace(sorotipos)

In [130]:
df_final2021

,IDADE EM ANOS,SEXO DO PACIENTE,RAÇA,ESTACAO POR CASO,MES DO CASO,GRAU ESCOLARIDADE,BAIRRO,ZONA,UNIDADE DE ATENDIMENTO,DATA REGISTRO,CLASS DOENCA,SEMANA EPDM,DATA PRIMEIROS SINTOMAS,SOROTIPO,ORIGEM_UNIDADE
10,39,MULHER,PARDO,VERAO,Fevereiro,ENSINO MÉDIO COMPLETO,MONTE SANTO,URBANA,SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE,2021,DENGUE,06,02/10/21,NaN,Campina Grande
12,25,MULHER,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2021,DENGUE,02,01/12/21,NaN,Campina Grande
28,52,MULHER,BRANCO,INVERNO,Julho,PRIMARIO COMPLETO,BODOCONGO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,27,07/09/21,NaN,Campina Grande
33,32,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO INCOMPLETO,RAMADINHA,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,28,07/14/21,NaN,Campina Grande
34,36,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,CENTRO,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,32,08/08/21,NaN,Campina Grande
36,28,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,NOVA BRASILIA,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,28,07/14/21,NaN,Campina Grande
41,59,MULHER,PARDO,VERAO,Fevereiro,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,UBS WESLEY CARIRI TARGINO (NOVA FLORESTA),2021,DENGUE,06,02/08/21,NaN,Campina Grande
51,43,HOMEM,PARDO,VERAO,Março,FUNDAMENTAL COMPLETO,ALTO BRANCO,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE C/ ALARME,08,02/25/21,NaN,Campina Grande
52,26,MULHER,PARDO,VERAO,Fevereiro,SUPERIOR COMPLETO,RAMADINHA,URBANA,SERVICO MUNICIPAL CAMPINA GRANDE REGIONAL SAUDE,2021,DENGUE,06,02/12/21,NaN,Campina Grande
58,25,MULHER,PRETO,VERAO,Março,ENSINO MÉDIO INCOMPLETO,MONTE CASTELO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,10,03/08/21,NaN,Campina Grande
64,6,HOMEM,PARDO,OUTONO,Junho,NÃO SE APLICA,VILA CABRAL,URBANA,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2021,DENGUE,22,05/31/21,NaN,Campina Grande
66,35,MULHER,BRANCO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,TRES IRMAES,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,26,06/29/21,NaN,Campina Grande
71,69,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,LOUZEIRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,19,05/14/21,NaN,Campina Grande
75,14,HOMEM,PARDO,INVERNO,Julho,1 GRAU INCOMPLETO,NOVO HORIZONTE,URBANA,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2021,DENGUE,28,07/14/21,NaN,Campina Grande
78,32,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,GALANTE,URBANA,UPA 24 HORAS DR MAIA (ALTO BRANCO),2021,DENGUE,18,05/02/21,NaN,Campina Grande
83,33,MULHER,BRANCO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2021,DENGUE,25,06/22/21,NaN,Campina Grande
86,10,MULHER,PARDO,INVERNO,Agosto,1 GRAU INCOMPLETO,VELAME,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,32,08/11/21,NaN,Campina Grande
88,27,MULHER,PARDO,INVERNO,Julho,SUPERIOR COMPLETO,CATOLE,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2021,DENGUE,28,07/11/21,NaN,Campina Grande
89,56,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO INCOMPLETO,BODOCONGO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,30,07/28/21,NaN,Campina Grande
93,31,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,CRUZEIRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,25,06/20/21,NaN,Campina Grande
94,44,MULHER,PARDO,INVERNO,Julho,SUPERIOR COMPLETO,MALVINAS,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,28,07/11/21,NaN,Campina Grande
97,34,MULHER,PARDO,OUTONO,Junho,SUPERIOR COMPLETO,CENTRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,21,05/23/21,NaN,Campina Grande
99,31,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,LIGEIRO,URBANA,UPA 24 HORAS DR MAIA (ALTO BRANCO),2021,DENGUE,18,05/02/21,NaN,Campina Grande
103,73,HOMEM,PARDO,OUTONO,Junho,PRIMARIO COMPLETO,LIBERDADE,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,23,06/12/21,NaN,Campina Grande
105,77,MULHER,PARDO,PRIMAVERA,Novembro,SUPERIOR COMPLETO,CATOLE,URBANA,CLINICA SANTA CLARA,2021,DENGUE,43,10/25/21,NaN,Campina Grande
108,12,HOMEM,PARDO,PRIMAVERA,Outubro,1 GRAU INCOMPLETO,CENTENARIO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,38,09/22/21,NaN,Campina Grande
109,24,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,MONTE CASTELO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,39,09/30/21,NaN,Campina Grande
110,0,MULHER,PARDO,PRIMAVERA,Novembro,NÃO SE APLICA,VILA CABRAL,URBANA,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2021,DENGUE,46,11/20/21,NaN,Campina Grande
117,4,HOMEM,PARDO,VERAO,Dezembro,NÃO SE APLICA,PRATA,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2021,DENGUE,50,12/17/21,NaN,Campina Grande
121,57,MULHER,PARDO,OUTONO,Maio,ENSINO MÉDIO COMPLETO,CRUZEIRO,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,19,05/15/21,NaN,Campina Grande
126,35,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,21,05/25/21,NaN,Campina Grande
128,57,HOMEM,PARDO,OUTONO,Junho,SUPERIOR COMPLETO,SANTA ROSA,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,25,06/21/21,NaN,Campina Grande
135,44,MULHER,PRETO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,MONTE CASTELO,URBANA,UBS HORACINA DE ALMEIDA,2021,DENGUE,37,09/14/21,NaN,Campina Grande
137,59,HOMEM,PARDO,OUTONO,Junho,ENSINO MÉDIO COMPLETO,CENTRO,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,24,06/17/21,NaN,Campina Grande
143,65,HOMEM,PARDO,OUTONO,Maio,ENSINO MÉDIO INCOMPLETO,MALVINAS,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,20,05/16/21,NaN,Campina Grande
144,7,HOMEM,PARDO,INVERNO,Julho,NÃO SE APLICA,CRUZEIRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,28,07/14/21,NaN,Campina Grande
146,10,MULHER,PARDO,INVERNO,Julho,PRIMARIO INCOMPLETO,CRUZEIRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,26,07/02/21,NaN,Campina Grande
147,38,HOMEM,PARDO,OUTONO,Junho,PRIMARIO INCOMPLETO,GALANTE,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,25,06/20/21,NaN,Campina Grande
150,47,HOMEM,BRANCO,PRIMAVERA,Novembro,PRIMARIO INCOMPLETO,JARDIM PAULISTANO,URBANA,HOSPITAL MUNICIPAL PEDRO I,2021,DENGUE,47,11/22/21,NaN,Campina Grande
157,14,MULHER,PARDO,INVERNO,Julho,1 GRAU INCOMPLETO,TAMBOR,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,28,07/15/21,NaN,Campina Grande
158,54,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,27,07/07/21,NaN,Campina Grande
160,9,HOMEM,BRANCO,OUTONO,Maio,PRIMARIO INCOMPLETO,JEREMIAS,URBANA,HOSPITAL MUNICIPAL DR SEVERINO BEZERRA DE CARV...,2021,DENGUE,20,05/16/21,NaN,Campina Grande
165,17,HOMEM,PARDO,INVERNO,Agosto,FUNDAMENTAL COMPLETO,TRES IRMAES,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,29,07/21/21,NaN,Campina Grande
171,48,HOMEM,PARDO,INVERNO,Agosto,SUPERIOR COMPLETO,CENTRO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,33,08/19/21,NaN,Campina Grande
174,38,HOMEM,PARDO,INVERNO,Julho,NaN,SANTA ROSA,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2021,DENGUE,29,07/21/21,NaN,Campina Grande
191,63,MULHER,PARDO,PRIMAVERA,Novembro,NaN,LAGOA DE DENTRO,URBANA,HOSPITAL DE EMERGENCIA E TRAUMA DOM LUIZ GONZA...,2021,DENGUE,46,11/14/21,NaN,Campina Grande
212,66,MULHER,PARDO,PRIMAVERA,Outubro,SUPERIOR INCOMPLETO,BODOCONGO,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,39,10/01/21,NaN,Campina Grande
213,61,MULHER,PARDO,INVERNO,Julho,ENSINO MÉDIO COMPLETO,MALVINAS,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,29,07/21/21,NaN,Campina Grande
216,54,MULHER,PARDO,INVERNO,Agosto,PRIMARIO INCOMPLETO,PRATA,URBANA,CLINICA SANTA CLARA,2021,DENGUE,29,07/22/21,NaN,Campina Grande
218,80,HOMEM,BRANCO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,NACOES,URBANA,CLINICA SANTA CLARA,2021,DENGUE,31,08/01/21,NaN,Campina Grande
228,50,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,TAMBOR,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,34,08/23/21,NaN,Campina Grande
236,66,MULHER,PARDO,PRIMAVERA,Outubro,ENSINO MÉDIO COMPLETO,BODOCONGO,URBANA,HOSPITAL UNIVERSITARIO ALCIDES CARNEIRO,2021,DENGUE,39,10/02/21,DENV 2,Campina Grande
253,64,MULHER,PARDO,VERAO,Dezembro,ANALFABETO,BODOCONGO,URBANA,VIGILANCIA EPIDEMIOLOGICA DE CAMPINA GRANDE,2021,DENGUE,49,12/07/21,NaN,Campina Grande
256,50,MULHER,PARDO,OUTONO,Abril,ENSINO MÉDIO COMPLETO,CATOLE,URBANA,UBS UNIDADE MISTA DE GALANTE,2021,DENGUE,14,04/08/21,NaN,Campina Grande
267,32,HOMEM,PARDO,VERAO,Janeiro,ENSINO MÉDIO COMPLETO,DINAMERICA,URBANA,HOSPITAL GENERAL EDSON RAMALHO (JOAO PESSOA),2021,DENGUE,03,01/22/21,NaN,Externo/Outro
268,19,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,VILA CABRAL,URBANA,UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS),2021,DENGUE,36,09/09/21,NaN,Externo/Outro
269,19,MULHER,PARDO,INVERNO,Agosto,ENSINO MÉDIO COMPLETO,VILA CABRAL,URBANA,UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS),2021,DENGUE,33,08/15/21,NaN,Externo/Outro
270,20,MULHER,PARDO,INVERNO,Setembro,ENSINO MÉDIO COMPLETO,VILA CABRAL,URBANA,UPA 24H DR WALDEMAR ALCANTARA (CAJAZEIRAS),2021,DENGUE,36,09/10/21,NaN,Externo/Outro
271,49,HOMEM,PARDO,INVERNO,Setembro,SUPERIOR COMPLETO,ACACIO FIGUEIREDO,URBANA,UPA 24H OCEANIA (JOAO PESSOA - BESSA),2021,DENGUE,37,09/16/21,NaN,Externo/Outro

In [127]:
df_final2021['BAIRRO'].fillna('BODOCONGO',inplace=True)

/tmp/ipython-input-2117740645.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [129]:
df_final2021['ZONA'].fillna('URBANA',inplace=True)

/tmp/ipython-input-368585938.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [131]:
df_final2021['CLASS DOENCA'].value_counts()

CLASS DOENCA
DENGUE              58
DENGUE C/ ALARME     1
Name: count, dtype: int64

In [132]:
df_final2021.to_csv('dengue2021_tratado.csv', index=False)